### ISSUE TITLE
Maintain whitespace in attributes (single-line blocks)

### ISSUE THREAD

**Issue by tylersticka** [sebastienros/fluid#100]
I know that according to #42 and the README, whitespace is stripped from blocks, but this results in some unfortunate scenarios, particularly in HTML attributes.

As an example, if `class` is set to `is-current`:

```liquid
<div class="Example{% if class %} {{class}}{% endif %}"></div>
```

Expected:

```html
<div class="Example is-current"></div>
```

Actual:

```html
<div class="Exampleis-current"></div>
```

One short-term fix is to move the space outside of the `if` block, but then the attribute will have an unnecessary trailing space when `class` is `nil`:

```html
<div class="Example "></div>
```

The only way to avoid the space and get the same behavior is to prepare the attribute contents beforehand:

```liquid
{% assign _class = 'Example' %}
{% if class %}
  {% assign _class = _class | append: ' ' | append: class %}
{% endif %}

<div class="{{_class}}"></div>
```

But that's a lot more extra logic in the template.

Since the whitespace stripping was likely implemented to _reduce_ the amount of unnecessary spaces, I thought I'd flag the issue.

**Updated** with more accurate test case.

**Comment by sebastienros** [comment]
Looks like a bug to me. Not saying that when I will try to fix it I won't find it to be correct ...

**Comment by sebastienros** [comment]
I think that if it's on the same line, the spaces should be preserved.

**Comment by sebastienros** [comment]
It works fine with the version I am using. There is already a unit test for something like this. 

I am currently adding more tests to ensure `{%- -%}` works in all cases, which is not right now.

**Comment by tylersticka** [comment]
@sebastienros I just updated the original issue description with a more accurate test case. I had attempted to simplify my example, but in so doing I ended up simplifying away the issue! 😅

**Comment by sebastienros** [comment]
Makes more sense in the relationship with the automatic space removal feature. Adding it in a unit test to fix it (and the other issues I found).
