### ISSUE TITLE
Error if template contain "--"

### ISSUE THREAD

**Issue by hacbq** [sebastienros/fluid#111]
I get error: "Syntax error, expected: identifier, string1, string2, number, true, false at line:1, col:7"
with code:
` IEnumerable<string> errors = null;
 FluidTemplate.TryParse("{{  settings.a--b }}", out CHECKOUT_PARSE_TEMPLATE, out errors);`
I test shopify, it works fine

**Comment by hishamco** [comment]
What's the result that you got on Shopify?

**Comment by hacbq** [comment]
@hishamco it works correct
<img width="472" alt="screen shot 2019-02-12 at 20 57 10" src="https://user-images.githubusercontent.com/7564830/52640514-390ee780-2f09-11e9-8cc4-ba047b5bff57.png">
<img width="361" alt="screenshot at feb 12 20-58-31" src="https://user-images.githubusercontent.com/7564830/52640515-390ee780-2f09-11e9-8176-c52e0c99087c.png">
<img width="1015" alt="screenshot at feb 12 20-59-16" src="https://user-images.githubusercontent.com/7564830/52640516-39a77e00-2f09-11e9-8dd2-0822db9852fc.png">

**Comment by hishamco** [comment]
` settings.a--b` should work an display an empty string, but I'm not sure if `default` is sort of fallback?!! To fix this issue we need to modify the parser to accept such tokens, but if we don't provide a fallback, I'm agree with the current behavior /cc @sebastienros

**Comment by sebastienros** [comment]
I added the support for `-` in identifiers.
