### ISSUE TITLE
Custom tag stops working in the child context when used with custom template type

### ISSUE THREAD

**Issue by Sojaner** [sebastienros/fluid#112]
I have a custom tag class and a custom template type (as presented on the README.md), as following:

```
public class CustomTag : SimpleTag
{
    public override async Task<Completion> WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context, Expression term)
    {
        // Do something and create a statement

        return await statement.WriteToAsync(writer, encoder, context);
    }
  }
```
```
  public class CustomTemplate: BaseFluidTemplate<CustomTemplate>
  {
    static CustomTemplate()
    {
        Factory.RegisterTag<CustomTag>("mytag");
    }
  }
```

I parse and render using the following code:

```
  public string Generate(Model model)
  {
    if (!CustomTemplate.TryParse("{% include 'index' %}", out CustomTemplate template)) return string.Empty;

    TemplateContext context = new TemplateContext();

    context.SetValue("model", model);

    return template.Render(context);
  }
```

And in the `index.liquid` file I use the custom tag as `{% mytag %}`, however on the line with `return template.Render(context);` I get the following error (unless I call `FluidTemplate.Factory.RegisterTag<CustomTag>("mytag");` before):

```
Exception: Syntax error, expected: if, endif, elsif, else, unless, endunless, case, endcase, when, for, endfor, continue, break, comment, endcomment, raw, endraw, cycle, assign, capture, endcapture, increment, decrement, include at line:3, col:8
```

**Comment by hishamco** [comment]
Try to use `FluidViewTemplate.Factory.RegisterTag<CustomTag>("mytag");` similar to the one which we attach in the sample. If you have different scenario please provide a minimal repo that reproduce the error

**Comment by Sojaner** [comment]
@hishamco unless I'm missing something, the `FluidViewTemplate` class you mentioned doesn't seem to exist in the `Fluid` codebase (I'm using the engine individually and not together with the asp.net core view engine). I'm guessing you mean the `FluidTemplate` class.
My scenario is pretty simple and straightforward. I need 2 isolated instances of the engine which don't share the same set of custom tags and filters.
And the reason being, I need to render the same tag/filter differently depending on some factors (for instance for 2 different languages).
According to the documentation, the correct way of isolating the engine instances is to inherit from `BaseFluidTemplate<>` which I have done, but as explained above, the `Factory` registrations of the inherited type only work on the root context.

**Comment by hishamco** [comment]
The `FluidViewTemplate` is exist in the **Fluid.MvcViewEngine**, so if you aren't using ASP.NET Core this will be useless and you need to use `BaseFluidTemplate` instead

I suggest to share a minimal repo that reproduce the issue

**Comment by Sojaner** [comment]
Here is a simple code sample which represents the problem:
[https://github.com/Sojaner/FluidTest](https://github.com/Sojaner/FluidTest)
There are just a few files to inspect. Just take a look and run the project and you will figure it out.

**Comment by hishamco** [comment]
I did some experiments, seems the issue with the include tag, could you please use `{% text %}` as a template instead of including a liquid file, and let me know if you get the correct result?

**Comment by Sojaner** [comment]
@hishamco if I parse `{% text %}` directly, the code runs fine. However, my scenario involves including child views and that's where the problem appears.

As I mentioned in my initial comment, when I try to debug the code, at the point of rendering the `{% 
include 'file' %}` when the engine enters a child scope context, it loses access to the current isolated template and uses the global template context instead.

I'm thinking, the singleton pattern used in the library might not be the easiest to maintain, therefore I'm thinking of converting the static classes used as singletons into regular nonstatic and instead use a layer of singleton access on top of it. One example can be the dependency injection layer. Another can be a static instance.

What do you think of this approach? Are there any reasons why you didn't use them in the first place?

**Comment by hishamco** [comment]
@sebastienros your idea

**Comment by sebastienros** [comment]
I understand the problem, I will try to repro and fix.
