### ISSUE TITLE
Concurrency issue (NullReferenceException)

### ISSUE THREAD

**Issue by NooNameR** [sebastienros/fluid#118]
I have multi thread message consumer which creates every time new `TemplateContext` and set `MemberAccessStrategy` using same types, if I handle couple messages in the same time it will throw this exception. If there is the only one thread - everything is okay.
Version `<PackageReference Include="Fluid.Core" Version="1.0.0-beta-9545" />`

```
 class Program
    {
        public class Name
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        public class User
        {
            public Name Name { get; set; }
        }

        static async Task Main(string[] args)
        {
            await Task.WhenAll(Enumerable.Range(0, 3).Select(x => Consume()));
            Console.ReadLine();
        }

        static async Task Consume()
        {
            var model = new User {Name = new Name {FirstName = "Bill", LastName = "Gates"}};

            try
            {
                await Task.Delay(10);
                var context = new TemplateContext();
                context.MemberAccessStrategy.Register(typeof(User));
                context.MemberAccessStrategy.Register(typeof(Name));
                context.SetValue("p", model);
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
    }
```

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Fluid.MemberAccessStrategyExtensions.GetAllMembers(Type type)
   at Fluid.MemberAccessStrategyExtensions.Register(IMemberAccessStrategy strategy, Type type)
```

**Comment by NooNameR** [comment]
could be converted into test:
```
public class TemplateContextTests
    {
        private class TestClass
        {
            public string Name { get; set; }
        }

        [Fact]
        public async Task ShouldNotThrowException()
        {
            var exception = await Record.ExceptionAsync(() => Task.WhenAll(Enumerable.Range(0, 10).Select(x => Register())));

            Assert.Null(exception);
        }

        private static async Task Register()
        {
            await Task.Delay(10);
            var templateContext = new TemplateContext();
            templateContext.MemberAccessStrategy.Register(typeof(TestClass));
        }
    }
```

**Comment by NooNameR** [comment]
Hi, could u please check my PR. this issue really cause me exception

**Comment by sebastienros** [comment]
Can you try the latest version as I changed the way these lists are handling concurrency? In the meantime I will try your repro.

**Comment by NooNameR** [comment]
sorry, can’t get to my laptop. But I think I have latest version. I provide a test with my PR. you can easily catch an issue.

**Comment by sebastienros** [comment]
I am adding your unit test then, thanks.

**Comment by sebastienros** [comment]
Your unit test works fine on the latest version already, please try this nuget version: 1.0.0-beta-9554
Actually there is a big "fat" lock in the exact method you are testing now.

I would also suggest to register classes only once, I assume this shouldn't be a problem since you should know your classes at the time you use them.

**Comment by NooNameR** [comment]
I'm really sorry, but I do not see any locks in this place
https://github.com/sebastienros/fluid/blob/dev/Fluid/MemberAccessStrategyExtensions.cs#L18

And I really think the concurrent collections is more elegant way to fix this issue, but it's up to you to decide.

I've checked the test with latest code in this repo, and it throw me the same exception

**Comment by sebastienros** [comment]
I can see the issue now, I was focusing on the Register call which is locked, but you are right to say that the MemberAccessStrategy can fail. Your UT didn't fail for me but I assume it's just because it's non-deterministic. The idea behind non using CD anymore is for performance. I didn't want to manage two different implementations of MemberAccessStrategy, I used to, might have to go back to it.
