### ISSUE TITLE
Update the benchmarks

### ISSUE THREAD

**Issue by hishamco** [sebastienros/fluid#126]
@sebastienros it's the time to update the benchmarks to include `Scriban`, I run the benchmarks sample but i'm unable to get all the information that show up in the previous one

**Comment by jafin** [comment]
@Hishamco , I wrote a little tool to parse the benchmark.net results and create the image, mayby in future it could just be a CI step.  If useful I can send a PR.  (https://github.com/jafin/fluid/tree/feature/benchmark)

Here is the benchmark result (I updated the nugets to latest DotLiquid and Scriban as well)

![benchmarks](https://user-images.githubusercontent.com/127927/64487746-73631c00-d281-11e9-84f4-eca9420e091e.png)

**Comment by hishamco** [comment]
If I'm not wrong there's already exist in Fluid.Benchmarks, which creates a dynamic chart in Excel

Please have a look, and let us know if your tool added some value

/cc @sebastienros

**Comment by jafin** [comment]
@hishamco I see there is a excel spreadsheet, perhaps it has macros?  I unfortunately can't tell as I don't have Excel.  Anyhow all good if there is an existing approach to doing this.

**Comment by hishamco** [comment]
Is the above image produced by your tool, please wait for Seb reply

**Comment by hishamco** [comment]
@sebastienros could please have a look
