### ISSUE TITLE
'for' Loop Iterating One Too Many Times

### ISSUE THREAD

**Issue by jeffolmstead** [sebastienros/fluid#127]
According to the documentation at https://shopify.github.io/liquid/tags/iteration/ the following code:
```
{% for i in (0..1) %}
  {{ i }}
{% endfor %}
```
Should output 0 1 but inside fluid it outputs 0 1 2 (i.e. it loops one too many times).

**Comment by hishamco** [comment]
You're right, I can reproduce the bug, I'm working on it

thanks
