### ISSUE TITLE
Can you use redis as cache on ParseLiquidFile?

### ISSUE THREAD

**Issue by lzymll** [sebastienros/fluid#131]
as subject

**Comment by hishamco** [comment]
As I see here https://github.com/sebastienros/fluid/blob/1bac266d925b3e518cf839efa78904e67a10b859/Fluid.MvcViewEngine/FluidRendering.cs `InMemoryCache` is injected by default, @sebastienros can we replace this with generic cache, so the user is free to use the suitable caching mechanism

**Comment by sebastienros** [comment]
The resulting cached object is an AST, I don't see a reason it would make sense to cache it in a distributed way as the time to deserialize it and exchange it on the network would be worse.

What is you scenario that it would make sense to share an AST on redis?

For an analogy, comparing this to Razor, the compiled classes are not share across machines, they are loaded in memory in each node. But you might have a different concern I didn't grasp.

**Comment by lzymll** [comment]
If one server host multiple websites  like 10 or 20 ,  Will it cause memory short?  Redis may be is better choice for scalable.

**Comment by sebastienros** [comment]
These objects are usually small in memory, it takes more memory to just render a page actually. Also they are kept for a sliding hour, which means if a page is not hit, it's not taking any memory. And 10-20 sites is nothing. That could be an issue if you had thousands of it, and you would have other problems that this specific cache.

The only way to really now is for you to create a site with thousands of views, and just hit them in a loop and analyze the memory usage.
