### ISSUE TITLE
Async model members are not registered with async accessors

### ISSUE THREAD

**Issue by twgraham** [sebastienros/fluid#135]
I have a use case where some of the members on my template model are Tasks that should evaluate lazily. Currently, when I register my model with Fluid (`Register<Model>`), these members are not evaluated correctly.

e.g. A `Task<string>` will be evaluated as the value of `Task<>.ToString()`. I suspect this is because these members are being registered as `PropertyInfoAccessor` or `DelegateAccessor` rather than `AsyncDelegateAccessor`.

In the below scenario, the users would only be loaded if they are used inside the template when rendering.

```Csharp
public class GroupTemplateModel
{
    public string Name { get; set; }
    public Task<List<User>> Users => AsyncCallThatReturnsUserList();

    private static Task<List<User>> AsyncCallThatReturnsUserList()
    {
        // Do stuff here...
    }
}
```

*NB: I know that it would probably be wise to cache the results of these tasks for multiple access when rendering the template - In my own code I handle this using `AsyncLazy` from `Nito.AsyncEx`*

I'd be happy to make a PR. I've solved it by making small adjustments to the `MemberAccessStrategyExtensions`.

**Comment by sebastienros** [comment]
If you want to try an use `AsyncDelegateAccessor` when the result is async, please do it. Same for properties I assume.
