### ISSUE TITLE
Whitespace handling in the Parser

### ISSUE THREAD

**Issue by lukaskabrt** [sebastienros/fluid#138]
I haven't found any official specification of the Liquid template language, so I don't know what is correct behavior. But it seems that Fluid only accepts space as a whitespace character, although the original Liquid library accepts all whitespace characters (https://github.com/Shopify/liquid/blob/b3b63a683f6daaea7e70f1602ee829abdf970ef3/lib/liquid/lexer.rb#L22)

We have found this issue, when we were unable to parse a template for not an obvious reason. The parser returned error `Invalid character: ' '. at line:0, col:2`. It turned out, the template contained the non-breaking space (ASCII code 160) instead if the regular space.

**Comment by sebastienros** [comment]
I added this unit test and couldn't repro.

```csharp
        [Fact]
        public void ShouldParseNonBreakingWhitespace()
        {
            var c = (char)160;

            var result = FluidTemplate.TryParse("{{ 'a" + c + "' }}" + c + "{{ '" + c + "b' }}", out var template, out var errors);
            var rendered = template.Render();

            Assert.Equal("a" + c + c + c + "b", rendered);
        }
```

**Comment by lukaskabrt** [comment]
This one fails:

```
        [Fact]
        public void ShouldParseNonBreakingWhitespace() {
            var c = (char)160;

            var result = FluidTemplate.TryParse("{{" + c + "'a'" + c +"}}", out var template, out var errors);
            var rendered = template.Render();

            Assert.Equal("a", rendered);
        }
```

**Comment by hishamco** [comment]
Isn't covered in PR #102?!!

**Comment by sebastienros** [comment]
@lukaskabrt thanks, somehow I missed your answer, will check.
