### ISSUE TITLE
Support lazy type conversion

### ISSUE THREAD

**Issue by fubar-coder** [sebastienros/fluid#139]
It seems that the type conversion is done automatically when I use `SetValue`. Is it possible to do this type conversion lazily?

**Comment by sebastienros** [comment]
There is an overload for `SetValue` that accepts a `Func`:

`public TemplateContext SetValue<T>(string name, Func<T> factory)`

**Comment by fubar-coder** [comment]
I'll take a look if this fixes my problem that I want the type conversion only when the value gets accessed the first time.

**Comment by sebastienros** [comment]
The value conversion will be done on every call this way. As the Func can return anything.

**Comment by fubar-coder** [comment]
And that's the point: I want to set the value now, but I only want the type conversion when the value gets accessed.

**Comment by sebastienros** [comment]
SetValue has a Lazy behavior overload
