### ISSUE TITLE
StringValue.WriteTo causes NullReferenceException

### ISSUE THREAD

**Issue by fubar-coder** [sebastienros/fluid#140]
Example:

```csharp
new StringValue("Test").WriteTo(new StringWriter(), null, null);
```

The statement above shouldn't throw as the encoder of a `TemplateContext` could be `null`.

The code should be changed to:

```csharp
            if (String.IsNullOrEmpty(_value))
            {
                return;
            }

            if (Encode && encoder != null)
            {
                encoder.Encode(writer, _value);
            }
            else
            {
                writer.Write(_value);
            }
```

**Comment by hishamco** [comment]
Did you try `NullEncoder.Default`

**Comment by fubar-coder** [comment]
No, but the problem is that I didn't expect to at a default encoder.

**Comment by hishamco** [comment]
@sebastienros can we set default encoder instead of `null`?

**Comment by fubar-coder** [comment]
OK, I'll change my source to use `NullEncoder.Default`, which is the correct thing to do.

Don't use my proposed solution, because it would be better to check if the `encoder` parameter is `null` in the `IFluidTemplate.RenderAsync` implementation.

**Comment by sebastienros** [comment]
I agree we could default to it if the value is null. Or at least throw an ArgumentNullException. This API should only be called from custom values I assume. It would help remind that it's required.
