### ISSUE TITLE
Request for a new DotNet Core version

### ISSUE THREAD

**Issue by egandro** [sebastienros/fluid#146]
It looks like the DotNet Core version is outdated.

`TemplateContext.GlobalMemberAccessStrategy.MemberNameStrategy = MemberNameStrategies.CamelCase;
`

MemberNameStrategy  is not available.

**Comment by sebastienros** [comment]
I published it, it's available on nuget now.

Note: There is no specific version for Core, we publish a single package that target both .NET Framework and .NET Core.

**Comment by egandro** [comment]
Thx for your time!

This really helped :) 

I just forgot the [x] include prerelease button.
