### ISSUE TITLE
Date format not working with datetime in seconds

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#147]
Moved this issue from oc to fluid like @hishamco said.
https://github.com/OrchardCMS/OrchardCore/issues/4104

If you search online how to add days to a datetime, the solution mentioned in the referenced issue is the inteded way.
I don't know if it's a bug or if I have to do it differently with oc fluid.

**Comment by hishamco** [comment]
I will check this one

**Comment by sebastienros** [comment]
The issue was that `{{ 1234 | date: "%Y, %m, %d" }}` would not work as `date` would not accept a number as its input. It should actually read this as a unix date if it's a number, which I fixed.

**Comment by Flarescape** [comment]
@sebastienros thank you very much for the quick fix!
