### ISSUE TITLE
Add a timeout for rendering

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#15]
Or limit how many statements can be executed.
There would otherwise be a risk of taking a server down if a script is badly written.

See Jint on how to implement it.

**Comment by hishamco** [comment]
IMHO timeout is better option than limit how many statements can be executed

**Comment by sebastienros** [comment]
In the same topic, stackoverflow should be prevented. Right now I think it's possible with `include` statements. I can't think of anything else.

**Comment by hishamco** [comment]
Yep `include` is expensive sometimes, so I'm still thinking to handle this at document level not filter level

**Comment by sebastienros** [comment]
This will probably be my next task. This is quite critical.
