### ISSUE TITLE
Need ability to override FluidValue.Create

### ISSUE THREAD

**Issue by cabal95** [sebastienros/fluid#158]
We have run into an issue with using dictionaries in Fluid Filters. FluidValue.Create() wraps the dictionaries in a special DictionaryDictionaryFluidIndexable object. That would normally be fine if our filter was just trying to access specific keys. But we have a few filters that expect to be able to work with real dictionary objects (IDictionary<string, object>). For example, sorting, filtering, etc. using LINQ. Another example is we have a `ToJSON` filter that dumps out the object as a JSON object.

All of these filters currently require access to private fields so that we can gain access to the real dictionary to do our processing with. We would rather not have to use reflection to access private fields. We looked into using the FluidValue.SetTypeMapping() method, but that would require an exact Type match, meaning if we have a custom object that implements `IDictionary<string, object>` (which we have a few) it would still end up being wrapped in the `DictionaryDictionaryFluidIndexable` object.

To that end, we see two options that would allow us to deal with this:

1. Ability to have a way to specify a custom FluidValue.Create() handler. Specifically, probably something that FluidValue.Create() would call and if non-null is returned, then that value is used, otherwise the normal processing continues.
2. `ToObjectValue()` would be modified on `DictionaryFluidValue` to return the actual underlying dictionary itself - or possibly a new method that would gain us access.

If one of these options, or any third option we can come up with, sounds good then I can work on a pull request to submit the code. Would just need to know which path would be preferable.

**Comment by hishamco** [comment]
> That would normally be fine if our filter was just trying to access specific keys. But we have a few filters that expect to be able to work with real dictionary objects (IDictionary<string, object>). For example, sorting, filtering, etc. using LINQ

I think you are able to use LINQ queries with `DictionaryDictionaryFluidIndexable`, perhaps it will be little tricky because there's no `Values` property ;)

Could you please provide a repo for one sample, I will try to look into

**Comment by cabal95** [comment]
Sure... Do you have more specific requirements of what you want the repo to show? Meaning, what I'm describing isn't a bug that I can just throw together a few pieces of code to show the crash.

If you are just wanting a sample showing what we are trying to accomplish then I can do that. Though the most basic example is the one I described originally of a `ToJSON` filter that converts the input into a JSON string. If that is good enough I can do a quick project to show how that doesn't work.

**Comment by hishamco** [comment]
I'm interesting on the one with LINQ ;) but in both ways, is return the underlying dictionary is enough for you? Coz if yes I don't think there's an issue if there 're some use cases that require to expose such property

**Comment by cabal95** [comment]
Yes, I think that would solve all the issues. We've been using Reflection to get to the "real" object and that appears to have solved all our roadblocks thus far. I'll see if I can work up a small sample project showing one of the LINQ usages are are trying to accomplish.

**Comment by hishamco** [comment]
@sebastienros can we expose the underlying dictionary for `DictionaryDictionaryFluidIndexable`?

**Comment by cabal95** [comment]
Also, just to be clear, I am hoping that the `DictionaryFluidValue` itself can be changed to return the actual dictionary instead of returning the `ObjectDictionaryFluidIndexable` wrapper. Currently, every other `FluidValue` type returns a real object, even arrays. Dictionary is the only one whose `ToObjectValue()` method doesn't follow this same pattern.

If that isn't possible and we are going to have to unwrap it ourselves we'll make do, it just means we have to do a lot more type checking everywhere. Though it seems to me that it would make more sense for it to follow the pattern of every other value type.

Attached is a sample project. It obviously doesn't work correctly because of the described issues in this conversation, but it did work correctly in DotLiquid as it deals with original objects instead of wrappers. We are trying to convert away from DotLiquid so that we can eventually switch our larger project to .NET Core.

[FluidSample.zip](https://github.com/sebastienros/fluid/files/4270762/FluidSample.zip)

**Comment by hishamco** [comment]
> Currently, every other FluidValue type returns a real object, even arrays. Dictionary is the only one whose ToObjectValue() method doesn't follow this same pattern.

On this I'm agree, perhaps the right return object is `IDictionary`

**Comment by hishamco** [comment]
@sebastienros could please let me know what's the difference between `DictionaryDictionaryFluidIndexable`, `FluidValueDictionaryFluidIndexable` and `ObjectDictionaryFluidIndexable`? Why we can't use `DictionaryValue` only?

**Comment by sebastienros** [comment]
I think this issue can be closed since there are "converters" now that let you return anything you want when an object is converted to a FluidValue. Please let me know if there is still an issue with it, sorry it took so long to answer, I just noticed this issue.
