### ISSUE TITLE
Multiline support

### ISSUE THREAD

**Issue by AmbroiseCouissin** [sebastienros/fluid#159]
Hi there!

The following template source doesn't seem to parse:
```
{{ "some long line \n hello" }}
{{ "something with a new line

...like this is after a new line"}}
```

I then use this:
```
FluidTemplate.TryParse(drawing.LiquidSource, out FluidTemplate template, out IEnumerable<string> fluidTemplateErrors);
```

I get the following error:
```
Mal-formed  string literal - cannot find termination symbol. at line:2, col:4
```

It's supposed to be supported by liquid apparently.

Am I forgetting something?

Thanks!

**Comment by hishamco** [comment]
Did you try this one:

```liquid
{{ "some long line
hello
something with a new line" }}
```

**Comment by sebastienros** [comment]
There might be two bugs here:
- the \n escape sequence might not be parsed. Actually I am not even sure Liquid supports that, couldn't find an example
- the string literal should accept new lines

**Comment by sebastienros** [comment]
In the end one or the other needs to be fixed. Because if you want string literals with new lines, you either need to be able to write one, or to write and escape sequence.

Can you help me and find out what Liquid suggests for this? I saw that DotLiquid doesn't support either for instance.

**Comment by sebastienros** [comment]
I fixed the line breaks in the string literals (your second example) and confirmed with a unit test that the first example (escape sequence) is handled correctly. Which might be seen as a non-standard liquid syntax.

**Comment by AmbroiseCouissin** [comment]
Hi @sebastienros, thanks a lot!

I checked that it was supported by liquid with the official vscode liquid previewer:
https://blog.lfalck.se/liquid-template-editing-in-visual-studio-code/
