### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by nixa333** [sebastienros/fluid#161]
Are nested properties supported?
I've tried following code just to test the support, but doesn't seem to work. Is there something I need to do to get it to work?

```csharp
var model = new 
{ 
    Firstname = "Bill", 
    Lastname = "Gates", 
    Data = new 
    { 
        Text = "Text", 
        Image = "src" 
    } 
};

var source = "Hello {{ Firstname }} {{ Lastname }} <img src=\"{{ Data.Image }}\"> {{ Data.Text }}";
}

@if (FluidTemplate.TryParse(source, out var template))
{
    var context = new TemplateContext();
    context.MemberAccessStrategy.Register(model.GetType());model to be used
    context.Model = model;

    <div>@template.Render(context)</div>

}
```

This is the output:

```html
Hello Bill Gates <img src="">
```

**Comment by sebastienros** [comment]
The inner type in Data is a different route that needs to be registered too in this case.

**Comment by nixa333** [comment]
@sebastienros well that was easy, thanks! :D

**Comment by nixa333** [comment]
@sebastienros one mor equestion while we're on it, if the Data is a dynamic type, how would I register it?

**Comment by sebastienros** [comment]
There is no such thing as dynamic types ;) What usually happens is that you have something like JObject which is the result of a dynamic deserialization, or something similar. But the types are well known. Otherwise please share an example of what you might do.

**Comment by nixa333** [comment]
Sorry, yes, I meant that I have a property that is declared as dynamic
```csharp
public dynamic Data { get; set; }
```

I've since replaced the declaration with 
```csharp
public object Data { get; set; }
```
and it's fine now.

**Comment by sebastienros** [comment]
That would still work. We do this in Orchard Core to expose a JObject actually.
