### ISSUE TITLE
How can I set the timezone for dates?

### ISSUE THREAD

**Issue by poneymusical** [sebastienros/fluid#162]
Hello,

I'm having issues with dates rendering, specifically the timezone. The included project 
[ExampleTimezoneIssue.zip](https://github.com/sebastienros/fluid/files/3788303/ExampleTimezoneIssue.zip) reproduces the issue.

In my model, I set a DateTime value, and it uses my current timezone (GMT +02:00). When I use ToString("O"), I get the correct timezone (mine).

When I render the template and check the output, the timezone used seems to be GMT and not GMT +02:00. 

Is there any way I can tell Fluid to use my timezone?

Thanks in advance for your help!
Regards,
Guillaume.

**Comment by sebastienros** [comment]
By default, if you use a `DateTime` directly from C# to liquid, rendering it will use the `u` Universal sortable date/time pattern which removed the timezone component.

What you want is to use the default date format string like this: https://shopify.github.io/liquid/filters/date/ and https://help.looker.com/hc/en-us/articles/360023800253-Easy-Date-Formatting-with-Liquid

This way you can use predefined formats or build yours. For instance in your example you can try `{{ model.Date | date: '%c'}}`

Then if you need to move from one timezone to the other, an option is to convert it to `%s` which will give you a number, that you can add a value to it (to shift it) then convert it back to the `| date` filter, but I don't think you will need it.
