### ISSUE TITLE
Where filter NRE when full path does not exist.

### ISSUE THREAD

**Issue by jptissot** [sebastienros/fluid#167]
Trying to access a deep nested property throw an NRE if the full path does not exist.

Example : 

`{% assign selectedVolunteers = volunteers | where: "Content.ParticipantPart.Selected.Value", true %}`

This throws a NRE when Selected does not exist where it should return a falsy value.

**Comment by hishamco** [comment]
IMHO NRE is the good indication that the object in `null` unless the liquid specification mentioned that it should return a false value

**Comment by jptissot** [comment]
It is null, the issue is that instead of throwing, it should imo use a null propagation operator instead of throwing.

**Comment by sebastienros** [comment]
It should not throw (nothing in liquid should) and the value returned by the expression should be the NilValue.
