### ISSUE TITLE
"limit" attribute for for-loop does not accept variables

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#168]
This gives the following error: `Syntax error, expected: number at line:23, col:31`
![image](https://user-images.githubusercontent.com/1375119/72365859-58a22780-36f9-11ea-8442-2fc952a15cc8.png)

This is working:
![image](https://user-images.githubusercontent.com/1375119/72366096-e0883180-36f9-11ea-943d-26c6a403a795.png)

**Comment by hishamco** [comment]
I will try to implement or fix this once I got time
