### ISSUE TITLE
Array initialization

### ISSUE THREAD

**Issue by AmbroiseCouissin** [sebastienros/fluid#171]
Hi there!

In the following link (http://www.codeshopify.com/blog_posts/building-arrays-with-liquid-in-shopify), shopify shows how to initialize array with splits.

This is the snippet:
```
{% assign cheeses = "cheddar, swiss, gouda, havarti, string" | split: ','%}
```

It looks like it is not working with Fluid. What would be the best practice?

Cheers!

**Comment by TFleury** [comment]
Hi @AmbroiseCouissin,

Here is the correct usage (https://shopify.github.io/liquid/filters/split/)

The correct syntax should be :
```
{% assign cheeses = "cheddar,swiss,gouda,havarti,string" | split: "," %}
```
or
```
{% assign cheeses = "cheddar, swiss, gouda, havarti, string" | split: ", " %}
```
