### ISSUE TITLE
Allow combination of capture and assign in one statement

### ISSUE THREAD

**Issue by eddyjl077** [sebastienros/fluid#172]
Would it be possible to combine capture and assign statement together?

For example, instead of writing

{% capture productData %}
	{% schemadata 'products'  | filter : categoryid=5 %}
{% endcapture %}

{% assign products = productData | jsonparse %}

{% for p in products %}
  {{p.name}} 
  {{p.price}}
{% endfor %}

I would prefer to write 

{% set products | jsonparse %}
	{% schemadata 'products' | filter : categoryid=5 %}   <--
{% endset %}

{% for p in products %}
  {{p.name}} 
  {{p.price}}
{% endfor %}

or any better way?

**Comment by sebastienros** [comment]
Won't do that since it's not standard and only you would use it. But you can definitely add a custom tag that would do it, even by altering the current capture statement.
