### ISSUE TITLE
Question: is there a way to loop through and render Dictionary items

### ISSUE THREAD

**Issue by srinivasrb** [sebastienros/fluid#173]
Is there a way to iterate through a Dictionary object and render a value by key?

Thanks!

**Comment by limeschool** [comment]
I ran into this same problem. One thing that might help: you can incorporate the Dictionary object in your context, allowing you to call something like ``page.key`` to get the value, so long as the key is a string.

**Comment by sebastienros** [comment]
Found a way.

Dictionaries are converted to lists of tuples. So this code works:

```
{% for c in Capitals %}{{ Capitals[c.first] }}{% endfor %}
```

which is equivalent to this one if we don't care about the Key:

```
{% for i in Capitals %}{{ i[1] }}{% endfor %}
```
