### ISSUE TITLE
QUESTION: Where does the include tag look for files?

### ISSUE THREAD

**Issue by limeschool** [sebastienros/fluid#174]
Before you tell me to just Google this, I have. I know this seems super simple and obvious but for the life of me I cannot figure it out.

I have two files: `index.liquid` and `include.liquid` in a folder called `_posts` (and no, this isn't Jekyll).

In `index.liquid`:

```
{% include 'include' %}
```

I have tried changing this to `{% include '/_posts/include' %}` and `{% include '_posts/include' %}` but this always yields a FileNotFound exception from Fluid. Where is Fluid looking?

**Comment by limeschool** [comment]
Apologies for taking your time with something so trivial, @sebastienros, but I really cannot find how this is handled in Shopify Liquid (in fact, the most relevant documentation was on how `render` has replaced `include` now).

**Comment by hishamco** [comment]
Does `_posts` inside the `Views` folder? Please refer to [Fluid.MvcSample](https://github.com/sebastienros/fluid/tree/dev/Fluid.MvcSample)
