### ISSUE TITLE
"limit" attribute on for-loop no longer working

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#178]
After my latest update to the newest nightly dev version of OC, limit isn't working at all.
My latest issue was about using variables with the limit attribute: #168 

In the current version, neither a variable nor a fixed number works with the limit attribute.
If I try the following (Array Digits = [1,2,0,0,0,0,0]):
```liquid
{% for digit in digits limit:2 %}
	{{ digit }}
{% endfor %}
```
This happens:
![image](https://user-images.githubusercontent.com/1375119/76338183-a3ef4580-62f8-11ea-8fc1-3fbb8d184129.png)

When I try it with a variable, the error of the above issue occurs.

**Comment by sebastienros** [comment]
We recently changed something related to `limit`: https://github.com/sebastienros/fluid/commit/6983b6d9fb6139b846b45a1c4a609f01669f545d

In your case, is `digits` an array value set from c# ?

**Comment by sebastienros** [comment]
I just tried this test and it works fine, can you adapt it to make it fail?

```
        [Fact]
        public void ShouldParseLimit()
        {
            var source = @"{% for digit in digits limit:2 %}{{ digit }}{% endfor %}";

            var result = FluidTemplate.TryParse(source, out var template, out var errors);
            var context = new TemplateContext();
            context.SetValue("digits", new[] { 1, 2, 3, 4 });

            var rendered = template.Render(context);

            Assert.Equal("12", rendered);
        }
```

**Comment by Flarescape** [comment]
Thanks for your quick reply!

No, digits is an array created by a liquid split attribute.
My whole code is just an experiment to format a number as price/salary:
I just added this comments here, they don't exist in my actual liquid file.
```liquid
{% assign ds = Model.Ds | default:',' %} //the decimal separator 
{% assign ts = Model.Ts | default:'.' %} //the thousands separator
{% assign numdecimals = Model.Decimals | default:2 | abs %} //digits behind the decimal point
{% assign parts = Model.Number | round:numdecimals | downcase | split:'.' %} //the number to format
{% assign digits = parts[0] | downcase | split:'' %}
{% capture formatedNumber %}
{% for digit in digits %}
	{% assign threeFromEnd = digits.size | minus:forloop.index | modulo: 3 %}
	{% if threeFromEnd == 2 and forloop.index != 1 %}
		{{ digit | prepend: ts }}
	{% else %}
		{{ digit }}
	{% endif %}
{% endfor %}
{% if numdecimals > 0 %}
	{{ ds }}
	{% if parts.size == 1 %}
		{% assign decs = '0000000000' %}
	{% else %}
		{% assign decs = parts[1] | append:'0000000000' %}
	{% endif %}
	{% assign digits = decs | split:'' %}
	{% for digit in digits limit:2 %} //this is where the error occurs, no matter if i use a number or a variable. Before my latest update, a fixed number worked. I would like to use "numdecimals" here.
		{{ digit }}
	{% endfor %}
{% else %}
	{{ ds }}-
{% endif %}
{% endcapture %}
{{ formatedNumber | strip_newlines | remove: "	" }}
```

**Comment by sebastienros** [comment]
Can you share a simple repro, which wouldn't require models, and go straight to the issue?

**Comment by Flarescape** [comment]
Sorry for my late update to this issue, but I think it solved itself.
At the time this issue occurred I was on the latest dev branch.
Now I've tested this again with the current latest version and it works with both, a fixed number and a variable.
Thank you!
