### ISSUE TITLE
InvalidCastException on HtmlEncoder for {%capture%} with Shape inside

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#180]
I hope that this issue is related to fluid and not OC, else I'm sorry and I have to move it.

This is the scenario:
I have this in my liquid template in the OC backend:
`{%capture uitest %}{{"UniqueIdentifierHelper" | shape_new | shape_render }}{%endcapture%}`

This in the `UniqueIdentifierHelper.cshtml` in the theme:
```csharp
@{ 
    Guid ui = Guid.NewGuid();
}
@ui
```

Which results in this error:
`InvalidCastException: Unable to cast object of type 'Fluid.NullEncoder' to type 'System.Text.Encodings.Web.HtmlEncoder'.
OrchardCore.DisplayManagement.Liquid.HtmlContentValue.WriteTo(TextWriter writer, TextEncoder encoder, CultureInfo cultureInfo) in HtmlContentValue.cs, line 60`

Also if I try to use `assign` instead of `capture`, I'm able to display the variable with the expected value from the `UniqueIdentifierShape`, but I can't do anything with it because it's not a string value.
So e.g. `| downcase` results in the same thing as the following thing.
If i try `...shape_render | raw` ( #90 ) it just outputs this:
`Microsoft.AspNetCore.Mvc.ViewFeatures.Buffers.ViewBuffer`

I've found out that `capture` is doing this inside the `CaptureStatement.cs` and thats where the `NullEncoder` is set (but I'm not completely sure because I'm not able do debug the Fluid.dll):
```liquid
completion = await Statements[index].WriteToAsync(sw, NullEncoder.Default, context);
```

Then, as the error says, inside the `HtmlContentValue.cs` this cast at line 60 happens:
```csharp
_value.WriteTo(writer, (HtmlEncoder)encoder);
```

**Comment by sebastienros** [comment]
Old issue, please re-open if you can still repro.
