### ISSUE TITLE
Add location info to ParseException if available

### ISSUE THREAD

**Issue by twgraham** [sebastienros/fluid#183]
Getting parse exceptions is a pretty common occurrence when users are drafting up liquid. e.g. not closing tags, invalid tag format etc. It would be really helpful if the location of the error was more readily available [instead of part of the parse error](https://github.com/sebastienros/fluid/blob/6983b6d9fb6139b846b45a1c4a609f01669f545d/Fluid/DefaultFluidParser.cs#L918).

I suppose what I am proposing is something like:
```csharp
public class ParseException : Exception {
    // ... rest of class

   public SourceLocation Location { get; set; }
}
```

This information could be provided on a best effort basis. If the parse exception can't pinpoint an exact location (e.g. template file missing), then the location could be null.

**Comment by sebastienros** [comment]
Should be supported now. The parser was reimplemented.
