### ISSUE TITLE
Add ability to check available properties in Scope

### ISSUE THREAD

**Issue by twgraham** [sebastienros/fluid#185]
Currently, you can only get or set specific values on a scope. It would be useful if `Scope`'s could share what properties were available to them. For example, being able to check all the top level properties on the current `TemplateContext` could be used to tell the user what properties are available.

In my case, I'd like to make a JSON tag or filter that could return a JSON representation of the available data, or provided expression.

I'd propose a change like the following:
```csharp
public class Scope
{
    // ... rest of class omitted for brevity

    public List<string> Properties => _properties.Keys.ToList()
}
```

This way I could see all the properties, and get values for the properties I want.

**Comment by hishamco** [comment]
@sebastienros is sound looks good to you?

**Comment by Soar360** [comment]
I also need this feature, which is very useful when printing debugging information. Currently, I rely on reflection to implement this functionality, but it's ugly.
