### ISSUE TITLE
Dotliquid markup

### ISSUE THREAD

**Issue by matengo** [sebastienros/fluid#189]
We have an application that uses DotLiquid with the object member markup/strategy for example model.First_Name, if the source property name is FirstName. 
We would like to migrate to .Net Core and Fluid. But there is thousands of views using this pattern and I can see that Fluid is case sensitivie and the member strategy can be changed to CamelCase or Snake case, that won't accept for example model.First_Name.. Is there any way that we can accept this type of member strategy/pattern? So that we don't have to change all our customers views before we move to Fluid..?

**Comment by sebastienros** [comment]
The existing MemberStrategy allows for customizing properties mapping, and already supports snake case.
