### ISSUE TITLE
Add startswith/endswith operators

### ISSUE THREAD

**Issue by TFleury** [sebastienros/fluid#197]
For discussion

I know they are not part of shopify liquid but they could be helpful.

It seems they are implemented in PowerApps and DotLiquid.

**Comment by hishamco** [comment]
Could you please provide an example? or is it similar to what `string` in .NET have?

**Comment by TFleury** [comment]
Yes, it's just the String StartsWith and EndWith implementation.

Here is the documentation for PowerApps :
https://docs.microsoft.com/en-us/powerapps/maker/portals/liquid/liquid-operators#startswith

**Comment by hishamco** [comment]
@sebastienros is this look good for you to implement? if YES I can push a PR for it

**Comment by hishamco** [comment]
I think this could be implemented as filter not a tag

**Comment by sebastienros** [comment]
Fluid now supports custom operators. These can be added by configuration.

I assume it's fine to add them out of the box. I wonder what name they should have though, `startswith`, `starts_with`.

**Comment by TFleury** [comment]
> I wonder what name they should have though, `startswith`, `starts_with`

It's `startswith` in PowerApps and `startsWith` in dotliquid. Both are fines, but I less for using snake_case for an operator.
Are operators case sensitive ?

In addition, if you add `startswith` and `endswith`, it could also be fine to have `contains`.

The dotliquid implementation seems to handle string values, but also array values.

**Comment by hishamco** [comment]
@TFleury could you start a PR for it?
