### ISSUE TITLE
Question: support for enum types?

### ISSUE THREAD

**Issue by RobWalker** [sebastienros/fluid#199]
Is it possible to support a syntax like:

```
{% if field.FieldType == FieldType.Currency %}
 ...
{% endif %}
```

Where `FieldType` is a registered .NET type.

Currently I am having to resort to adding boolean properties:

```
{% if field.IsCurrency %}
...
{% endif %}
```

Which works, but is a bit ugly on the external classes.

Thanks!

**Comment by sebastienros** [comment]
There are two ways to convert dotnet types to fluid values. You could convert FieldType to StringValue automatically. Should be explained in the readme. If you can't find it I'll give you some sample.

**Comment by RobWalker** [comment]
Thanks for the quick response!

Converting to a string value works great.
