### ISSUE TITLE
Implement Escape Tag

### ISSUE THREAD

**Issue by hishamco** [sebastienros/fluid#20]
@sebastienros it would be nice if we have an escape tag for temporarily disables tag processing. It is something similar to [`Raw`](https://shopify.github.io/liquid/tags/raw/) in liquid

**Comment by sebastienros** [comment]
There is the raw tag already. How would it be better?

**Comment by hishamco** [comment]
Oh really .. I though it's not implemented yet
Could you please refer it to me?

**Comment by sebastienros** [comment]
https://github.com/sebastienros/fluid/blob/5beaf78508a65b7b8e40cc73f3016e58a6fb8bba/Fluid.Tests/ParserTests.cs#L111

**Comment by hishamco** [comment]
Thanks
