### ISSUE TITLE
Bug: Loop parameter changes global variable 

### ISSUE THREAD

**Issue by antifree** [sebastienros/fluid#201]
For example, I have a global variable post, which contains information about current post. I want to show a list of similar posts and loop throw them using the post variable in a loop. And the problem is that after loop my current post changed the value to the last value of posts list. I think this problem occurs because child scope was removed from for block #55.

Here is an example:
```
<h3>Post title before: {{post.title}}</h3>
<div class="row">
    <div class="col-md-4">
        {% for post in posts %}
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">
                    <a href="{{post.fullPath}}">{{post.title}}</a>
                </h5>
                <p class="card-text">{{post.datePublished |  date: "%Y-%m-%d" }}</p>
                <a href="{{post.fullPath}}" class="btn btn-link">Read more...</a>
              </div>
            </div>
        {% endfor %}
    </div>
</div>
<h3>Post title after: {{post.title}}</h3>
```

`Post title before` does not equal `Post title after`.

It is not a big deal for me to use other names for variable, but for me, it is unexpected behavior. 

Thank you for your attention!

**Comment by sebastienros** [comment]
Simpler example showing how it should behave:

```
{% assign name = 'seb' %}
{% assign c = 'x' %}
{% for c in name %}{{ c }}{% assign c = 'y' %}{{ c }}{% endfor %}
{{ c }}
```

What would you expect?

```
sseebb
y
```

Which would mean that `c` can be assigned, but `c` is the value from the loop when it's read. Almost like we need a custom scope that is readonly and that only contains the for loop variable.

**Comment by sebastienros** [comment]
The ruby implementation returns 

```
sebseb
y
```
