### ISSUE TITLE
Is it possible to override the writeto behaviour of default tag

### ISSUE THREAD

**Issue by Antonf26** [sebastienros/fluid#202]
I understand overriding using custom tags but we have a use case where we'd like to specify the output for the default tags like {{ object }}. Is there a way of doing this?

**Comment by sebastienros** [comment]
You could use an Encoder. It can be passed as an argument when rendering a template. Chances are that you want to HTML encode the results ;) This is documented in the main README https://github.com/sebastienros/fluid#encoding
