### ISSUE TITLE
Capture HTML issue

### ISSUE THREAD

**Issue by nathanaskinner** [sebastienros/fluid#203]
It looks like the capture tag is encoding HTML? 

for example, 

```
{% capture hero_image %}
    {% include 'compositions/hero/image-overlay', hero_image: '/images/prototypes/services/couple-small.jpg', hero_image_large: '/images/prototypes/services/couple-large-crop.jpg', hero_heading: 'The region’s most comprehensive cardiovascular care.' %}
{% endcapture %}

{% include 'components/band/index', band_wave_end: true, band_wave_class: 'Band-wave--in', band_content: hero_image %}
```

renders this: 

![Screen Shot 2020-07-21 at 6 17 05 PM](https://user-images.githubusercontent.com/42789919/88112707-6c35bb80-cb7e-11ea-985b-7b37b1ed376d.png)

I do not believe this is the usual behavior for capture. Am I mistaken?

**Comment by sebastienros** [comment]
Not sure yet. In `components/band/index` when you are rendering `band_content`, are you actually using `| raw`?
To me it looks like `band_content` should contain html, so you don't want this to be encoded, hence using `| raw`.

**Comment by nathanaskinner** [comment]
I see, so any nested or includes with captures need Raw to render the HTML? This is not the behavior I am use to in the static site generator we used to build our pattern library (11ty).

**Comment by nathanaskinner** [comment]
I see. adding `{% assign hero_image = hero_image | raw %}` fixed it. 

![Screen Shot 2020-07-21 at 7 08 10 PM](https://user-images.githubusercontent.com/42789919/88115982-89ba5380-cb85-11ea-8130-47d5a1f6d350.png)

**Comment by sebastienros** [comment]
Forget about the include, and look at the `band_content` argument. You are passing a string. How does liquid know that it's some HTML? From the point of view of the engine, it's just a string. Now by default all `{% %}` usage is encoded, for security reasons. If you know that the variable is already encoded, then you need to use raw.

I assume that "other" engine would not encode by default. You can decide to disable this. Or use `raw` to opt out in specific cases instead.

**Comment by sebastienros** [comment]
So yes, using `{% assign hero_image = hero_image | raw %}` will convert the variable to the `IHtmlString` equivalent in aspnet. And it won't be encoded again.

So looking back at the `capture` tag, we might want to have this behavior by default, that a `capture` is already encoded. This might be an issue actually. Because it's already rendered using the default encoder. We should not be able to re-encode it, unless on purpose (there is a filter for that too).

**Comment by sebastienros** [comment]
Are you actually using the Fluid MVC engine? I know this one is setting a default encoding. Otherwise there is no default encoding.

**Comment by sebastienros** [comment]
I have fixed the bug in a PR. You won't need the `raw` filter if the variable is coming from a capture tag.
