### ISSUE TITLE
How to use uppercase, formatted Text and padding

### ISSUE THREAD

**Issue by iozcelik** [sebastienros/fluid#210]
I am new at template engine and use fluid.
I want to create a string list like formatted text.

User string list: a12, a14g, hu9jy, s6

Expected result: 00-A12, 0A-14G, HU-8JY, 00-0S6

Is there any way to making it with fluid? 
Do I need create some custom tag? And also if I create custom tags, can I use them at once?

**Comment by hishamco** [comment]
There're some built-in custom filters [here](https://github.com/sebastienros/fluid#custom-filters), but what you asking for need to create your own filter, please check the [link](https://github.com/sebastienros/fluid#customizing-tags-and-blocks)

**Comment by iozcelik** [comment]
What is filter working order? How many filter could be use in a bracket { } ?

**Comment by hishamco** [comment]
> What is filter working order?

I didn't understand what you mean?!!

> How many filter could be use in a bracket { } ?

Frankly I'm not sure, but I expect you could supply many filters

**Comment by iozcelik** [comment]
Ok I get all answers. Thanks. The filter what I need, but I dont know.

**Comment by hishamco** [comment]
> but I dont know

You don't know what?!! Please let me know if you need help in writing such filter

**Comment by iozcelik** [comment]
@hishamco I handle it, thanks. I add padLeft custom filter and works well. I do not know what I need. When you said filter, I figured out how to solve problem.

**Comment by hishamco** [comment]
Good luck
