### ISSUE TITLE
Question: Why still Fluid has beta tag?

### ISSUE THREAD

**Issue by iozcelik** [sebastienros/fluid#212]
I am testing fluid for my project 2 days. It is better than others, also easy than. I create multiple custom filters and blocks.

However, it has still beta tag at nuget package. If we don't check include prerelease checkbox at Visual studio, package manager doesn't find the package.

Fluid is looking good and production ready. Why still beta? Is there something at roadmap?

**Comment by sebastienros** [comment]
v1 released, v2 started with beta tag, but I would recommend to use v2.
