### ISSUE TITLE
Are color filters included in this implementation of Fluid?

### ISSUE THREAD

**Issue by jagbarcelo** [sebastienros/fluid#214]
I'm using OrchardCore, which it seems uses this implementation of the Fluid engine and I've been redirected here to ask (from [here](/OrchardCMS/OrchardCore/issues/7352)).

I'm trying to convert an RGB hex color value into another one with transparency. For that, according to [Shopify color-filters](https://shopify.dev/docs/themes/liquid/reference/filters/color-filters) there is one just for what I need (an example from them):
`{{ '#7ab55c' | color_modify: 'alpha', 0.85 }}`
However, when I try to use it (in OrchardCore), it does not work. It simply outputs the original hex RGB value without any transparency (solid).

The output, according to the former example should be:
`rgba(122, 181, 92, 0.85)`
but the result I get is `'#7ab55c'` as if no transformation has been made.

**Comment by jagbarcelo** [comment]
Thanks @hishamco for your changes but I do not see any reference to generate an output including `rgba`, being the trailing `a` for `alpha` (transparency). Your changes here:
https://github.com/sebastienros/fluid/blob/ff7c73053457f69668ce120f29d1a3c003f638d4/Fluid/Filters/ColorFilters.cs#L25 produce an `rgb(...)` output  not an `rgba(...)` output.

Even the unit tests are for just `rgb(...)`, and not `rgba(...)` cases: https://github.com/sebastienros/fluid/blob/ff7c73053457f69668ce120f29d1a3c003f638d4/Fluid.Tests/ColorFiltersTests.cs#L16

So I think the issue still unresolved since there is no `color_modify` filter among any of the filters defined under /fluid/Filters/*. I'd say, however, it is now partially solved.

**Comment by hishamco** [comment]
I'm working on other filters, no worry, they are on the way ;)

**Comment by hishamco** [comment]
BTW regarding the transperancy aka Alpa isn't not listed in the filter but we could easily add it if it's required, but I'm trying to implement what it's in Liquid

**Comment by jagbarcelo** [comment]
https://shopify.dev/docs/themes/liquid/reference/filters/color-filters#color_modify

**Comment by hishamco** [comment]
Seems there are two filters `rgb` & `rgba` but the last one not listed in the left menu

**Comment by hishamco** [comment]
@jagbarcelo almost of the color filters have been implemented and some waiting for approval

**Comment by sebastienros** [comment]
Is this done ?

**Comment by hishamco** [comment]
I think 95-97%, I think there's two remaining filters which I hold for awhile .. hope to finalise them in the upcoming few days, but we can close it as Fluid now supports most and important color filters

**Comment by hishamco** [comment]
I will close this one, while almost the filters are implemented
