### ISSUE TITLE
Colaborators

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#215]
I invited @lahma and @hishamco to become collaborators. They have contributed the most, and an healthy oss project needs more than one maintainer in case something happens to the owner.

**Comment by hishamco** [comment]
It's my pleasure to make this project healthy

**Comment by lahma** [comment]
One suggestion that is not Fluid specific. Might be a good idea to create some organizations to NuGet too and allow multiple persons to maintain packages. I have created one for Quartz ( https://www.nuget.org/profiles/Quartz.NET ) which holds backup person if I get hit by a car or something. This organization also allowed me to reserve Quartz prefix from NuGet by contacting NuGet support.
