### ISSUE TITLE
Data from different API calls in layout file

### ISSUE THREAD

**Issue by nathanaskinner** [sebastienros/fluid#216]
I am a front end developer. I am working on a layout file. We are using a headless cms for our data. The header data, footer data, and page data come from different sections of the cms, and require three different calls to get. With Fluid, what would be best approach to implement something like below, where I include a header and footer with their own data from the cms? 

 renderbody is working as expected and rendering the data from the page. 

How can I explain this to our .NET developer(s) to implement? Thanks.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% rendersection meta %}
    <link rel='stylesheet' href='/css/bundle.min.css' />
    <link rel='stylesheet' href='/css/site.css' />
    
</head>
<body>
    {% include 'SiteHeader', data: header_api %}
    <main role="main" class="container">
      {% renderbody %} //page_api
    </main>
    {% include 'SiteFooter', data: footer_api %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="/js/bundle.min.js"></script>
    <script src="/js/site.js"></script>
</body>
</html>
```

**Comment by sebastienros** [comment]
How is this template rendered? 
- Are you generating a static site that needs to connect to the cms to extract the content?  
- Are you generating this page dynamically from another server-side project in .NET that connects to the headless API?

Can you describe how your extract the data from the cms? authentication, rest, graphql, ...
Is there a .NET SDK that the cms provides to get the content in an easier way?

Even without more details I can say that some custom helpers will be required to connect to the cms and grab the data, probably doing some http requests (auth might be in the way though). But ideally all the data should be available when the template is called, so you don't have to "query" for more data. But don't worry Fluid was made in a way that it can handle it. Once I have more details I can provide an more complete answer.
