### ISSUE TITLE
Question - Mixing Razor Pages and Fluid

### ISSUE THREAD

**Issue by espray** [sebastienros/fluid#23]
Can Razor Pages and Fluid be use I'm the same application?

Example
I have a SaaS multi tenant application. The general pages I want to use Razor Pages to have full controll of the html. But, tenant specific pages I want tenants to controll their layout using Fluid.

**Comment by sebastienros** [comment]
Yes you can. We also do similar things in https://OrchardCMS/OrchradCore

**Comment by espray** [comment]
That url 404. Below is the correct url.
https://github.com/OrchardCMS/OrchardCore

Can you give me a high level overview on how mixing Page Views and Fluid?

SaaS app I am working in is more like Shopify, Lodgify and Azure Api Management. No dynamic pages(tenants can not add their own pages), all pages have pre defined routes. But, I want to allow the tenant modify the .liquid and render that on the page

What I am thinking is defining all the pages. Then use a TagHelper to render the Tenant specific .liquid
 
Lodgify: https://www.lodgify.com/docs/Templates
Azure Api Management: https://docs.microsoft.com/en-us/azure/api-management/api-management-developer-portal-templates-reference

**Comment by sebastienros** [comment]
You know that Api Managment is using Orchard? ;)

This is exactly what we do in Orchard Core (yes I have to insist). We use Liquid is liquid files for views, but also from the Admin for users to edit templates. Look at the OrchardCore.Liquid.Abstractions and implementation.  Or just install Orchard Core, use the Agency recipe, and open the templates section.

**Comment by espray** [comment]
I did not know that about Api Management.
Is Api Management open source? Would love to see how they use Orchard.

I will check out the Abstractions Implementation



Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by sebastienros** [comment]
It's not open source. They use it because their offer is also to build a public facing website, so they can just reuse the CMS features, and then add Modules for their specific offer. They are using Dotliquid right now for their templates, but they will be looking at Fluid now as it's faster.

**Comment by espray** [comment]
So I only want my customers to use a .liquid template for only a single page. Rest of my app I want to stick with Razor Pages. Any example of using fluid to render a single page route?

**Comment by espray** [comment]
Nevermind found what i was looking for

**Comment by hishamco** [comment]
@sebastienros this need to be closed
