### ISSUE TITLE
{% include %} is deprecated and replaced by {% render %}

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#235]
https://shopify.dev/docs/themes/liquid/reference/tags/deprecated-tags
https://github.com/Shopify/liquid/blob/5532df880fda804c838a35324ba7b8ea6cf0e34f/test/integration/tags/render_tag_test.rb

Might also require the {% section %} tag

**Comment by sebastienros** [comment]
Sections might actually be part of a broader theme extension, like the mvc project:
https://shopify.dev/docs/themes/sections

**Comment by hishamco** [comment]
We could annotate the `include` tag as obsolete then removed in the upcoming major release. Also the code should execute the `render` to make sure nothing is broken

**Comment by sebastienros** [comment]
I don't think we have to. It's not an issue to keep it, like shopify is doing, and just add a new one.

**Comment by hishamco** [comment]
From Shopify docs

> When a snippet is rendered using the render tag, the deprecated include tag may not be used inside of the snippet.

**Comment by sebastienros** [comment]
The include tag is deprecated because it can access the parent's variables and change them. However in fluid this is not possible since it is run within a scope. This is actually what the render tag should do, so implementing the render might mean to also "fix" the include tag by introducing this flaw.

The render tag also need the `for x in y` and `with x as y` statements. The `as` keyword should just overwrite the current `_identifier` property (defaulting to the name of the template). The `for` loop should reuse the `ForStatement` internally since it needs to provide the `forloop` variable.

**Comment by srid** [comment]
IIUC, then the pending tasks are:

- Make `render` support the for/with syntax.
- Recommend `render` (instead of `include`; as that's deprecated) in README and docs

?

**Comment by MrUpsideDown** [comment]
As suggested by @sebastienros, it would be very helpful to also "fix" the include tag in fluid to reproduce the current Liquid behavior. We are currently migrating to fluid, and I'm concerned that this unexpected change in the scoping rules for include could break our existing Liquid-compatible templates.

**Comment by sebastienros** [comment]
`input` tag was actually behaving as expecting wrt parent template variables access.
`render` tag is equivalent to `input` tag but only grants access to the global scope variables defined in `options.Scope`.
Only the `with` argument was implemented. Not it also support `for`, `for/as` and `with/as`
