### ISSUE TITLE
Support .NET Standard 1.3

### ISSUE THREAD

**Issue by RSuter** [sebastienros/fluid#24]
Context: I'm evaluating different template engines for [NSwag](http://nswag.org) to generate C#/TypeScript code. I need a template engine which can load templates at runtime (this is why I want to replace the currently used T4 templates) and should work almost everywhere (full .NET 4.5.1+, .NET Core 1.0+). I wanted to use DotLiquid but @rynowak pointed me to this library - it looks much better performance wise and the white space handling seems also better for my needs. 

My only problem is that it requires .NET Standard 1.6 - is it possible to change it to target .NET Standard 1.3? I checked some dependencies but couldn't find one which does not support it. Is there a reason why it targets .NET Standard 1.6?

**Comment by sebastienros** [comment]
Probably by convenience when I created the project. I'd suggest you try to downgrade it from the source code, at least the main library, and if that works (which should be the case) then submit a PR.

Worst case some specific dependency needs a higher version and we can still multi-target.

**Comment by hishamco** [comment]
FYI `Irony.Core 1.0.7` is not compatible with netstandard 1.3

**Comment by RSuter** [comment]
Where is irony hosted? Still on codeplex?

**Comment by hishamco** [comment]
It's in NuGet https://www.nuget.org/packages/Irony.Core/

**Comment by hishamco** [comment]
Sorry you asking for the source, let me check ..

**Comment by hishamco** [comment]
It was on on CodePlex, but seems the source is outdated ..

**Comment by RSuter** [comment]
Yes, I’d have to downgrade this first...

**Comment by sebastienros** [comment]
It's on github, at least the package that I published on nuget is taken from github.

https://github.com/sebastienros/irony

**Comment by RSuter** [comment]
Ah, when I looked into this I thought that you may be "in charge" of this NuGet...

**Comment by RSuter** [comment]
I just tried to downgrade irony to .NET Standard 1.3 - it doesn't work because DynamicMethod is missing in 1.3. I'll now evaluate Microsoft.AspNetCore.Razor (big advantage: intellisense/compile time static analysis). Thanks for your input.

**Comment by rynowak** [comment]
@RSuter 

>  intellisense/compile time static analysis

Sadly we don't really have this right now except for open documents. Also the intellisense you get will reflect MVC's api.

Razor is first and foremost an HTML templating language, and all of the work we are doing is going towards making it better for HTML (not for general-purpose templating). I'm happy to discuss the limitations offline or on aspnet/Razor if you want more info.

**Comment by sebastienros** [comment]
If `DynamicMethod` is the only thing, then let's get rid of that, from what I see it's used only once to create a factory of objects, we can do it without it.

**Comment by sebastienros** [comment]
I replaced this method with the following code:

```
    private DefaultAstNodeCreator CompileDefaultNodeCreator(Type nodeType) {
        return Expression.Lambda<DefaultAstNodeCreator>(Expression.New(nodeType)).Compile();
    }
```

Then changed to target netstandard1.3 and everything just built fine.

**Comment by RSuter** [comment]
@sebastienros sorry I didnt try to change it. Didnt have much time...

@rynowak intellisense or static analysis in general would be extremely desirable, mostly to do safe refactorings... maybe ill stay with fluid and liquid syntax... or do you have any other ideas?

@sebastienros your idea with the js interpreter engine is good but i think it happens too fast to have too much logic in the template with this approach

**Comment by sebastienros** [comment]
Just tried to make a PR and actually there are more changes to do because of reflection. Doable, but not as straight as a simple method to change.

**Comment by rynowak** [comment]
> mostly to do safe refactorings

Razor in VS does not have refactoring. This is on our roadmap but it will be some time before this is possible.

**Comment by RSuter** [comment]
Ok, I see. I think I'll stick with DotLiquid for now - I dont have the time to work on more projects :-). Switching to fluid later (still desirable) should be simple as the syntax is the same (I think the only diff is the white space handling).
