### ISSUE TITLE
Using Parlot

### ISSUE THREAD

**Issue by hishamco** [sebastienros/fluid#242]
Seems a Parlot is shining parser, that have been using in Shortcodes recently, any plan to use in Fluid especially the PERF here is very important for a templating language

I will take some time to check and dig into Parlot, hopefully it's extensible and allow us to expose metadata for exception and others things, coz I remember there was an old issue about geting the error line or column in Irony in Fluid, which has been resolved using hack if I'm not wrong

**Comment by sebastienros** [comment]
I have already started converting the grammar and adding things to Parlot as I progress.
Next there is the SQL grammar in OC if you want to take on the exercise. Should be much simpler than Liquid.
