### ISSUE TITLE
when using custom endblock without startblock, throw NullReferenceException

### ISSUE THREAD

**Issue by cadcad-sat** [sebastienros/fluid#244]
Hi,I found it when I made a custom block.
when using custom endblock tag without startblock, DefaulFluidParser throw NullReferenceException.
I want you to add a process to judge whether '_context.CurrentBlock.Tag' is null.

``` DefaulFluidParser.cs
if (_blocks.TryGetValue(tagName, out ITag customEndBlock))
{
    // Add
    if (_context.CurrentBlock.Tag == null)
    {
        throw new ParseException($"Expected tag '{tagName}' before 'end{tagName}'");
    }
    
    if (_context.CurrentBlock.Tag.Term.Name != tagName)
    {
        throw new ParseException($"Unexpected tag: '{tag.Term.Name}' not matching '{_context.CurrentBlock.Tag.Term.Name}' tag.");
    }
```

**Comment by sebastienros** [comment]
I am currently rewriting the parser. Do you have an example I could try to repro on it? Like what does this tag look like and how it's being used?

**Comment by cadcad-sat** [comment]
1. Create "RepeatBlock" written in readme.md
2. Registe it `FluidViewTemplate.Factory.RegisterBlock<RepeatBlock>("repeat");`
3.  Add to index.liquid
```
{% repeat 1 + 2 %}
Hi!
{% endrepeat %}
{% endrepeat %}
```

Debug
![image](https://user-images.githubusercontent.com/36953431/104263212-7650cb00-54cc-11eb-874c-7890abfdf4de.png)

**Comment by cadcad-sat** [comment]
when adding the condition
![image](https://user-images.githubusercontent.com/36953431/104263625-4d7d0580-54cd-11eb-9935-4e62621963b9.png)

**Comment by hishamco** [comment]
Why there's two end repeat in your snippet? Just remove the last one

**Comment by sebastienros** [comment]
@hishamco the issue is that it should not throw

**Comment by hishamco** [comment]
I'm expected an expection, what's the default behavior it should be Seb? So I can have a look

**Comment by cadcad-sat** [comment]
>I'm expected an expection

I think so, too.
I'm expected ParseException instead of NullReferenceException.

**Comment by hishamco** [comment]
@cadcad-sat could please create a minimal repo to reproduce the issue, or paste your custom tag block here

**Comment by cadcad-sat** [comment]
@hishamco here is the custom tag block.
references : https://github.com/sebastienros/fluid#creating-a-custom-block
```RepeatBlock.cs
using Fluid.Ast;
using Fluid.Tags;
using System.Collections.Generic;
using System.IO;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace Fluid.MvcSample
{
    public class RepeatBlock : ExpressionBlock
    {
        public override async ValueTask<Completion> WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context, Expression expression, List<Statement> statements)
        {
            var value = (await expression.EvaluateAsync(context)).ToNumberValue();
            for (var i = 0; i < value; i++)
            {
                await RenderStatementsAsync(writer, encoder, context, statements);
            }

            return Completion.Normal;
        }
    }
}
```

**Comment by sebastienros** [comment]
I added a unit test in the new parser, and it's detected correctly:

```
        [Fact]
        public void CustomBlockShouldReturnErrorMessage()
        {
            var parser = new CustomParser();

            parser.RegisterEmptyBlock("hello", (s, w, e, c) =>
            {
                w.Write("Hello World");
                return s.RenderBlockAsync(w, e, c);
            });

            parser.TryParse("{% hello %} hi {%- endhello %} {% endhello %}", out var template, out var error);

            Assert.Null(template);
            Assert.Contains("Unexpected tag 'endhello'", error);
        }
```

**Comment by cadcad-sat** [comment]
@SebastianStehle 
Thanks a lot.
Looking forward to the next release.

**Comment by hishamco** [comment]
I reopen this, you can closed once the PR is pushed, it is good for tracking
