### ISSUE TITLE
The type or namespace name 'FluidParser' could not be found

### ISSUE THREAD

**Issue by alex-jitbit** [sebastienros/fluid#252]
Copy-pasted the code from your Readme to a brand new console app (.NET Framework 4.7.2) - got the error.

**Comment by sebastienros** [comment]
Have you tried the 2.0.0-beta nuget package ? It corresponds to that version

**Comment by alex-jitbit** [comment]
Of course not

* Visual Studio does not show you pre-release versions by default
* The nuget badge in readme points to 1.0.0

**Comment by sebastienros** [comment]
I added a note at top of the readme to make it clear. Thanks.
