### ISSUE TITLE
Properties at second level

### ISSUE THREAD

**Issue by jirisykora83** [sebastienros/fluid#253]
Hello,

It is expected that this example do not return `Hello: ABC`? Or i miss something?

```
var model = new Model
{
  Property1 = new PropertyDeep1
  {
	  Property2 = new PropertyDeep2
	  {
		  Text = "ABC"
	  },
  },
};
var source = "Hello: {{ PropertyDeep1.PropertyDeep2.Text }}";

if (FluidTemplate.TryParse(source, out var template, out var error))
{
  var context = new TemplateContext(model, true);
  Console.WriteLine(template.Render(context));
}
```

**Comment by sebastienros** [comment]
Yes, by design, no property is accessible if not registered. In this case do that:
```
TemplateContext.GlobalMemberAccessStrategy.Register<PropertyDeep1>();
TemplateContext.GlobalMemberAccessStrategy.Register<PropertyDeep2>();
```

**Comment by jirisykora83** [comment]
i try it but still get same result. `Hello: `

```
var model = new Model
{
	Property1 = new PropertyDeep1
	{
		Property2 = new PropertyDeep2
		{
			Text = "ABC"
		},
	},
};
var source = "Hello: {{ PropertyDeep1.PropertyDeep2.Text }}";

TemplateContext.GlobalMemberAccessStrategy.Register<PropertyDeep1>();
TemplateContext.GlobalMemberAccessStrategy.Register<PropertyDeep2>();
if (FluidTemplate.TryParse(source, out var template, out var error))
{
	var context = new TemplateContext(model, true);
	Console.WriteLine(template.Render(context));
}
```

**Comment by sebastienros** [comment]
Did you do the same thing for `Model`?

**Comment by sebastienros** [comment]
Well, not necessary since you passed it as a model ...

**Comment by sebastienros** [comment]
Your template is wrong, should be :`"Hello: {{ Property1.PropertyDeep1.PropertyDeep2.Text }}";`

**Comment by lahma** [comment]
I guess `Hello: {{ Property1.Property2.Text };` ?

**Comment by jirisykora83** [comment]
> Your template is wrong, should be :`"Hello: {{ Property1.PropertyDeep1.PropertyDeep2.Text }}";`

Ohh sorry now i feel stupid.  Actually it should be in this example `var source = "Hello: {{ Property1.Property2.Text }}";`. Naming things thing is hard :) Next time I need to choose better naming for example. 

For future me it also can be register at context level

```
context.MemberAccessStrategy.Register<PropertyDeep1>();
context.MemberAccessStrategy.Register<PropertyDeep2>();
```

Thank you very much for fast help!

**Comment by clement911** [comment]
I came across the same issue so it might be worth adding docs.
How can we achieve the same thing with anonymous type models? It might be nice if we could instruct the `TemplateContext` to register the model properties recursively. I think using anonymous with nested properties is a pretty common pattern.

**Comment by lahma** [comment]
Do you need the security feature at all if you allow all? i.e. would it just be easier for you to disable the registration checks? If you control model and templates, you might not need the checks.

**Comment by sebastienros** [comment]
@clement911 you can already do the same thing like this: `Register(new { foo: "Bar"}.GetType())`

But talking about "common pattern" a common one is to pass the model like this: `new TemplateContext(model)` and this registers the type automatically. So if it's an anonymous type it will also work nicely.

**Comment by clement911** [comment]
Thanks but how do you register a nested property on an anonymous type?
