### ISSUE TITLE
"Error: Invalid 'if' tag" when have a filter

### ISSUE THREAD

**Issue by Soar360** [sebastienros/fluid#254]
I have written some code:

```csharp
	var parser = new FluidParser();
	
	var model = new { Firstname = "Bill", Lastname = "Gates" };
	var source = @"
	Hello {{ Firstname }} {{ Lastname }} Size:{{ Lastname | size }}
	{% if Lastname | size > 5 %}
	...
	{% endif %}
	";
	
	if (parser.TryParse(source, out var template, out var error))
	{
		var context = new TemplateContext(model);
	
		Console.WriteLine(template.Render(context));
	}
	else
	{
		Console.WriteLine($"Error: {error}");
	}
```
This produces an error:
```
Error: Invalid 'if' tag at (3:7)
```
This error does not appear in version 1.0.

**Comment by sebastienros** [comment]
This is not a valid `{% if %}` tag. It was wrongly supported in v1. Here you need to define an intermedia variable that gets `Lastname | size` and then compare it in the if tag. Filters are not allowed, only properties, values and boolean operators.

**Comment by Soar360** [comment]
I've seen code on the liquid language introduction site that uses filters in if statements, which seems to be a very common operation.

```liquid
{%- assign username = "John G. Chalmers-Smith" -%}
{%- if username and username.size > 10 -%}
  Wow, {{ username }}, you have a long name!
{%- else -%}
  Hello there!
{%- endif -%}
```

https://shopify.github.io/liquid/basics/whitespace/

**Comment by sebastienros** [comment]
I don't see any filter in this example, just logical operators, and if you try it you'll see it works too in Fluid.

I double checked in Shopify source code and other liquid engines.

**Comment by Soar360** [comment]
Sorry, it' my fail.

The following code works fine:

```csharp
	var parser = new FluidParser();

	var model = new { Firstname = "Bill", Lastname = "Gates" };
	var source = @"Hello {{ Firstname }} {{ Lastname }} {% if Lastname.size > 3 -%}...{%- endif %}";

	if (parser.TryParse(source, out var template, out var error))
	{
		var context = new TemplateContext(model);

		Console.WriteLine(template.Render(context));
	}
	else
	{
		Console.WriteLine($"Error: {error}");
	}
```
