### ISSUE TITLE
v2.0: Custom parsers implementation

### ISSUE THREAD

**Issue by agross** [sebastienros/fluid#259]
I'm currently using the 2.0 prerelease and try to implement custom parsers as per the [readme](https://github.com/sebastienros/fluid#custom-parsers):

> ... the methods `RegisterParserBlock` and `RegisterParserTag` accept any custom parser construct. These can be the standard ones defined in the `FluidParser` class, like `Primary`

The problem is that `FluidParser.Primary` is protected and I wanted to set up the parser extensions using `FluidViewEngineOptions` (which contains an action to register stuff in the default `Parser`).

How is it supposed to be done?

N.B.: I find it very confusing that the readme in the repo refers to v2.0 whereas the latest release is 1.x.

**Comment by sebastienros** [comment]
There is a note at the top of the readme that explains the readme is for 2.0. I updated it with a link to the 1.0 version.

Thanks for reporting all these issues, and I had no idea "unless" could handle "else". It's not even mentioned in the main documentation site, but I found it worked in liquidjs.com, so I added it.

**Comment by agross** [comment]
Thank you for the quick fixes to the issues I reported.

Off the top of your head, can you tell me if it would be possible to implement a custom block for something like this:

```liquid
{% partial '_foo', bar: 42, baz: 'abc' %}
some content
{% endpartial %}
```

This is similar to `include`, but instead of providing `some content` as an assignment, I need to pass it like as a child (that in turn could contain other liquid code).

The reason for this is that I want to have a higher level of abstraction and proper nesting when building my template:

```liquid
{% partial '_row', class: 'header' %}
  {% partial '_cell' %}
    some value
  {% endpartial %}    

  {% partial '_important-cell' %}
    some value
  {% endpartial %}    
{% endpartial %}
```

Doing the same with `include` only would be a nightmare and hard to understand. I don't know if you ever worked with [Spark](https://github.com/SparkViewEngine/spark), but it supported that.

**Comment by sebastienros** [comment]
You can use `ArgumentsList`  and access the first argument by position.
So a RegisterParserBlog("partial", ArgumentList, ...)

**Comment by sebastienros** [comment]
Would this issue solve your problem? https://github.com/sebastienros/fluid/issues/235

**Comment by agross** [comment]
I do not think it'll solve my issues as `render` does not support child content (like it is the case with `include`).
