### ISSUE TITLE
Liquid within comment executes

### ISSUE THREAD

**Issue by jeremycook** [sebastienros/fluid#26]
Should Liquid within a comment still execute or should a comment prevent execution? For Shopify's implementation, code will not execute:

> comment
> Allows you to leave un-rendered code inside a Liquid template. Any text within the opening and closing comment blocks will not be output, and any Liquid code within will not be executed. https://help.shopify.com/themes/liquid/tags/theme-tags#comment

Fluid example:

    {% comment %}
    I don't get printed but this code is executed. That is, `programs` is assigned a value, and all that.
    {% assign programs = '[ {"id": 1, "iconUrl": "http://lorempixel.com/output/animals-q-c-640-480-3.jpg", "title": "One" } ]' | parse %}
    {% endcomment %}

**Comment by sebastienros** [comment]
If it's executing then I assume it's a bug.

**Comment by hishamco** [comment]
I can verify that `Include` tag is the only tag I ever seen that been executed inside the comment statement, I'm working on this now ..
