### ISSUE TITLE
Expose context methods?

### ISSUE THREAD

**Issue by geekox86** [sebastienros/fluid#268]
Greetings and thanks for this clean library.
Is there a way to expose the non-static methods of a registered type in the template context?

I am aware of the safety feature of the library for not exposing such methods, but I am managing the templates internally and they will not be used by the end-users.

**Comment by sebastienros** [comment]
There is no support in the liquid syntax to invoke methods. The only way would be to bind a property to a custom callback that will invoke the method. Or create a filter that will invoke it.

Example:

```
public class Foo
{
  void MyMethod(string arg1) {}
}
```

```
{{ value | mymethod arg1: "x" }}
```

And you can create a custom filter that will invoke MyMethod on `value` with the correct argument.
You could even create a filter that will invoke anything on anything:
` {{ source | invoke: "MyMethod", arg1: "arg" }}`
