### ISSUE TITLE
include tag behavior

### ISSUE THREAD

**Issue by jeremycook** [sebastienros/fluid#28]
The `include` tag only writes the contents of the included file, but does not parse the file. This varies from [Shopify's include tag implementation](http://www.rubydoc.info/github/Shopify/liquid/Liquid/Include). The `with` and `for` syntax are also not supported at this time.

At a minimum should Fluid render the contents of the included file using the existing context?

**Comment by sebastienros** [comment]
All should be handled "at a minimum". If you feel like you could help, then please do so.

**Comment by jeremycook** [comment]
@sebastienros The variables I have access to are `Expression path` from the `public IncludeStatement(Expression path)` constructor, and `TextWriter writer`, `TextEncoder encoder`, `TemplateContext context` via `WriteToAsync` method. It seems to me that I need an `IFluidParser` and a `IFluidTemplate` when `WriteToAsync` is called so that I can render the contents of the include file at that time. Passing these through the constructor seems wrong. So the other option is to pass it as part of the call to `WriteToAsync`.

How should I go about making an `IFluidParser` and a `IFluidTemplate` available to the `WriteToAsync` method? Or would you recommend a different approach?

**Comment by sebastienros** [comment]
We might just be able to provide the parser in the ambient value property, globally, so any filter can use it if necessary.
