### ISSUE TITLE
Exception: Invalid 'cycle' tag when using numeric values.

### ISSUE THREAD

**Issue by bryan07** [sebastienros/fluid#284]
When using numeric values in cycle tag there is an exception, that is different from Shopify where you can use numeric values.
```
{% for i in (1..100) limit:9%}
    {% cycle 1, 2 ,3 %} <br />
{% endfor  %}
```

**Comment by hishamco** [comment]
Which `cycle` tag do you mean?

**Comment by bryan07** [comment]
Updated example

**Comment by hishamco** [comment]
I did't see the `cycle` tag in the source, is this a custom tag?

**Comment by bryan07** [comment]
No it's a Fluid tag source here [https://github.com/sebastienros/fluid/blob/main/Fluid/Ast/CycleStatement.cs](url)

**Comment by hishamco** [comment]
`CycleStatement` I wasn't aware about it ;) I will try to test your example and checkout the shopify one, If you have a direct link to it's usage, please shoot it to me

**Comment by bryan07** [comment]
Documentation here  [https://shopify.dev/docs/themes/liquid/reference/tags/iteration-tags](url) but it's not current as actual templates are using both numeric and text values.

**Comment by sebastienros** [comment]
Created a PR. The issue was in the parser that was looking explicitly for string instead of any "Primary" expression, like numbers, members, ...

**Comment by hishamco** [comment]
Seems Seb was made a quick fix of this ;)

Thanks
