### ISSUE TITLE
F#: JSON models doesn't seem to work

### ISSUE THREAD

**Issue by srid** [sebastienros/fluid#290]
I followed the [C# example in the README](https://github.com/sebastienros/fluid#using-jsonnet-object-in-models) as closely as possible, but it doesn't seem to work in F#. Here's the code:

```fsharp
    let demo = 
        // Build opts
        let opts = TemplateOptions()
        let lookup (src: JObject) (name: string) = src.GetValue(name)
        let getIt : System.Func<JObject, string, JToken> = 
            System.Func<JObject, string, JToken>(lookup)
        opts.MemberAccessStrategy.Register<JObject, JToken>(getIt)
        opts.ValueConverters.Add(fun x -> 
            match x with 
            | :? JObject as o ->
                // ObjectValue(x).ToObjectValue()
                x
            | _ -> null)
        opts.ValueConverters.Add(fun x -> 
            match x with 
            | :? JValue as v ->
                v.Value
            | _ -> null)
 
        let json = "{\"Name\": \"Srid\"}"
        let template = "{{ x.Name }}"

        let parser = FluidParser()
        let success, tmpl = parser.TryParse(template)
        match success with 
        | false -> printfn "fail"
        | true -> 
            let ctx = TemplateContext(opts)
            let value = JsonSerializer.Deserialize<JsonElement>(json)
            let ctx' = ctx.SetValue("x", value)
            let out = tmpl.Render(ctx')
            printfn $"{out}"
        printfn "Done."
        0
```

I can't use `ObjectValue(x)` because it doesn't type check (the return value is expected to be object, which is `x` itself). Any idea what I might be doing wrong?

**Comment by srid** [comment]
As an aside, I'd rather use the new `System.Text.Json` - but the README uses Newtonsoft library, so that's what I chose to begin with.

**Comment by sebastienros** [comment]
I updated the sample in the README and added a unit test to ensure the sample works.

Please check this link https://github.com/sebastienros/fluid#using-jsonnet-object-in-models

**Comment by sebastienros** [comment]
Note that you could try to use System.Text.Json, unfortunately it doesn't provide an abstract representation of a json document like JSON.NET does (aka JObject, JValue, ...).

What you can do however to deserialize a json document to your own object model, and then it will work.

**Comment by srid** [comment]
I adapted your changes to README, and now use:

```fsharp
let value = JsonSerializer.Deserialize<JObject>(json)
let ctx = TemplateContext(value, opts)
let out = tmpl.Render(ctx)
```

Now I get an exception from `Render`:

```
Unhandled exception. System.TypeInitializationException: The type initializer for '<StartupCode$Feather-Build>.$Library' threw an exception.
 ---> System.Text.Json.JsonException: The JSON value could not be converted to Newtonsoft.Json.Linq.JToken. Path: $.Name | LineNumber: 0 | BytePositionInLine: 15.
```

Is my `ValueConverters` addition correct? The C# code does this:

```csharp
x => x is JObject o ? new ObjectValue(o) : null
```

The equivalent function in F# would be:

```fsharp
fun x -> 
            match x with 
            | :? JObject as o ->
                ObjectValue(x)
            | _ -> null)
```

But this throws compile error:

```
C:\Users\srid\Projects\Feather\src\Feather.Build\Library.fs(23,17): error FS0001: This expression was expected to have type↔    'obj'    ↔but here has type↔    'ObjectValue' [C:\Users\srid\Projects\Feather\src\Feather.Build\Feather.Build.fsproj]
```

I mean the compiler is making sense. ValueConverter expects a function that takes `Object` (`obj` in F#) and returns the same, but your C# returns a *different* type, called `ObjectValue`. How does that even work? Your [test](https://github.com/sebastienros/fluid/commit/06b9be14bd42f2a3dc8a1613726328b2677ecf56#diff-0bcea0bf6880c4b82b40cb2e504a1b9c741eaf7aa151a824545575dc560d5fbdR139) indicates that it does in fact work, but I don't understand how this is possible.

**Comment by srid** [comment]
Ah, if I had to use `JObject.Parse` and now it works!
