### ISSUE TITLE
sections feature not working in master

### ISSUE THREAD

**Issue by srid** [sebastienros/fluid#294]
To reproduce,
- Clone https://github.com/srid/Feather/commit/ae672f126f14e6f9c214a6553088d1325cee45da
- `dotnet run -p .\src\Feather.CLI\ -- -w -C example`

Specifically I noticed a couple of issues:

1. *section* feature stopped working. Notice that the use of `{% section title %} ...` in index.liquid has no effect, as in it doesn't populate the `{% rendersection title %}` in _layout.liquid.
2. Inner attributes cannot be accessed using dot accessor. `{{ Extra.More }}` in index.liquid returns empty string; yet `{{ Extra }}` displays `{ More = &quot;more..!&quot; }` (I've disabled the JSON patching mentioned in README for clean slate).

The code that actually uses the library is here: https://github.com/srid/Feather/blob/ae672f126f14e6f9c214a6553088d1325cee45da/src/Feather.Build/Library.fs#L46-L67

**Comment by srid** [comment]
Oops, I hadn't seen the comment here: https://github.com/sebastienros/fluid/pull/292#issuecomment-809737571

Once I used `vopts.TemplateOptions.MemberAccessStrategy <- UnsafeMemberAccessStrategy.Instance` - it resolves issue 2 - but the section bug remains. Let me look further at `MapActionViewEngine` ...

**Comment by sebastienros** [comment]
`UnsafeMemberAccessStrategy.Instance` will allow any property to be accessed. I believe that is safe in your context. But Liquid's intent it to only allow specific properties explicitely. This is documented on the main readme if you want details.

Can you share your full templates? I might be able to spot the issue. Because it works in my sample.

**Comment by srid** [comment]
Sure,

- Code using the library: https://github.com/srid/Feather/blob/c357e8bccc1f07be191cd6715d3682615efc70b3/src/Feather.Build/Library.fs#L17-L40
- Templates: 
    - `_layout.liquid`: https://github.com/srid/Feather/blob/c357e8bccc1f07be191cd6715d3682615efc70b3/example/templates/_layout.liquid
    - `index.liquid`: https://github.com/srid/Feather/blob/c357e8bccc1f07be191cd6715d3682615efc70b3/example/templates/index.liquid

**Comment by sebastienros** [comment]
You are missing the % in endsection

**Comment by srid** [comment]
Ah.

But shouldn't that lead to those unparseable section tags showing up in HTML source? Or is fluid somehow consuming and discarding them?

**Comment by sebastienros** [comment]
I believe so. I will file an issue to report such cases. Wonder if this is because it got the end of the document.
