### ISSUE TITLE
Tags should report an error when not closed

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#298]
`{% if true %} {{ }` `EOF` won't report any error

**Comment by dafergu2** [comment]
Here are a few other permutations of this issue:

`{% assign meh = "blah" | append "bleh" %}` will cause a template to stop rendering content.  Fixing `append` to `append:` fixes it.

`{% script name: "vuejs" at: "Foot" %}` exhibits the same behavior due to the missing comma after `"vuejs"`.

**Comment by jptissot** [comment]
`{% assing hello = "world" %}`

This also renders a blank page. Is it possible to have the lines where the issue occurs to help us debug the liquid errors ?

**Comment by pentarex** [comment]
{% assign meh = "blah" | append "bleh" %} 
still stops rendering. Adding ":" after append fixes it. Not sure by design should not fail, but at least it should not stop render.
