### ISSUE TITLE
Iteration index with offset

### ISSUE THREAD

**Issue by urbanit** [sebastienros/fluid#299]
In a for loop like
```
<!-- if array = [1,2,3,4,5,6] -->
{% for item in array offset:2 %}
  {{ item }}
{% endfor %}
```
the loop index starts from 3. Is this behavior by design?

**Comment by sebastienros** [comment]
Yes

https://shopify.dev/docs/themes/liquid/reference/tags/iteration-tags

**Comment by sebastienros** [comment]
I assume you can think that offset 0 doesn't do anything so it starts on the first one.
