### ISSUE TITLE
Implement include options

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#30]
https://help.shopify.com/themes/liquid/tags/theme-tags#include

**Comment by hishamco** [comment]
We need to add `With` Am I right?

**Comment by hishamco** [comment]
Let me check the link if I can do it ..

**Comment by sebastienros** [comment]
`with`, `for` and the inline variables too

**Comment by sebastienros** [comment]
It can be done in multiple steps

**Comment by hishamco** [comment]
I didn't see the `for` in the link that you provide

**Comment by hishamco** [comment]
May I start to support `With` for inline variable assignment

**Comment by sebastienros** [comment]
the easiest should be the inline variables, but do what you prefer

**Comment by sebastienros** [comment]
I say it's easier because it doesn't require to change the tag and support the `with` keyword. But you have created tags by the past, so you know how it works.

**Comment by hishamco** [comment]
According what I saw the `With` basically equivalent to `assign` during including the template

**Comment by hishamco** [comment]
Yep, now I see the inline variables
```
{% include 'snippet', my_variable: 'apples', my_other_variable: 'oranges' %}
```
I will start on it soon

**Comment by sebastienros** [comment]
Does the current context need to be cloned and get these new variables? Or is it a brand new one?

**Comment by sebastienros** [comment]
> When you include a snippet, the code inside it will have access to the variables within its parent template.

So the solution is to create a new context, and give the current one as the `parent` context. I think I implemented it this way when I created the contexts. If I remember correctly.

**Comment by hishamco** [comment]
Let me check in my way ..

**Comment by sebastienros** [comment]
Ah, `EnterScope` and `LeaveScope`.

**Comment by hishamco** [comment]
@sebastienros could you please review the PRs related to this

**Comment by hishamco** [comment]
@sebastienros this need to be closed
