### ISSUE TITLE
GlobalMemberAccessStrategy in 2.x.x.

### ISSUE THREAD

**Issue by jirisykora83** [sebastienros/fluid#302]
Hello in 1.x.x was `GlobalMemberAccessStrategy` (even mention in docs). But it seems like it not exist new 2.x.x is there any replacement?

**Comment by sebastienros** [comment]
Just updated the documentation, thanks for reporting it.
https://github.com/sebastienros/fluid/blob/main/README.md#allow-listing-object-members

**Comment by sebastienros** [comment]
What's your feedback on this new version, does it feel faster at least?

**Comment by jirisykora83** [comment]
I don't have chance to try it yet (also our use case is not performance critical). But i know this lib is fast even in 1.x.x. and base on benchmark it seems crazy fast now 👍
