### ISSUE TITLE
Add another way to encode variables

### ISSUE THREAD

**Issue by thomasmalloch** [sebastienros/fluid#312]
Right now IFluidTemplate.Render allows you to pass in a TextEncoder object to be used to encode values however you'd like, but there should be another option that uses a callback or something similar to encode strings however you like.

**Comment by sebastienros** [comment]
Can you explain with more details or explain what can't be done right now?

**Comment by thomasmalloch** [comment]
Right now I want to use a proprietary JSON encoder to encode string values. To get that to work with this library, I would need to override a System.Text.Encodings.Web.TextEncoder to use our proprietary encoder, which seems a bit of a roundabout way to go about it.

If there was some sort of callback I could use with the Render method that asks be how I would like a string value encoded, that would solve my problems.

**Comment by sebastienros** [comment]
This is the way I intended it, use a custom TextEncoder. I don't see what can't be done with it. If you want a text encoder to call another external method you can still do that.

Another approach is to use a custom filter. There is the `| json` one already that will encode anything to json, like for instance string that will then have the quotes too, or arrays that will be outputted with `[ ... ]`
