### ISSUE TITLE
Able to access unregistered properties

### ISSUE THREAD

**Issue by Josef-Haupt** [sebastienros/fluid#314]
I have two classes A and B.
```csharp
private class A
{
    public string AProperty1 { get; set; }

    public string AProperty2 { get; set; }

    public B B { get; set; }
}

private class B
{
    public string BProperty1 { get; set; }

    public string BProperty2 { get; set; }
}
```
I then register only one property from each class.
```csharp
var options = new TemplateOptions();
options.MemberAccessStrategy.Register(typeof(A), "AProperty1");
options.MemberAccessStrategy.Register(typeof(B), "BProperty1");
```
But in my template I try to access all properties of each type.
```csharp
 var templateText = "" +
               "{{ AProperty1 }}" +
               "{{AProperty2}}"+
               "{{B.BProperty1}}" +
               "{{B.BProperty2}}";
var parser = new FluidParser();
var template = parser.Parse(templateText);
```
When I parse the `template` with the following context
```csharp
var input = new A
{
    AProperty1 = "Hello",
    AProperty2 = "Are",
    B = new B
    {
        BProperty1 = "World",
        BProperty2 = "Me"
    }
};
var context = new TemplateContext(input, options);
var result = template.Render(context);
```
I expect `result` to be `"Hello"`, because I specifically did not register the `B` as well as the `AProperty1` property of type `A`.
But the result is actually `"HelloAreWorld"`. Which means it correctly ignored the `BProperty2` property of type `B`, but registered all properties of type `A`.

Did I miss something or Is this expected behaviour? And if so, can you explain to me why?
I'm currently using Fluid.Core 2.0.5.

**Comment by sebastienros** [comment]
Looks like a bug. `B` should result in a `nil` value. You can try to fix it or I will take a look.

**Comment by sebastienros** [comment]
Found the root cause, in the doc:

> Note: When passing a model with `new TemplateContext(model)` the type of the `model` object is automatically registered.

**Comment by sebastienros** [comment]
I think I had made an overload to prevent this behavior, will check.

**Comment by Josef-Haupt** [comment]
Thanks Sebastien. I did not see the note in the docs, but it now works as expected, at least in my opinion.
