### ISSUE TITLE
What would be a good way to have global data? (Such as Razor's User and Request objects)

### ISSUE THREAD

**Issue by Saticmotion** [sebastienros/fluid#316]
I'm not exactly sure how to phrase my question, so do let me know if I need to clarify something.

**In Razor templates you always have access to e.g. User and Request. Is there a way to do something similar in Fluid?**

It doesn't need to be fully automagic like in Razor, but at the moment I can only emulate it by manually adding my "global" data to my model in each endpoint. And then each time I render a page, I would have to get the data to my template and my baselayout.

_Maybe I'm also completely wrong about how you're supposed to use Fluid. So below is my Render method, with some comments explaining what I'd like to add._

```C#
//TemplateContext is created in my controllers. Baselayout has all the shared HTML of e.g. page header and footer
public static async Task<string> Render(string templateName, TemplateContext context, BaseLayout layout = BaseLayout.Web)
{
	if (templateCache.TryGetValue(templateName, out var template))
	{
		//Call a function to get user data

		//Then add that user data to the context param

		string result;
                //This would probably be merged with the else clause if I want to access User in pages without models
		if (context == null)
		{
			result = await template.RenderAsync();
		}
		else
		{
			context.MemberAccessStrategy = defaultAccessStrategy;
			context.MemberAccessStrategy.Register(context.Model.GetType());
			result = await template.RenderAsync(context);
		}

		if (layout != BaseLayout.None)
		{
			//At this point, also add the user data to this new context
			var content = new TemplateContext(new { content = result });
			result = await layoutCache[layout].RenderAsync(content);
		}

		return result;
	}
	else
	{
		throw new Exception($"Something went wrong while rendering {templateName}");
	}
}
```

**Comment by jptissot** [comment]
Maybe you can have a look at how it's setup in OrchardCore and it may lead you to answers? 

https://github.com/OrchardCMS/OrchardCore/blob/3b1e4cb0769f694d8f95a128122c8454044fc658/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/OrchardCoreBuilderExtensions.cs#L82

**Comment by sebastienros** [comment]
That is actually quite straightforward. When you render a template you need to pass a `TemplateContext` instance, which is built from a `TemplateOptions` instances. These options are where you put things that are common to all your contexts. And you can set some properties on it, with `options.Scope.SetValue(name, value)`.

You can also have different options instances if you need to have different things to share across templates.

**Comment by Saticmotion** [comment]
Sounds good, I'll give it a try tomorrow. Thanks for the quick replies!

**Comment by Saticmotion** [comment]
This is working great, thanks!
