### ISSUE TITLE
"Buffer has already been rendered" exception

### ISSUE THREAD

**Issue by jptissot** [sebastienros/fluid#318]
I have a `Menu.liquid` where we render the Items in two different lists.
```
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}

.....
  {% for item in Model.Items %}
      {{ item | shape_render }}
  {% endfor %}
```

This exception occurs. Removing the second for loop fixes the issue.

![image](https://user-images.githubusercontent.com/4681586/115869506-f8c22280-a40b-11eb-8504-eb91143a81cd.png)

**Comment by sebastienros** [comment]
Can you create it in OC, I can't transfer across orgs.

**Comment by sebastienros** [comment]
If they are displayed the same way, a mitigation for now is to use `{% capture %}`.

**Comment by jptissot** [comment]
> If they are displayed the same way, a mitigation for now is to use `{% capture %}`.

This is exactly what I ended up doing 👍🏼
