### ISSUE TITLE
the mvc sample dosent work in version 2

### ISSUE THREAD

**Issue by nkouhi** [sebastienros/fluid#321]
In version 2, neither the {%for%} nor {%layout%} works,
Even MVC Sample does not work without any changes.

**Comment by sebastienros** [comment]
Can you provide more details? I already have multiple tests for these. And also other projects using it.

**Comment by nkouhi** [comment]
just run the mvc sample project, this is output:

```
From /Views/Home/_ViewStart.liquid
57
From /Views/_ViewStart.liquid
Hello World from Liquid 2

<h1>This is a title</h1>




<div>Hello Index. This is a partial in the Views/Home folder</div>



Hello from MyTag

```

{% layout '_Layout' %} does not work so the output has no layout .

even 
```
{% for p in Model %}
  <p>{{ p.Firstname }} {{ p.Lastname }}</p>
{% endfor %}
```
does not render anything.

**Comment by sebastienros** [comment]
Thanks for reporting it. I fixed the MVC view engine and the sample.
