### ISSUE TITLE
Custom Filters Issue

### ISSUE THREAD

**Issue by ronfcodes** [sebastienros/fluid#322]
I am attempting to use a custom filter in a .Net core test application with v 2.07  I am getting an error indicating that it's the wrong return type using the example provided on the documentation page.  I have tried a few different things but nothing so far has worked.  I have attached a snapshot of the code from the example page and the compilation errors.

![image](https://user-images.githubusercontent.com/7442684/116132919-17d6e380-a69c-11eb-9649-9059f7068b6c.png)

**Comment by sebastienros** [comment]
```
public static ValueTask<FluidValue> Downcase...
```

I am fixing the README, thanks
