### ISSUE TITLE
Sample Project Not Working

### ISSUE THREAD

**Issue by ronfcodes** [sebastienros/fluid#323]
I am running into a few different issues but I figured I would test against the sample project in the code but it just spins and the page never loads.

**Comment by sebastienros** [comment]
Works fine for me. Using the main branch. I actually fixed it two days ago when it was reported as broken.

![image](https://user-images.githubusercontent.com/1165805/116265604-1bb44580-a730-11eb-8f71-53b0e33f1af3.png)

**Comment by ronfcodes** [comment]
I still wasn't able to get the sample project to run, I'm assuming that our environments could be different and I don't have the time to spend in figure it out at the moment.  In case it helps someone else with the site not loading and just spinning I changed the program.cs file of the site to below and it worked.

`   public class Program
    {

        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }`

**Comment by sebastienros** [comment]
Found the reason to be IIS. When running with it I had the same issue. My VS picked Kestrel by default.
I updated the template like yours and added some default logging configuration from the standard templates and everything should be fine now. Thanks for reporting.
