### ISSUE TITLE
CamelCase member name strategy does not work with UnsafeMemberAccessStrategy

### ISSUE THREAD

**Issue by ssougnez** [sebastienros/fluid#329]
Hello,

I defined my options like this:

```
_options = new TemplateOptions
{
    MemberAccessStrategy = new UnsafeMemberAccessStrategy
    {
        MemberNameStrategy = MemberNameStrategies.CamelCase
    }
};
```

And the object I pass looks like this:

```
var result = new
{
    Data = ...
};
```

However, in the template, I have to use `Data` to reference `Data` instead of `data` even though I specified the `MemberNameStrategy` to `CamelCase`. Is it possible to use the unsafe member access strategy with camel name naming strategy?

(and btw, thanks a lot for this awesome library)

**Comment by sebastienros** [comment]
Probably this `UnsafeMemberAccessStrategy` is not taking the enum into account. Will check.

**Comment by ssougnez** [comment]
Works like a charm ;-)
