### ISSUE TITLE
Cycle group parameter doesn't support strings

### ISSUE THREAD

**Issue by gvkries** [sebastienros/fluid#337]
I was just trying to use the cycle tag with a group parameter as described [here](https://shopify.github.io/liquid/tags/iteration/) : 
```
{% cycle "first": "one", "two", "three" %}
{% cycle "second": "one", "two", "three" %}
{% cycle "second": "one", "two", "three" %}
{% cycle "first": "one", "two", "three" %}
```

This doesn't work with strings as the group parameter, but with literals:
```
{% cycle first: "one", "two", "three" %}
{% cycle second: "one", "two", "three" %}
[...]
```

Shouldn't the group parameter support strings too?

**Comment by sebastienros** [comment]
Are you using an older version?

**Comment by sebastienros** [comment]
Ah sorry, you aren't, will fix asap
