### ISSUE TITLE
Assign problem on new version.

### ISSUE THREAD

**Issue by lzymll** [sebastienros/fluid#340]
{% assign price = 10 %} 
{% assign qty = 1 %} 
{% assign subTotal =price * qty %}

ParseException: '%}' was expected at (45:33)
Fluid.MvcViewEngine.FluidRendering.ParseLiquidFile(string path, IFileProvider fileProvider, bool includeViewStarts) in FluidRendering.cs,

**Comment by sebastienros** [comment]
`price * qty` is not supported in the official Liquid syntax. You need to use `{% assign subTotal =price | times: qty %}`
