### ISSUE TITLE
Very basic For example doesn't work

### ISSUE THREAD

**Issue by dehghani-mehdi** [sebastienros/fluid#356]
With this template:

```
<ul id='products'>
    {% for p in products %}
    <li>
        <h2>{{ p.name }}</h2>
        <span>Only {{ p.price }}</span>
        <p>{{ p.description | truncate: 30 }}</p>
    </li>
    {% endfor %}
</ul>
```

And this `C#` code:

```cs
public class Product
{
    public Product(string name, float price, string description)
    {
        Name = name;
        Price = price;
        Description = description;
    }
	
    public string Name { get; set; }
    public float Price { get; set; }
    public string Description { get; set; }
}
//======================================
var products = new List<Product>();
for (int i = 0; i < 1; i++) products.Add(new Product("Name" + i, i, "Description"));

var parser = new FluidParser();

parser.TryParse(productTemplate, out var template, out var _);

var options = new TemplateOptions();
options.MemberAccessStrategy.Register<Product>();
options.MemberAccessStrategy.MemberNameStrategy = MemberNameStrategies.CamelCase;

var context = new Fluid.TemplateContext(options).SetValue("products", products);

var result = template.Render(context);
```

I got this as result:

```html
<ul id='products'>
	
    <li>
        <h2></h2>
        <span>Only </span>
        <p></p>
    </li>
	
</ul>
```

Why?

**Comment by dafergu2** [comment]
Without testing it myself and with only knowledge I have from using liquid and fluid in OC, I think you need to do the following:

`var context = new Fluid.TemplateContext(options).SetValue("products", new ArrayValue(products.Select(p => new ObjectValue(p)))`

Fluid needs you to wrap your data in its object types.  They all derive from `FluidValue`.

An example to see what I mean is:

https://github.com/OrchardCMS/OrchardCore/blob/1ca2d744054ce5a991f26675e4919e56f66918bb/src/OrchardCore.Modules/OrchardCore.Settings/Startup.cs#L41-L74

**Comment by dehghani-mehdi** [comment]
@dafergu2 nope, still same result.

BTW, I took my code from here: https://github.com/sebastienros/fluid/blob/main/Fluid.Benchmarks/FluidBenchmarks.cs#L34

**Comment by dafergu2** [comment]
Hrm, interesting.  Can you post a repo with the reproduction?  If I have a spare moment this week (might be tough) I'll try and take a look.

**Comment by dehghani-mehdi** [comment]
@dafergu2 here you go: https://github.com/dehghani-mehdi/fluid-testcase

**Comment by dehghani-mehdi** [comment]
@MarcoBeerepoot I tested your suggestion before opening issue here, the output didn't change in either case.

**Comment by MarcoBeerepoot** [comment]
@dehghani-mehdi That's odd. I checked out your repo and tried some things myself. Changed the casing and it worked. That's why I posted my comment.
I tried again this morning. Discarded all changes, changed the casing of 1 property and it printed out that property, but not the others.

This is the template I use and the only thing I changed to make it work:

```
<ul id='products'>
{% for p in products %}
    <li>
		<h2>{{ p.Name }}</h2>
		<span>Only {{ p.Price }}</span>
		<p>{{ p.Description | truncate: 30 }}</p>
    </li>
{% endfor %}
</ul>
```

**Comment by dehghani-mehdi** [comment]
@MarcoBeerepoot interesting, so you cloned my repo and changed the template to what you posted and it worked for you?

**Comment by MarcoBeerepoot** [comment]
> @MarcoBeerepoot interesting, so you cloned my repo and changed the template to what you posted and it worked for you?

That's correct

**Comment by sebastienros** [comment]
Here is a link to the documentation about casing and how to change it: 
https://github.com/sebastienros/fluid#object-members-casing

**Comment by dehghani-mehdi** [comment]
@MarcoBeerepoot I have no idea why it happened, I'm sure I tested every possible solutions before.
Anyway, thanks man.
