### ISSUE TITLE
How to use dictionary object in the template in c# ?

### ISSUE THREAD

**Issue by pulkitmbd** [sebastienros/fluid#358]
static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            var parser = new FluidParser();
            TemplateOptions options = new TemplateOptions();

            var fileProvider = new PhysicalFileProvider(Environment.CurrentDirectory);
            options.FileProvider = fileProvider;

            Dictionary<string, string> model = new Dictionary<string, string>();
            model.Add("Firstname", "Bill");
            model.Add("Lastname", "Gates");
            options.ValueConverters.Add((value) => value is Dictionary<string, string>);
            //var model = new { Firstname = "Bill", Lastname = "Gates" };
            var source = File.ReadAllText("EmailTemplate.html");

            if (parser.TryParse(source, out var template, out var error))
            {
                var context = new TemplateContext(model, options);
                Console.WriteLine(template.Render(context));
                Console.WriteLine("Parsed successfully");
            }
            else
            {
                Console.WriteLine($"Error: {error}");
            }
        }

I am using in this way, but its not working.

**Comment by gr8tushar** [comment]
+1
This would make it lot easier to add values to the template and render them.

**Comment by gr8tushar** [comment]
> Try this:
> 
> ```cs
> void Main()
> {
> 	var parser = new FluidParser();
> 	TemplateOptions options = new TemplateOptions();
> 
> 	Dictionary<string, string> model = new Dictionary<string, string>();
> 	model.Add("Firstname", "Bill");
> 	model.Add("Lastname", "Gates");
> 	var source = "{{dic.Firstname}}";
> 
> 	if (parser.TryParse(source, out var template, out var error))
> 	{
> 		var context = new TemplateContext(options);
> 		context.SetValue("dic",model);
> 		Console.WriteLine(template.Render(context));
> 		Console.WriteLine("Parsed successfully");
> 	}
> 	else
> 	{
> 		Console.WriteLine($"Error: {error}");
> 	}
> 
> }
> ```
> 
> output:
> 
> ```
> Bill
> Parsed successfully
> ```

Will this work if the source is just {{FirstName}} ? In this case how would one assign dictionary to the context ?

**Comment by sebastienros** [comment]
Example I just added to the documentation.

```csharp
var options = new TemplateOptions();
options.MemberAccessStrategy.Register<IDictionary, object>((obj, name) => obj[name]);

var model = new Dictionary<string, object>();
model.Add("Firstname", "Bill");
model.Add("Lastname", "Gates");

var template = _parser.Parse("{{Firstname}} {{Lastname}}");
```

**Comment by hisuwh** [comment]
How we do this now?  The syntax above does not seem to be valid anymore?

**Comment by sebastienros** [comment]
You don't need to register dictionaries anymore, they are supported oob.

**Comment by hisuwh** [comment]
We were trying to pass a dictionary as the main model object - this doesn't seem to work.  We've managed to work around this by creating a class for our model with a property which is a dictionary - which as you say, works OOB.

**Comment by sebastienros** [comment]
what version are you using? can you provide a repro?

**Comment by sebastienros** [comment]
In exchange I give you the code that tests the feature:

https://github.com/sebastienros/fluid/blob/b370f3ed8df07a8966fac357eef8b0f819ec42e7/Fluid.Tests/MemberAccessStrategyTests.cs#L230-L241
