### ISSUE TITLE
_ViewStart.liquid not found on Linux because of case sensitivity

### ISSUE THREAD

**Issue by CuriousCurmudgeon** [sebastienros/fluid#361]
Fluid.MvcViewEngine does not correctly find `_ViewStart.liquid` files on Linux because of case sensitivity. I've confirmed this with the MVC sample. It works on Windows, but not on Linux.

The call to `fileProvider.GetfileInfo` always fails unless the casing of the file is exactly `_viewstart.liquid`. See https://github.com/sebastienros/fluid/blob/main/Fluid.MvcViewEngine/FluidRendering.cs#L89.

**Comment by hishamco** [comment]
I'm wondering while the original file is `_ViewStart.liquid`

**Comment by CuriousCurmudgeon** [comment]
> I'm wondering while the original file is `_ViewStart.liquid`

My assumption was that it's just matching the default casing of `_ViewStart.cshtml` when a new project is generated.

**Comment by CuriousCurmudgeon** [comment]
Thanks for fixing this issue. 💯
