### ISSUE TITLE
how get objects with handles? {{ pages["about-us"].title }}

### ISSUE THREAD

**Issue by nkouhi** [sebastienros/fluid#362]
https://shopify.dev/api/liquid/basics/handle
we can get objects with index like {{ products[1].name }} but how we can get with handles for example: {{ products["shirt"].name }}?

**Comment by sebastienros** [comment]
If `products` is an array, then only the numeric indexer will work. You can implement custom resolution of the indexer, but then you need `prodcuts` to be a custom type and register a custom accessor in the options for this type, like this: https://github.com/sebastienros/fluid#intercepting-a-type-access
