### ISSUE TITLE
Casing does not apply to nested types

### ISSUE THREAD

**Issue by benfoster** [sebastienros/fluid#364]
I configured Fluid to use snake_casing using:

```c#
TemplateOptions.Default.MemberAccessStrategy.MemberNameStrategy = MemberNameStrategies.SnakeCase;
```

It seems this only applies for top level members and not nested types. This works:

```html
              <td>
                {{ company_name }}<br /> <!-- this works -->
                {{ company_address.line1 }}<br /> <!-- this doesn't -->
                {{ company_address.Line1 }}<br /> <!-- this does -->
              </td>
```

I tested with my own strategy delegate and it appears to be only invoked for top level members. Is this by design?

**Comment by hishamco** [comment]
Seems the casing is matter, we may create a unit test for it to ensure if it's a bug

**Comment by hishamco** [comment]
I can confirm that everything works as expected, you can try this unit test:

```csharp
        [Fact]
        public void TestSnakeCaseStrategy()
        {
            var options = new TemplateOptions();
            options.MemberAccessStrategy.MemberNameStrategy = MemberNameStrategies.SnakeCase;
            options.MemberAccessStrategy.Register<Company>();
            options.MemberAccessStrategy.Register<Address>();

            var company = new Company { Name = "Company Name", CompanyAddress = new Address { Line1 = "Line 1" } };

            var template = _parser.Parse("{{name}};{{company_address.line1}};{{company_address.Line1}}");
            Assert.Equal("Company Name;Line 1;Line1", template.Render(new TemplateContext(company, options)));
        }
```

Expected: Company Name;Line 1;Line1
Actual:   Company Name;Line 1;

**Comment by benfoster** [comment]
I copied your test into my project and it passed and then strangely my template started rendering. Given I'm copying the template to the output directory I'm wondering if it had not picked up the latest changes. Thanks for the help.
