### ISSUE TITLE
Implement base64 filters

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#365]
https://github.com/Shopify/liquid/pull/1450

**Comment by sebastienros** [comment]
Implementation details for "safe" versions: https://ruby-doc.org/stdlib-2.5.3/libdoc/base64/rdoc/Base64.html#method-i-urlsafe_encode64

**Comment by jptissot** [comment]
Basic implementation here: 
https://github.com/StatCan/StatCan.OrchardCore/blob/master/src/Modules/StatCan.OrchardCore.DisplayHelpers/Filters/Base64Filters.cs#L8

**Comment by hishamco** [comment]
We already have `UrlEncode` and `UrlDecode` filter, I will add `Base64Encode` and `Base64Decode`

**Comment by sebastienros** [comment]
> We already have UrlEncode and UrlDecode filter

It is not related. `base64_url_safe_encode` uses a custom set of chars:
```
The alphabet uses ‘-’ instead of ‘+’ and ‘_’ instead of ‘/’.
```

So for these it just needs to replace `+` and `/` by `-` and `_`. It can be a simple Replace call. The goal is to generate a sort of base64 that can be used in url. The standard base64 char set contains + and / which would make it incompatible. It also has `=` but only at the end so it's not an issue.

**Comment by hishamco** [comment]
I think I will be add another PR to add `base64_url_safe_encode` as another filter

**Comment by hishamco** [comment]
> It also has = but only at the end so it's not an issue.

I left the = at the end because it creates an issue during decoding
