### ISSUE TITLE
Passing filter argument as expression

### ISSUE THREAD

**Issue by ns8482e** [sebastienros/fluid#373]
Is it possible to pass filter argument as  identifier/expression instead of string? 

`{{  theobj | where:  in: p,  condition:  p.Amount > 0  }}`

**Comment by sebastienros** [comment]
Liquid doesn't allow that. You need an intermedia variable.
https://shopify.github.io/liquid/filters/where/

**Comment by ns8482e** [comment]
@sebastienros  ok ! However is there a way in Fluid to extend to include expression in arguments ?

**Comment by sebastienros** [comment]
Ash, sorry, didn't see it this way. I'd suggest to create a new filter for that, since this one wouldn't parse a difference expression. And then yes, you can evaluate anything.

**Comment by ns8482e** [comment]
the problem is that I  need to pass expression as argument and I need to evaluate that expression inside filter for each record

**Comment by sebastienros** [comment]
maybe pass the expression as a string, and use a different parse parse phase to extract the expression?
That would even work with the existing filter name, you can just replace with your own, and a custom name for the argument
