### ISSUE TITLE
Wiki ambiguity

### ISSUE THREAD

**Issue by sanghel-payoff** [sebastienros/fluid#383]
It is not clear from the wiki whether Fluid supports all [liquid functionality](https://shopify.github.io/liquid/).

I tried using the [truncate filter](https://shopify.github.io/liquid/filters/truncate/) and am getting parsing errors...

```
Here is my {{ ReallyLongStringProp | truncate 10 }} really long but truncated string
```

Does Fluid support all base liquid functionality and adds some on top, or am I understanding the wiki wrong?

**Comment by sebastienros** [comment]
Closing in favor of https://github.com/sebastienros/fluid/issues/397
