### ISSUE TITLE
reverse bug?

### ISSUE THREAD

**Issue by chinasqzl** [sebastienros/fluid#392]
![image](https://user-images.githubusercontent.com/16968103/140479393-1f68a3a4-0201-4c6e-bb5f-a86fb0696c5a.png)

but:

{% assign my_array = "abc,123" | split: "," %}
{{ my_array | reverse | join: "," }}

Output:
![image](https://user-images.githubusercontent.com/16968103/140480384-ae07b6e5-81e7-40b3-aad0-aa49950a4bb7.png)

**Comment by hishamco** [comment]
I wil have a quick look ...

**Comment by hishamco** [comment]
After few investigation I notice that we have naming collision in `reverse` filter I fixed the issue in my local, I will push a PR in upcoming hours coz I don't have a good internet connection at the moment

**Comment by hishamco** [comment]
Related to #367 which pushed by me ;) seems we forgot that we already have the same exact filter name in `ArrayFilters`

The upcoming PR should resolve this permanently

**Comment by sebastienros** [comment]
There should be only one filter named `reverse` that checks if the value is an Array or a String before applying the correct logic. Should be in Misc filters then.

**Comment by hishamco** [comment]
I already did that in `ArrayFilters` that call the proper implementation based on the input but we could move it to the Misc

**Comment by sebastienros** [comment]
Ok, should be easy to move the code around then, it's already checking for arrays I saw.
