### ISSUE TITLE
Feedback for MinimalViews

### ISSUE THREAD

**Issue by agriffard** [sebastienros/fluid#400]
I tested https://github.com/sebastienros/fluid/blob/main/MinimalApis.LiquidViews/README.md

Suggestions: 
- All liquid files are meant to be in a Views folder? Please say it at the beginning.
- Move `From /Views/_ViewStart.liquid` outside the code block (or else we would also paste it).
- Update assets (Bootstrap beta 3) to obtain a nice layout or may be a ClassLess css like https://github.com/mblode/marx if BS is too cumbersome (Preview some classless css : https://dohliam.github.io/dropin-minimal-css/)

I had to rebuild to actually see the changes made in the Liquid files. Have I missed anything?
Is Hot reload supposed to work?

What about making a dotnet new Template nuget package?

**Comment by dodyg** [comment]
https://github.com/dodyg/practical-aspnetcore/tree/net5.0/projects/net6/liquid-view

I created a new sample here. Yeah I can't get the hot reload to work either.

**Comment by sebastienros** [comment]
Thanks. 

I was too lazy to talk about Views and also document the options, guess I should do it ;)
Will remove BS3, it's adding unnecessary complexity to the sample.

When you mention hot reload, I instinctively think about the dotnet feature. But I have an internal one based on FSWatchers, I believe that's what you mean. It might be broken will check. There should be an option to disable it in production IMO.

**Comment by dodyg** [comment]
The expectation is that when the view is updated, it will be reflected on the browser without having to rebuild and restart kestrel.
