### ISSUE TITLE
Rendering nested objects

### ISSUE THREAD

**Issue by avoxm** [sebastienros/fluid#407]
Hello, I am trying to parse a variable with nested object and for some reason it does not work.
Could you please advise if there's an issue with this code 

```
dynamic templateParams = new { 
    Name = "Bruce",  
    Address = new { City = "Gotham" }
};

var template = "Hey {{ Name }}, how's {{ Address.City }}";

renderer.Parse(template, templateParams);
```

The result is : `Hey Bruce, how's `

**Comment by sebastienros** [comment]
You need to allow the type of this property like this: https://github.com/sebastienros/fluid#allow-listing-object-members

**Comment by avoxm** [comment]
Thanks for the prompt reply @sebastienros. Sorry I should have mentioned that I am looking at it from [FluentEmail](https://github.com/lukencode/FluentEmail) and unfortunately there seem to be no option to configure it there. 
I understand it is not related to Fluid though. Thanks again

**Comment by unruledboy** [comment]
@sebastienros  but in "Allow-listing a specific type", it says :

> When passing a model with new TemplateContext(model) the type of the model object is automatically registered. This behavior can be disable by calling new TemplateContext(model, false)

So, the nested properties should be registered automatically, right? We have exact same problem here.

**Comment by T0shik** [comment]
> Alternatively, the MemberAccessStrategy can be assigned an instance of UnsafeMemberAccessStrategy which will allow any property to be accessed.

**Comment by rpb4004** [comment]
Hey everyone,

I'm trying to use MemberAccessStrategy as instructed here, but still unable to access nested fields in a JSON object. Not sure what I'm doing wrong:

`using Fluid;
string templatingResult = string.Empty;
var model = new {
    LiquidTemplate = @"{%- assign deviceList = content.devices | Split: ', ' -%}
{
    ""fullName"": ""{{content.firstName | Append: ' ' | Append: content.lastName}}"",
    ""firstNameUpperCase"": ""{{content.firstName | Upcase}}"",
    ""phoneAreaCode"": ""{{content.phone | Slice: 1, 3}}"",
    ""devices"" : [
{%- for device in deviceList -%}
    {%- if forloop.Last == true -%}
    ""{{device}}""
    {%- else -%}
    ""{{device}}"",
    {%- endif -%}
{%- endfor -%}
    ]
}",
JsonObject = @"{
    ""content"": {
    ""devices"": ""Surface, Windows Phone, Desktop computer, Monitors"",
    ""firstName"": ""Dean"",
    ""lastName"": ""Ledet"",
    ""phone"": ""[(111)5551111](tel:1115551111)""
    }"
};
FluidParser _parser = new();
string? jsonObjectDataString = model.JsonObject;
if (_parser.TryParse(model.LiquidTemplate, out var template, out var error))
{
    TemplateOptions templateOptions = new TemplateOptions();
    templateOptions.MemberAccessStrategy = new UnsafeMemberAccessStrategy() { IgnoreCasing = true };
    TemplateOptions.Default.MemberAccessStrategy = new UnsafeMemberAccessStrategy() { IgnoreCasing = true };
    var context = new TemplateContext(jsonObjectDataString, templateOptions, true);
    templatingResult = await template.RenderAsync(context);
}`

When running that code, the engine is unable to access the fields under "content".

**Comment by sebastienros** [comment]
You are not passing an json object, you are passing a string with Json. You need to parse the json with a json parser, like NewtonSoft.Json or System.Text.Json. Or create a real model that the member access strategies can actually use.

**Comment by rpb4004** [comment]
> You are not passing an json object, you are passing a string with Json. You need to parse the json with a json parser, like NewtonSoft.Json or System.Text.Json. Or create a real model that the member access strategies can actually use.

We cannot bind it to a real model because we do not know what the Json is going to look like, and when we try and parse into a dynamic object it resolves simple items like strings and integers, but not more complex ones like classes or even timestamps. The Json object being received can vary a lot and we are trying to make it the templates responsibility to create the right output.

**Comment by sebastienros** [comment]
> Or create a real model

Meaning this is one option (emphasis on "or"). If this is not working for you then take the first option. You can parse to an abstract object model. NewtonSoft json does it, System.Text.Json does it too. And Fluid supports it out of the box.

Here is a unit test that does exactly what you want:

https://github.com/sebastienros/fluid/blob/91dcc869374e9a6d37ad8f7caa584f20cbcb763a/Fluid.Tests/MemberAccessStrategyTests.cs#L169-L179
