### ISSUE TITLE
Context variables can be set to null, but then throw an exception if you attempt to access them

### ISSUE THREAD

**Issue by deanebarker** [sebastienros/fluid#410]
You can set a null value in the context, like this:

```
context.SetValue("name", null);
```

Trying to access this in the template, like this --

```
{{ name }}
```
-- will throw a `NullReferenceException`

This seems wrong. If you can't access a null variable from the context, then set a `ArgumentNullException` if someone tries to set a null value.

**Comment by deanebarker** [comment]
So you can still set them, they're just converted to "safe" `NillValue` values, correct?

**Comment by sebastienros** [comment]
Yes. `null` is a valid value. Can be checked against `empty` or `blank`. Like any property of the model.
