### ISSUE TITLE
Variable Names cannot start with numeric characters?

### ISSUE THREAD

**Issue by MrUpsideDown** [sebastienros/fluid#422]
In Fluid, this template 
`{% assign 1st = "first" %} {{ 1st }}`
throws the error "An identifier was expected after the 'assign' tag".

Although I can't find any explicit mention of variable naming restrictions in the official Liquid documentation, it seems that this should be acceptable because it works when I run it in this sandbox:
https://jumpseller.com/support/liquid-sandbox/

It's also supported by DotLiquid, which we are currently migrating from.
Can somebody please clarify if this is an intentional limitation in Fluid?

**Comment by hishamco** [comment]
In nutshell Fluid parser is using normal identifier restriction in almost languages, may be it needs to be mentioned in docs if Liquid allows this or change the parser

@sebastienros your though?

**Comment by hishamco** [comment]
I may check the Liquid identifier spec and update the parser

**Comment by sebastienros** [comment]
Release ongoing

**Comment by hishamco** [comment]
I'm suffering from my internet connection, my PR was ready 30 minutes ago ;)

**Comment by MrUpsideDown** [comment]
Thanks for the rapid response and fix, much appreciated!
