### ISSUE TITLE
Custom Tag Expression arguments

### ISSUE THREAD

**Issue by eddyjl077** [sebastienros/fluid#427]
How do we get the arguments from a custom tag expression?
There is only an example of a tag identifier in the doc.

Thank you

**Comment by sebastienros** [comment]
This is the section of the documentation you want: https://github.com/sebastienros/fluid#custom-parsers
And in a sub class of `FluidParser` you can then access `ArgumentsList` to build your own expression.

**Comment by sebastienros** [comment]
Here is how it's used in Orchard: https://github.com/OrchardCMS/OrchardCore/blob/339d74b251b53393dd510f8ad3027aa17d78500d/src/OrchardCore/OrchardCore.DisplayManagement.Liquid/LiquidViewParser.cs#L20
