### ISSUE TITLE
StringValue.Create doesn't handle nulls

### ISSUE THREAD

**Issue by deanebarker** [sebastienros/fluid#442]
https://github.com/sebastienros/fluid/blob/main/Fluid/Values/StringValue.cs#L57

Why wouldn't `StringValue.Create` gracefully handle `null` values?  If you try to pass in a `null`, it throws an exception on the call to `.Length`.

It handles empty values. Why not `null` values?

**Comment by hishamco** [comment]
AFAIK `null` in Fluid represents by `NilValue`, I'm not sure why you need to hold `null`? Accourding what you mentioned it should fail
