### ISSUE TITLE
Include variables written to caller's scope

### ISSUE THREAD

**Issue by jeremycook** [sebastienros/fluid#45]
The following is an example of this behavior. You can see that the second time I include 'template' I do not set the value of `varB` but `varB`'s value from the first include of 'template' appears. I also have a similar example of using `with`.

I'm not sure if that is how Shopify's implementation of include behaves. So I don't know that this is strictly a bug. For my purposes it causes problems, and is an unwanted side-effect.

Your thoughts on whether or not this is a bug, or how I could scope variables in a way that they don't leak from one `include` to another would be appreciated.

```c#
var folder = Path.Combine(Path.GetTempPath(), "IncludeScopeExample");
Directory.CreateDirectory(folder);
File.WriteAllText(Path.Combine(folder, "template.liquid"),
@"-----------------
varA = {{ varA }}
varB = {{ varB }}
template = {{ template }}
");

TemplateContext.GlobalFileProvider = new PhysicalFileProvider(folder);

var model = new { Firstname = "Bill", Lastname = "Gates" };
var source =
@"Hello {{ p.Firstname }} {{ p.Lastname }}

{% include 'template', varA: 'first call of varA', varB: 'first call of varB' %}
{% include 'template', varA: 'second call of varA' %}

{% include 'template' with 'third call of with' %}
{% include 'template' %}";

if (FluidTemplate.TryParse(source, out var template))
{
    var context = new TemplateContext();
    context.MemberAccessStrategy.Register(model.GetType());
    context.SetValue("p", model);

    Console.Write(template.Render(context));
}
```

Output:

```console
Hello Bill Gates

-----------------
varA = first call of varA
varB = first call of varB
template = 
-----------------
varA = second call of varA
varB = first call of varB
template = 

-----------------
varA = second call of varA
varB = first call of varB
template = third call of with
-----------------
varA = second call of varA
varB = first call of varB
template = third call of with
```

**Comment by sebastienros** [comment]
I will look into some examples/tests from shopify, but it looks like a bad behavior to me. All this variables should be local to the template, and not leak on subsequent renderings. But we need proof.

**Comment by sebastienros** [comment]
I can't find anything related in the tests https://github.com/Shopify/liquid/blob/9c72ccb82f4e7a1f158b59741596a473c499875e/test/integration/tags/include_tag_test.rb

It looks like the template shouldn't change the parent's variables, but that's it. From the documentation, the other values are actually defining the main context variables, so what you are seeing seems expected. We would need to check on a shopify site probably.

**Comment by jeremycook** [comment]
I'm with you on it "seems expected" but also "looks like bad behavior". It makes for all sorts of unfortunate problems that basically require me to Nil out variables before calling another include.

If it is by design according to Shopify may I suggest we make up our own tag like `partial` that has the scoped behavior you and I seem to expect.

**Comment by jeremycook** [comment]
Jekyll's implementation of include appears to align with what we expect, at least that's my impression after reading this: https://hamishwillee.github.io/2014/11/13/jekyll-includes-are-functions/
