### ISSUE TITLE
Ability to set additional context values when using Fluid.MvcViewEngine

### ISSUE THREAD

**Issue by markeverard** [sebastienros/fluid#455]
When using Fluid.MvcViewEngine and the new FunctionValue options. We want to add additional items to the FluidContext in an MVC context. Current there is no way to do this, outside of forking / modifying the full Fluid.MvcViewEngine project.

Consider adding a way to modify or switch the FluidRendering class - currently registered as as Singleton, specifically allowing us to define our own RenderAsync method.

This also applied to setting AmbientValues in the FluidContext too.

Thinking of  something like the below as an example....
```
public async Task RenderAsync(ViewContext viewContext, string path)
        {
            var context = new TemplateContext(_options.TemplateOptions);
            context.SetValue("ViewData", viewContext.ViewData);
            context.SetValue("ModelState", viewContext.ModelState);
            context.SetValue("Model", viewContext.ViewData.Model);
            
            var lowercase = new FunctionValue((args, context) =>
            {
                var firstArg = args.At(0).ToStringValue();
                var lower = firstArg.ToLower();
                return new ValueTask<FluidValue>(new StringValue(lower));
            });
            
            context.SetValue("LowerCase", lowercase);

            await _fluidViewRenderer.RenderViewAsync(viewContext.Writer, path, context);
        }
```

**Comment by sebastienros** [comment]
Suggestions:
- Create `IFluidRendering` such that custom implementations can be registered instead.
- Create `virtual IFluidRendering.OnRenderAsync(ViewContext viewContext, string path, TemplateContext context)` which can be customized in a sub-class

Other solution:
- Add `RenderingOptions` with a delegate like `OnRenderAsync(ViewContext viewContext, string path, TemplateContext context)`. No new interface.

**Comment by sebastienros** [comment]
Actually since `FluidMvcViewOptions` inherits from `FluidViewOptions` I can add delegates to it (RenderView and RenderPartial) and these will be available in all view engines.

**Comment by markeverard** [comment]
I think that provides the best flexibility in those scenarios where you don't own the Model. 

Looking a little closer at our particular need it's a little more than that. We need to change the RenderAsync signature of FluidRendering, as the custom data I need in the Fluid context is the view engine ViewContext. I have an existing rendering pipeline heavily coupled to HtmlHelpers. 

I can't see a flexible way of achieving that beyond forking / owning our own version of the Fluid.MvcViewEngine

**Comment by sebastienros** [comment]
Can you check if https://github.com/sebastienros/fluid/pull/464 solves everything? If provides access to `ViewContext`.

**Comment by markeverard** [comment]
Hi Sebastien. Yes #464 gives us everything I need. Spot on :)

**Comment by deanebarker** [comment]
@sebastienros  Is this going to be merged?
