### ISSUE TITLE
Shared folder is not used as view location when specifying layout in MVC

### ISSUE THREAD

**Issue by simonech** [sebastienros/fluid#457]
Not sure if it's my mistake, or if by design or is a bug, but I'll give it a shot.

## Issue 
If I put `{% layout '_layout.liquid' %}` either in the index or viewstart files, and I put the `_layout.liquid` file in the `Shared` folder, I get a blank page.
It works only if I also specify the folder (`{% layout 'Shared/_layout.liquid' %}`)

## Replication

I did a vanilla installation of a MVC project in net5 and added the `AddFluid()` to whatever code is in the MVC project template, so I end up with
```
services.AddControllersWithViews().AddFluid();
```

Then I copied the sample pages of the readme and placed the `_layout.fluid` file in the `Shared` folder, as the usual convention.

**Comment by sebastienros** [comment]
Layouts will only match based on the `ViewFileProvider` which is rooted to `/Views` by default.

Looks like `ViewsLocationFormats` is only used for finding views, not Layouts. There is another option, `PartialsLocationFormats`, so I wonder if there should be a third option for layouts, of if it should use the same formats as views.

What do you suggest? Safe bet is to create a custom option, initialized with the same values as for views, but the discoverability of the feature might be impacted.

**Comment by simonech** [comment]
The Razor view engine uses the `Shared` folder also for the layouts and partials.
Maybe also this engine should implement the same behaviour?
