### ISSUE TITLE
Add 'include for' support

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/fluid#46]
c.f. http://www.rubydoc.info/gems/liquid/Liquid/Include

Like `with`, but renders the template for each element in the collection.

**Comment by hishamco** [comment]
Hope I get a change to look into this ASAP

**Comment by hishamco** [comment]
@sebastienros How can we access the current element in the collection inside the template?

**Comment by sebastienros** [comment]
I don't really understand the question. Like in the `for` tag, it should detect that the parameter is a collection, and in this case loop over the collection and call the same code to render the template with a `with` but using each of the elements in the collection.

**Comment by hishamco** [comment]
Yep I knew, what I mean is when the template is applied for each element how can I access the element properties to ensure that I got the right result

**Comment by hishamco** [comment]
@sebastienros could you please reply to my earlier question, so I can push my pending PR?
