### ISSUE TITLE
Bug: For loop restarts on continue

### ISSUE THREAD

**Issue by john-s-morgan** [sebastienros/fluid#463]
Version issue observed: 2.2.13

When we go to continue a for loop in a block of liquid, the loop starts over at index 0, instead of holding the place in the context. The context should be holding the index and continuing to iterate the loop until reaching the last element.

sample pseudocode with expected / actual results:
```
{% assign array = (1..6) %}
{% for item in array limit: 3 %}
{{ item}}
{% endfor %}
{% for item in array offset: continue %}
{{ item}}
{% endfor %}
```
```
expect: 
123
456

actual results:
123
123456
```

**Comment by sebastienros** [comment]
I fixed your test

**Comment by sebastienros** [comment]
Also discovered that Liquid allows to assign ranges directly, so fixed it too. So much learning with one issue.

**Comment by sebastienros** [comment]
https://github.com/sebastienros/fluid/issues/468
