### ISSUE TITLE
Help Parsing If in template -- Invalid 'if' tag error

### ISSUE THREAD

**Issue by gtejeda** [sebastienros/fluid#467]
Greetings guys, this is too basic a question, so my apologies in advance, but I'm unable to find the reason.
Getting the following error:
Error parsing template: Invalid 'if' tag at (2:6)

(Actual html template in a database and have single quotes)

```
var source = @"Basic content here, find more <a href='https://www.google.com' target='_blank'>here</a>
if {{variable1}} == ""Web"" %}
    <b>This works</b>
endif %}";
```

This is my code:
```
dynamic model = new ExpandoObject();
model.variable1 = "Web";

var parser = new FluidParser();
var compiled = "";
if (parser.TryParse(source, out var template, out var error))
{
    var context = new TemplateContext(model);
    compiled = template.Render(context);
}
else
{
    if (!string.IsNullOrEmpty(error))
    {
        Console.WriteLine($"Error parsing template: {error}");
    }
    compiled = source;
}
```

**Comment by lahma** [comment]
Check the syntax guidance here: https://shopify.github.io/liquid/tags/control-flow/

**Comment by gtejeda** [comment]
Thanks @lahma, I believe I'm following the guide properly... :(

**Comment by sebastienros** [comment]
Your example is so far off of the examples that you might want to read the liquid documentation and samples a little more. Hints: missing starting "if" tag; wrong use if condition in {{ }} tag. Start with the "if" section in the docs.

**Comment by lahma** [comment]
So why no `{%` before `if` and `endif`?

**Comment by gtejeda** [comment]
as explained, the actual templated code is in a database, I just made an error pasting it here (and manually trying to re-create the error), I don't know why github's editor deleted them, but whatever,  thanks for responding anyway.
