### ISSUE TITLE
Net with Liquid

### ISSUE THREAD

**Issue by ronfcodes** [sebastienros/fluid#471]
This is more of a question as opposed to an issue.  I created a custom .net core application that was originally supposed to be completely liquid.  To get the project to work I had to modify a few things of course but now I'm running an issue and hoping you have any suggestions.  The currently application works, but if I return a .cshtml page in the controller the razor code doesn't work. I modified the startup file to add back in AddRazorRuntimeCompilation() that was previously commented out.  Adding that back in now makes liquid not recognized.  Do you have a suggestion of a way to be able to support Razor and liquid in a project?

**Comment by sebastienros** [comment]
So an MVC application that can run a Razor view or a Liquid view based on what's available?

**Comment by ronfcodes** [comment]
Yes, at some points it may be liquid and other times razor. Also in case it matter the view start and layout files are .liquid. I was creating a new layout.cshtml specifically for the razor pages.

**Comment by ronfcodes** [comment]
@sebastienros, hey just checking back to see if there is anything you can think of?

**Comment by sebastienros** [comment]
I checked with the team (asp.net mvc) and it should be doable, though I still need to prove that it works ... Also viewstarts/layouts files will only be applied for their own engine.

**Comment by ronfcodes** [comment]
I'm closing the issue it looks like my issue was related more to the project, I made a few modifications to try and get liquid to work and include the .liquid files so maybe the file wasn't being included and recognized as a razor page.
