### ISSUE TITLE
XmlDocument as model

### ISSUE THREAD

**Issue by pentarex** [sebastienros/fluid#479]
Hi, is it possible the model which we pass to the context to be of type XML Document?

I know it can be converted to JSON and passed to the model, what I am trying to achieve is from various documents lets say CSV or XML or Fixed Length to generate JSON using Fluid, currently is working great, but i was wondering how this could be done.

Thank you in advance and sorry if not properly written/understood, just little bit in unknown territory and my head is mess ...

**Comment by deanebarker** [comment]
This might be slightly related? It's a `FluidValue` that models an XML document and allows you to query it view virtual members.

https://gist.github.com/deanebarker/3618faff0b743e351b2afb3adaf5f566

**Comment by pentarex** [comment]
yes thats good example. Thank you! Now i have to think carefully how I can make it work for CSV and maybe make it agnostic of the incoming format (meaning to get rid of _children)
Also not sure if you did it by accident or on purpose, or you just didnt saw need this to be there but in order to work I needed to add it to the value converters:
```csharp
var template = parser.Parse(template);
var options = new TemplateOptions();
options.ValueConverters.Add((v) => v is XDocument document ? new XmlValue(document) : null);
options.ValueConverters.Add((v) => v is XElement element ? new XmlValue(element) : null);
var context = new TemplateContext(xmlModel, options);
```

**Comment by deanebarker** [comment]
If I can be so bold as to promote my own documentation, this page might help you. https://deanebarker.net/tech/fluid/virtual-members/

**Comment by deanebarker** [comment]
> Also not sure if you did it by accident or on purpose, or you just didnt saw need this to be there but in order to work I needed to add it to the value converters:

I was just creating the object explicitly:

```
context.SetValue("xml", new XmlValue(xmlDoc));
```

**Comment by pentarex** [comment]
Also something that i have learned now. Thank you! Also will check your site. Closing it since i think is resolved

**Comment by deanebarker** [comment]
More on value convertors:

https://deanebarker.net/tech/fluid/value-convertors/
