### ISSUE TITLE
Validation possible?

### ISSUE THREAD

**Issue by pentarex** [sebastienros/fluid#481]
Is validation possible somehow? 

Currently I am using CustomFilters to validate the length of a field. Which filter is set in the template as property and an argument (length). In order to generate meaningful message its going to be good somehow to be able to get also the key not only the value which i am validating. 

Is this somehow possible?

Thank you in advance

**Comment by pentarex** [comment]
Is it possible to create custom expression which is divided by ? or ! or ?! and use it as:
`{{ object.data ! mandatory ! length: 3 }}`
I am not sure I want to do it with
`{% .... %}`

**Comment by sebastienros** [comment]
There is a new feature to "visit" a template and event update it if necessary
