### ISSUE TITLE
How to access the syntax tree

### ISSUE THREAD

**Issue by thomasrosdahl** [sebastienros/fluid#482]
Could someone please clarify this section of the readme:

"Parses templates in a concrete syntax tree that lets you cache, analyze and alter the templates before they are rendered."

How can I access the syntax tree of a parsed template? I would like to analyze which values/props are being accessed.

Thanks

**Comment by thomasrosdahl** [comment]
Found it. It's hidden by the IFluidTemplate interface. The concrete implementation has a 'Statements' property which exposes the AST.

**Comment by sebastienros** [comment]
Note that [this PR](https://github.com/sebastienros/fluid/pull/627) contains an updated AST and a visitor pattern which allows to detect specific elements in the template and also modify it.
