### ISSUE TITLE
Getting specified tags

### ISSUE THREAD

**Issue by yilmazbuhar** [sebastienros/fluid#483]
Is this posible to get all tag from specified template?

for example, i want to get all position tags and they values

```
<html>
	<body>
                {% partial '_Partial' %}
		<pre>
		
		</pre>
		<pre>
			{% position position1 %}
		</pre>
		<pre>
			{% position position2 %}
		</pre>
                {% rendersection footer %}
	</body>
</html>
```

**Comment by hishamco** [comment]
This is not HTML Parser, could you please tell what's the use case?

**Comment by yilmazbuhar** [comment]
In the liquid template above, I want to use backend code that returns different data for each request path. This will be a structure like multiple render_body, rather than using a single render_body.
To determine at which position a backend code will run, I need the position information on that liquid. As you said, I can get these values by parsing, but if it's already stored somewhere, I wanted to get it from there.

**Comment by thomasrosdahl** [comment]
Here's an example on how to recursively traverse the AST and handle specific statements.

`

        private void HandleStatements(IEnumerable<Statement> statements)
        {
            foreach (var statement in statements)
            {
                if (statement is TagStatement tagStatement)
                {
                   ....Handle TagStatement
                }
                else if (statement is IfStatement ifStatement)
                {
                    HandleStatements(ifStatement.ElseIfs?.SelectMany(e => e.Statements);
                    HandleStatements(ifStatement.Else?.Statements);
                    HandleStatements(ifStatement.Statements);
                }
                else if (statement is CaseStatement caseStatement)
                {
                    HandleStatements(caseStatement.Whens.SelectMany(w => w.Statements));
                    HandleStatements(caseStatement.Else?.Statements);
                    HandleStatements(caseStatement.Statements);
                }
                else if (statement is UnlessStatement unlessStatement)
                {
                    HandleStatements(unlessStatement.Else?.Statements);
                    HandleStatements(unlessStatement.Statements);
                }
            }
        }
`

**Comment by yilmazbuhar** [comment]
Thanks a lot
