### ISSUE TITLE
Proper boolean support using JObjects 

### ISSUE THREAD

**Issue by sjd2021** [sebastienros/fluid#487]
I have a class that I convert to a JObject using JObject.FromObject like this:

```
  var model = new { MyBool = false };
  var jObject = JObject.FromObject(model);
  var liquidTemplate = Parser.TryParse(rawHtml, out liquidTemplate, out var error);
  return await liquidTemplate.RenderAsync(new TemplateContext(jObject, Options););
```

In the template, doing this does not work because it's always considered truthy and always prints (True or False) even when myBool is false:

```
      {% if myBool %}
            <div>{{ myBool }}</div>
       {% endif %}
```

As a workaround, I have to check ` myBool == "True"` explicitly since that's the ToString'd conversion. I would like to avoid this so I can use liquid templates that are already shared across javascript libraries.

**Comment by sebastienros** [comment]
Maybe try to convert the `JToken` corresponding to bools (can't recall) like this:

```
options.ValueConverters.Add((value) => value is JValue v && v.Type == JTokenType.Boolean ? (bool)v.Value : null);
```

**Comment by sjd2021** [comment]
@sebastienros I'll gladly take this solution. Thank you so much for your constant availability and helpfulness.
