### ISSUE TITLE
Supports Razor pages or Blazor?

### ISSUE THREAD

**Issue by HybridSolutions** [sebastienros/fluid#489]
Hi,

can Fluid be used with Razor Pages or with Razor Components? If yes, any example?

Thank you!

**Comment by hishamco** [comment]
Fluid is a template language like Razor, why you need to mix both of them?

**Comment by hishamco** [comment]
Fluid is a template language like Razor, why you need to mix both of them?

**Comment by HybridSolutions** [comment]
> Fluid is a template language like Razor, why you need to mix both of them?

Because I need templates that don't have to be recompiled each time a change in HTML like a CSS class added to a DIV and this happens with .razor or .cshtml files.

**Comment by hishamco** [comment]
Did you try [MvcViewEngine](https://github.com/sebastienros/fluid/tree/main/Fluid.MvcViewEngine)?

**Comment by HybridSolutions** [comment]
I want to be able to make changes to templates at runtime without having to compile the hole web project like I do now with Blazor or even Razor Pages if not using RuntimeCompilation package. Been using Dotnetliquid in webforms and it worked great. Fluid seems more up to date but wit would be nice to have some more examples of integration with .NET 6, Razor Pages or Blazor.

**Comment by sebastienros** [comment]
There is no specific integration to provide or document. You can run C# code in a view, and all the currently provided samples will work the same way:

```
@{
 // ANY SAMPLE FROM DOCUMENTATION
}
```
