### ISSUE TITLE
Call method on model?

### ISSUE THREAD

**Issue by Kopdardar** [sebastienros/fluid#491]
Is it possible to call functions on a model, including void-returning ones? E.g.:

```
public class Model
{
    public string Greet()
    {
        return "Hey";
    }
}

var parser = new FluidParser(new FluidParserOptions
{
    AllowFunctions = true
});

var model = new Model();

var source = @"
{{ Greet() }}
{{ Greet }}
{{ greet }}
{% assign x = Greet() %}
{{ x }}
{% assign y = Greet %}
{{ y }}";

if (parser.TryParse(source, out var template, out var err))
{
    var ctx = new TemplateContext(model);
    var result = template.Render(ctx);
    Debug.Log("Result: " + result.Trim());
}
else
{
    Debug.LogError("Failed to parse: " + err);
}
```

But the output is just blank.

Is the only option to manually add a FunctionValue to the TemplateContext for each method on the model?

I see that there is a `MethodInfoAccessor` class which seems to imply it would support this, but I don't see where that class is actually used by Fluid. 

I'm thinking this might be by design (for the case where the templates are not completely trusted and you don't want the template-editor to be able to call arbitrary methods, and probably in alignment with original Liquid behaviour) but it seems like it would be a useful feature to be able to opt out of that, similar to the AllowFunctions parameter.

**Comment by Trapulo** [comment]
I also tried to call ToShortDateString() on a DateTime proprety and get blank. Is there a way to perform this kind of call in a quick way?

**Comment by cambirch** [comment]
Just had to deal with this and manually defining was going to be too annoying so I went looking.

Recording my results for future me or others.

This gives the useful hints I needed: #433.

Summary is you don't define a function you define a Property that returns a FluidValue.  You then have the property return a FunctionValue and implement your code inside.

You will also need to account for converting your parameters in and your result objects out.  So arrays/lists/etc that automatically convert have to be manually converted to ArrayValue.  Objects need to be converted to ObjectValue.  Likely a few more.

**Comment by sebastienros** [comment]
FYI, there is also now an optional functions support, not on models but a way to invoke reusable methods defined in a template
