### ISSUE TITLE
Fluid View engine does not work with Windows-style paths corretly

### ISSUE THREAD

**Issue by JustusGreiberORGADATA** [sebastienros/fluid#500]
The following code does not work on a Windows machine properly, because the path is generated with the Windows-style path seperator (`MemberInvitation\MemberInvitation.liquid`) but the discovery code for partials, layouts and viewstarts can't deal with the backslash.

```c#
var path = Path.Join("MemberInvitation", "MemberInvitation.liquid");
await fluidViewRenderer.RenderViewAsync(stringWriter, path, templateContext);
```
For example the code here expects the path seperator to be the forward slash:
https://github.com/sebastienros/fluid/blob/f61b88fda54eabf606b944c94d213a9e2b3fe4ca/Fluid.ViewEngine/FluidViewRenderer.cs#L96-L121

**Comment by hishamco** [comment]
I'm wondering how it works before?

**Comment by ju57u5** [comment]
Before there was no layout path resolution algorithm like that. It just took the layout path directly from the root of the file provider. It was changed here:

https://github.com/sebastienros/fluid/commit/26b931185278b521135b4d777e340519ea985fcd#diff-87667ed94ee7cf341f18d062a1184f52f622dd055e657180b4eeab7a4e02c412R53-R61
