### ISSUE TITLE
truncatewords - truncate indicator is always added, even if shorter

### ISSUE THREAD

**Issue by Flarescape** [sebastienros/fluid#506]
If i use `truncatewords` in one of my OC liquid templates, the 3 dots are always visible, even if the text is much shorter.
![image](https://user-images.githubusercontent.com/1375119/186464522-38667854-fe09-4313-a1d1-d3fabc7b8e34.png)

This happend to me, when i used it like this `truncatewords: 40`, but the 3 dots are also shown on a text with 20 words or something like that.
![image](https://user-images.githubusercontent.com/1375119/186464329-063738e2-f7bd-4c75-8016-2c95f51e8962.png)

Changing the indicator to a custom one also doesn't change that behavior.

**Comment by hishamco** [comment]
Let me double check

**Comment by hishamco** [comment]
If you check below everything seems as expected

https://github.com/sebastienros/fluid/blob/f61b88fda54eabf606b944c94d213a9e2b3fe4ca/Fluid.Tests/StringFiltersTests.cs#L299-L314

Could you please break the test to ensure there's a bug

**Comment by Flarescape** [comment]
@hishamco I'm not quite sure if i'm missing something here, but your last test in line 303 doesn't make much sense to me or seems wrong.
You truncate to 10 words, the example is way shorter, still you have the dots.
That's pretty much exactly the problem i have.
The text is shorter then the truncate size, but still gets the dots or whatever string will be defined for that.

**Comment by sebastienros** [comment]
The bug is obvious, and we need to check the behavior of when the number of words matches exactly by looking at Shopify 's tests.

**Comment by hishamco** [comment]
@Flarescape could you please submit a PR to break the test or write here, then we can check Shopify's tests as Seb mentioned

**Comment by hishamco** [comment]
Ya, I notice the bug, also I might check with Liquid the case that Seb mentioned

**Comment by sebastienros** [comment]
https://github.com/Shopify/liquid/blob/8882338aa1aad79968fafbb4a661d0674adad9b8/test/integration/standard_filter_test.rb#L217-L234

And probably also fix `truncate` since it has the same logic:

https://shopify.dev/api/liquid/filters#truncate

**Comment by hishamco** [comment]
```
{{ "The cat came back the very next day" | truncatewords : 4 }} -> The cat came back...
{{ "The cat came back the very next day" | truncatewords : 8 }} -> The cat came back...
{{ "The cat came back the very next day" | truncatewords : 12 }} -> The cat came back the very next day
```

**Comment by hishamco** [comment]
I will push a PR soon ..

**Comment by hishamco** [comment]
@sebastienros I checked `truncate` the logic seems right

**Comment by Flarescape** [comment]
@hishamco Thanks a lot!
