### ISSUE TITLE
Using `partial layout` without using Fluid as ViewEngine

### ISSUE THREAD

**Issue by dehghani-mehdi** [sebastienros/fluid#513]
I don't want to use Fluid in ASP.NET Core app, I have a console app and I'm planning to use fluid as my Render Engine.
I could not find any useful example/documentation about how to use partial layout feature. would you tell me how can I do that?

For example, I imagine something like this:

`index.html`
```
<!DOCTYPE html>
<html land='en'>
<head>
    <title>Page Title</title>
</head>
<body>
    <main>        		
        <div id='container'>
            <h1>Index</h1>
        </div>        
    </main>
    {% partial '_footer', { model: model } %}
</body>
</html>
```

`partials/_footer.html` _or .liquid_
```
<footer>...</footer>
```

```
var parser = new FluidParser();
var html = File.ReadAllText("index.html");
if (parser.TryParse(html, out var template, out var error))
{
    var context = new Fluid.TemplateContext(model);

    return await template.RenderAsync(context);
}
else
{
    return error;
}
```

**Comment by hishamco** [comment]
```csharp
var parser = new FluidParser();
var html = File.ReadAllText("index.html");

parser.TryParse(source, out var template, out var error);

var fileProvider = new MockFileProvider();
fileProvider.Add("Partials.liquid", @"{{ 'Partial Content' }}
Partials: '{{ Partials }}'
color: '{{ color }}'
shape: '{{ shape }}'");

var options = new TemplateOptions();
options.FileProvider = fileProvider;

var context = new TemplateContext(options);
var result = await template.RenderAsync(context);
```

You could replace the `MockFileProvider` with a physical one

**Comment by sebastienros** [comment]
@hishamco I have no idea what your sample is trying to do ;) 

@dehghani-mehdi there is a `{% render %}` tag that is part of the default liquid tags. There is also `{% include %}` but is being deprecated in favor of `render`. This are "partials".

"Layout" is different and is provided by the View Engine library which doesn't depend on ASP.NET, only the MVC package depends on it.

**Comment by hishamco** [comment]
> @hishamco I have no idea what your sample is trying to do ;)
I just copy paste from the unit test we have ;) just show how we can use partial without using a ViewEngine

**Comment by dehghani-mehdi** [comment]
@sebastienros If you mean changing `{% partial '_footer', { model: model } %}` to `{% render '_footer', { model: model } %}` is the solution, I tried that before posting this issue (actually I saw `render` in `[Liquid](https://shopify.github.io/liquid/)` documentation), and as the result I just see `{% render '_footer', { model: model } %}` on the output (rendered result), that's why I posted this issue.
