### ISSUE TITLE
Nondeterministic unit tests

### ISSUE THREAD

**Issue by danielmpetrov** [sebastienros/fluid#517]
Unit tests are assuming the user has not modified the default culture settings. I have the regional format set as `English (United States)` on my machine, but have customized some of the default formats under the `Date & time` menu in the Windows settings app. This is my config:

![windows-region](https://user-images.githubusercontent.com/15656341/196750947-f9648234-0013-4fe4-b682-ad57b91f85d9.PNG)

And with these settings, five unit tests are failing for me. One example below:

![failing-test](https://user-images.githubusercontent.com/15656341/196751539-7e230782-a0d1-466a-a2ed-49b20c36cfa4.PNG)

**Comment by sebastienros** [comment]
Nice find, these might be bugs or unit tests that need to force the culture (in the options, like we do for several ones already).

**Comment by danielmpetrov** [comment]
The culture is specified, it's just that the expected outcome is hardcoded and doesn't match with the computer configuration.

Is this what you mean by forcing the culture - https://github.com/sebastienros/fluid/blob/main/Fluid.Tests/MiscFiltersTests.cs#L259 (this is one of the tests that fails), or am I misunderstanding?

**Comment by sebastienros** [comment]
> the expected outcome is hardcoded

Hard coded as in "this is exactly what should be rendered, based on the current culture options and any server configuration.

> Is this what you mean by forcing the culture

Yes, some culture-dependent tests/templates will have that to ensure that the "hard-coded" expected result is deterministic. I am never setting the current thread culture to a weird one it might blead to other tests that are executed concurrently (there is a risk with async that the code runs on two different threads). Another option would be to run the whole set of tests with a different culture to be certain that we didnt' miss the option in some places, or that the configure culture is correctly taken into account.

**Comment by danielmpetrov** [comment]
Specifying a second parameter `useUserOverride: false` fixes this issue. Acceptable solution?

```csharp
new CultureInfo("en-US", useUserOverride: false)
```

**Comment by sebastienros** [comment]
Oh, I see what you mean now, that's a different issue. I am well aware of this option as we are currently discussing its usage in ASP.NET request localization and Orchard Core ;)

For the tests yes we should do that such that the environment doesn't break them.

**Comment by sebastienros** [comment]
> You have added this recently, any idea why this is failing locally for me?

What culture and TFM are you running on?
Try to change to English or use a different TFM (if one works) and debug to see the differences.

**Comment by hishamco** [comment]
I might handle this because I already worked in exact usecase in Orchard Core

**Comment by hishamco** [comment]
I might handle this because I already worked in exact usecase in Orchard Core

**Comment by danielmpetrov** [comment]
Failing on all - netcoreapp 3.1, net 5, and net 6. The below code throws locally, so it's something for sure on my end

https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLQGUCWBbADgGwgAUEB7AcwSm2QBoYQE4A7AHwAEAmARgFgAoAQDcoCAAQATWBBg4IYgLxjmEAO5iAItIAqcgBQAGAJQBuYaLGkwYZDMXK1mnXIDy12zD1SYMuaYFWNjIAdACSzMi4EADGnv78QA==

I can open a PR for the rest for now..

**Comment by hishamco** [comment]
I might handle this because I already worked in exact usecase in Orchard Core

**Comment by danielmpetrov** [comment]
Something to do with my time zone it seems.

```csharp
// this throws :(
var datetime = new DateTime(0).AddMinutes(59);
var offset = new DateTimeOffset(datetime);

// this works :)
var datetime = new DateTime(0).AddMinutes(60);
var offset = new DateTimeOffset(datetime);
```

The offset is becoming a negative when `new DateTime(0)` is passed into it.

**Comment by sebastienros** [comment]
What is your timezone?

**Comment by sebastienros** [comment]
If that is timezone dependent then we might need to force one in the DateTimeOffset constructor, or the `new DateTime(0)`

**Comment by danielmpetrov** [comment]
My time zone is set to `UTC +1`, which explains the 60 minute test.

![time-zone](https://user-images.githubusercontent.com/15656341/196768319-82dd2098-b480-45a9-8766-88e408dd2f03.PNG)

**Comment by sebastienros** [comment]
the `new DateTime()` assumes "Local" AFAIR, that might be the issue here when passed to `new DateTimeOffset`.

**Comment by hishamco** [comment]
@danielmpetrov let me knoe if you need help on this, I can push a PR to continue what you already started with

**Comment by hishamco** [comment]
@danielmpetrov let me knoe if you need help on this, I can push a PR to continue what you already started with

**Comment by sebastienros** [comment]
Can't repro the issue:
https://sharplab.io/#v2:EYLgZgpghgLgrgJwgZwLRLKsBLCAbAE2QBoYQE4A7AHwAEAmARgFgAoNgNygQAIBjOHnhIeAXh6UIAdx61GAOgDieAPbAoebAC9Y2FZXkBhQcIgBJSmBUAKAEQEIt4jzAbkEAJQBuNnPkAVAAskKAJsSgBzAODoAiNEJEoYIJC44wREmGMhRAgxfhNcn1Y/FNjwqLLQ+IyIJKq0hLqYAFUzbNN8gRykYs5uHgIYfMkZABFYCH9sAFsIawAGD3kAQQICAFlwuBgUawBWAE5vft4hlRHpHgnd6bmAeTAwdxhrIZP2EsZDt5gPuR+528QA=

**Comment by danielmpetrov** [comment]
@sebastienros if your code, the offset it printed as `+00:00`, I get `+01:00` locally.

```csharp
var datetime = new DateTime(0).AddMinutes(60);
var offset = new DateTimeOffset(datetime);
Console.WriteLine(offset); // 01-Jan-01 01:00:00 +01:00
```

@hishamco If you have an idea go ahead, I have nothing right now. 😁

**Comment by sebastienros** [comment]
Maybe SharpLab is highjacking the culture. The challenge is to create some code that will fail with the same error on any machine. I will try the same code on my local machine then.

**Comment by hishamco** [comment]
> @hishamco If you have an idea go ahead, I have nothing right now. 😁

Ok, it's in plate now ..

**Comment by danielmpetrov** [comment]
@sebastienros

From the docs of the constructor - https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.-ctor?view=net-6.0

> If the value of [DateTime.Kind](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-6.0) is [DateTimeKind.Utc](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-6.0#system-datetimekind-utc), the [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.datetime?view=net-6.0) property of the new instance is set equal to dateTime, and the [Offset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.offset?view=net-6.0) property is set equal to [Zero](https://learn.microsoft.com/en-us/dotnet/api/system.timespan.zero?view=net-6.0).

> If the value of [DateTime.Kind](https://learn.microsoft.com/en-us/dotnet/api/system.datetime.kind?view=net-6.0) is [DateTimeKind.Local](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-6.0#system-datetimekind-local) or [DateTimeKind.Unspecified](https://learn.microsoft.com/en-us/dotnet/api/system.datetimekind?view=net-6.0#system-datetimekind-unspecified), the [DateTime](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.datetime?view=net-6.0) property of the new instance is set equal to dateTime, and the [Offset](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.offset?view=net-6.0) property is set equal to the offset of the local system's current time zone.

So specifying `DateTimeKind.Utc` in the constructor would solve this problem.

```csharp
var datetime = new DateTime(0, DateTimeKind.Utc); // this clears up the offset
var offset = new DateTimeOffset(datetime); // so this line does not throw anymore
Console.WriteLine(offset); // 01-Jan-01 00:00:00 +00:00
```

https://github.com/sebastienros/fluid/blob/63bade9e14630f3bad98cda58e3885c0b4302e0b/Fluid/Values/FluidValue.cs#L170

Tests pass, I don't know if anything else would break conceptually.

**Comment by sebastienros** [comment]
Awesome, just submit the PR, with a comment on why the UTC is used in the ctor. Maybe check if we use the same TZ-less constructor somewhere else.

**Comment by hishamco** [comment]
@danielmpetrov seems you did some progress on this, to save the time for us I will stop working on this, and let you start a PR
