### ISSUE TITLE
First and last filters throw when passed an empty array

### ISSUE THREAD

**Issue by paynecrl97** [sebastienros/fluid#52]
This is because they use Linq's `First` and `Last` methods respectively.

I can't find any liquid documentation to say how this should be handled, so I'm guessing that it should return `NilValue`.

**Comment by hishamco** [comment]
I don't see how this handled in `Liquid` docs, but I think we should throw an `ArgumentNullException` instead of return `NilValue`, because `First` & `Last` should return the first or the last element in the array, but may be we can write an extension method that does what you did

/cc @sebastienros

**Comment by paynecrl97** [comment]
We should probably confirm how this works in liquid, but I chose to not throw for a couple of reasons:

* I don't think any tags, filters, or blocks should throw- because liquid is meant to be a safe templating language, and also because there is no way to handle exceptions in your template (e.g no try/catch to the best of my knowledge)
* Checking if the result of `first` is `Nil` is more succinct than checking if the array length > 0 before calling `first` (IMO, this is all subjective of course)

Regardless, we should be aiming to replicate liquid as closely as possible, so I'll try and find out how this is handled in liquid and post back once I have found the answer.

**Comment by hishamco** [comment]
I checked the source before I wrote my previous comment, but I didn't understand the null-ability check correctly, but after checking the docs that you refer to your PR LGTM

**Comment by hishamco** [comment]
@sebastienros if I look closely to https://apidock.com/ruby/Array/first, seems `first` work as `Top` in LINQ in some cases, can I handle this or shall we stay with what we have?

**Comment by paynecrl97** [comment]
The documentation you are referring to there is the documentation for the ruby method first, and not the liquid filter. 

The liquid filter first will only ever return one item (or nil).
