### ISSUE TITLE
How to use dynamicPartials?

### ISSUE THREAD

**Issue by last-Programmer** [sebastienros/fluid#521]
Do we have the option of using dynamicPartials?

like this 

`{% render {{partial}} with item %}`

where partial is a variable.

Thanks in advance.

**Comment by sebastienros** [comment]
I believe you can do this with the `{% include %}` tag, since `render` was introduced to prevent that. This was done in Shopify to allow for caching the templates. But then remove the `{{ ... }}` and just use the variable name directly.
