### ISSUE TITLE
ISO8601 with timezone string with date filter appears to use System time zone rather than defined TimeZone

### ISSUE THREAD

**Issue by nicholas-brooks** [sebastienros/fluid#537]
The following feels off to me, but not sure if this is the expected behaviour:

My Environment:

System time zone: Australian/Queensland (+10:00)

dotnet: 6
Fluid Version: 2.3.0

Code:

```csharp
var parser = new FluidParser();

var template = parser.Parse(@"The date is: {{ '2022-12-13T21:02:18.3991572+00:00' | date: ""%Y-%m-%d"" }}");

var context = new TemplateContext() { TimeZone = TimeZoneInfo.Utc };

Assert.Equal("The date is: 2022-12-13", template.Render(context));
```

This fails with the actual output being: `The date is: 2022-12-14`

Three interesting points:

1. This test passes when run from CI, as the CI system timezone is UTC.
2. When I leave off the "+00:00" from the timestamp (e.g. `2022-12-13T21:02:18.3991572`), the test passes.
3. I can also get this to pass by using the `time_zone` filter first like so: `The date is: {{ '2022-12-13T21:02:18.3991572+00:00' | time_zone: 'UTC' | date: "%Y-%m-%d" }}`

**Comment by sebastienros** [comment]
Without reading the issue I just want to say Fluid is probably doing the correct thing. Now, let me read the issue ;)

**Comment by sebastienros** [comment]
Wrote a failing unit test, progress is being made.

**Comment by sebastienros** [comment]
Got new test for you case and fixed it. Right now I only have one regression to fix. The rules are:
- When a TZ is provided in the source string, the resulting DateTimeOffset uses it
- When no TZ is provided, we assume the local offset (context.TimeZone)

Also the output is not influenced by the configured timezone.

**Comment by nicholas-brooks** [comment]
@sebastienros Awesome!  Thanks for the quick response!

**Comment by nicholas-brooks** [comment]
For future readers, I created a new filter called 'local_date' that always converts the ISO8601+time-offset to the time-zone defined by TemplateContext.TimeZone property:

```csharp

internal static class FluidFilters
{
    public static ValueTask<FluidValue> LocalDateFilter(FluidValue input, FilterArguments arguments, TemplateContext context)
    {
        var value = TimeZoneConverter(input, context);
        return ReferenceEquals(value, NilValue.Instance) ? value : MiscFilters.Date(value, arguments, context);
    }

    private static FluidValue TimeZoneConverter(FluidValue input, TemplateContext context)
    {
        if (!input.TryGetDateTimeInput(context, out var value))
        {
            return NilValue.Instance;
        }

        var result = TimeZoneInfo.ConvertTime(value, context.TimeZone);
        return new DateTimeValue(result);        
    }
}

```

And code to use the above:

```csharp
    [Theory]
    [InlineData("2022-12-07T22:22:18.1234-05:00")]
    [InlineData("2022-12-08T03:22:18.1234+00:00")]
    [InlineData("2022-12-08T05:22:18.1234+02:00")]
    [InlineData("2022-12-08T13:52:18.1234+10:30")]
    public void local_date_filter_should_convert_ISO8601_plus_offset_to_time_for_configured_TimeZone(
        string timestamp)
    {
        var templateOptions = new TemplateOptions
        {
            TimeZone = TimeZoneInfo.FindSystemTimeZoneById("Indian/Maldives"),
        };
        templateOptions.Filters.AddFilter("local_date", FluidFilters.LocalDateFilter);
        
        var parser = new FluidParser();
        var template = parser.Parse(@"Published at: {{ PublishedAt | local_date: ""%e %b %y %r"" }}");
        var result = template.Render(new TemplateContext(new {PublishedAt = timestamp}, templateOptions));

        Assert.Equal("Published at:  8 Dec 22 08:22:18 AM", result);
    }
```

**Comment by sebastienros** [comment]
@nicholas-brooks can you file an issue for that?

**Comment by nicholas-brooks** [comment]
@sebastienros I'd be happy to, though I'm tripping over the word 'issue'... you'd like me to file a ticket as a how-to/tip or as an actual issue to get fixed?

**Comment by sebastienros** [comment]
Yes, that's the common language on GitHub:

![image](https://user-images.githubusercontent.com/1165805/208767574-98353f02-bd97-44b5-8eb3-6e76f4ec6e58.png)
