### ISSUE TITLE
Passing parameters to a Liquid include file

### ISSUE THREAD

**Issue by AnthonySmith** [sebastienros/fluid#54]
The Shopify version of Liquid can pass parameters to an include file for rendering within it. It looks from running the latest version of Fluid that it does not yet support that feature.

`{% include 'snippet', my_variable: 'apples', my_other_variable: 'oranges' %}`

https://help.shopify.com/themes/liquid/tags/theme-tags#include

**Comment by hishamco** [comment]
This is already included, please refer to [this](https://github.com/sebastienros/fluid/blob/dev/Fluid/FluidGrammar.cs#L169-L171)

**Comment by sebastienros** [comment]
I just merged the dev branch into master, and a new version is available on nuget with this feature.

**Comment by AnthonySmith** [comment]
Great, thank you both for such a prompt reply and for your contributions. Fluid is shaping up to be a very valuable and performant library.
