### ISSUE TITLE
Nil and blank operator confusion

### ISSUE THREAD

**Issue by Adwelean** [sebastienros/fluid#550]
Hello,

Take this example :

```html
{% if Absence.AnimalOnSite != nil %}
<mj-group>
    <mj-column width="70%" padding="0 15px">
        <mj-text padding="0">
            {% if Absence.AnimalOnSite %}
            Animal présent sur site
            {% else %}
            Animal temporairement absent
            {% endif %}
        </mj-text>
    </mj-column>
</mj-group>
{% endif %}
```

If the 'AnimalOnSite' boolean of my 'Absence' object is not set, I would expect to have a value of `nil`.
However, it doesn't work, I have nothing... but if I use the `blank` operator instead of `nil` it works.

Is this a bug or a lack of interpretation? 

Note: 
- I use UnsafeMemberAccessStrategy
- A Dictionary<string, object> as parameter

Full code : https://dotnetfiddle.net/lHt8L6

@+

**Comment by sebastienros** [comment]
nil/blank/empty are weird, but the current implementation is very well tested based on Liquid's official behavior.

c.f. https://github.com/sebastienros/fluid/blob/de1fa859fe80affcf5e7594372d83376279e5056/Fluid.Tests/ParserTests.cs#L593-L687
