### ISSUE TITLE
Fluid parser does not accept valid object properties with Unicode characters `(Fluid.ParseException: end of tag '}}' was expected at xxx?)`

### ISSUE THREAD

**Issue by schittli** [sebastienros/fluid#557]
Good evening

This class is perfectly valid in C# (please note the german 'umlaut' **ü**):
```
public record class TeamMitglied {
   public string Kürzel   { get; set; }
   public string Vorname  { get; set; }
}
```

If the fluid parser has to parse this string: `… {{TeamMitglied.Kürzel}} …`
then it throws this exception:

```
"… {{TeamMitglied.Kürzel}} …"
                   ^
                   Fluid.ParseException: end of tag '}}' was expected
```

It would be great if fluid would accept the same characters as c# does for class- and property names 😊

Thanks a lot, kind regards,
Thomas

**Comment by sebastienros** [comment]
Maybe try `TeamMitglied["Kürzel"]` as a mitigation because these chars are not valid in liquid identifiers, you can check in Shopify and LiquidJs playgrounds:
- https://liquidjs.com/playground.html#eyUgIGFzc2lnbiBLdXJ6ZWwgPSAxMjMgJX0Ke3sgS3VyemVsIH19,e30=
- https://shopify.dev/docs/api/liquid (paste the same block in the samples)

**Comment by sebastienros** [comment]
Note that you might be able to customize the Parser though and change the character set that is used in identifiers. Fluid is very flexible in that matter.

**Comment by Oxana1989** [comment]
sebastienros, Hi
> Parser though and change the character set that is used in identifiers.

Sorry, maybe you have some example of how to do this. I've been trying to do this for several days now and it's not working for me.

I am very grateful if it is possible.

**Comment by sebastienros** [comment]
Identifiers are defined in `FluidParser` here: https://github.com/sebastienros/fluid/blob/main/Fluid/FluidParser.cs#L52

You can create a new class inheriting from it and replace how it's constructing, by creating a custom `IdentifierParser` that will take any unicode letter.

**Comment by Oxana1989** [comment]
Thank you for the very quick response. I did create my own class similar to the original one, but I do not know how to replace the existing one from my code, I do not know how and where to register it. I don't have enough experience to understand this. I will be very glad if you can give me another hint.
