### ISSUE TITLE
The object is transferred to json, and the reservation or escape character is passed in

### ISSUE THREAD

**Issue by huangyedie** [sebastienros/fluid#563]
![image](https://user-images.githubusercontent.com/51399090/224673426-289312c9-90d5-4e38-a6a4-74f3cdde37a7.png)

Whether object fields and values can be prefixed. For example:{"key":value} change {\"key\":\"value\"} or {\\\"key\\\":\\\"value\\\"}.Escape characters can be passed in

**Comment by sebastienros** [comment]
There is a `|json` filter for that
