### ISSUE TITLE
[Custom Block] How to access the value between start and end of the block?

### ISSUE THREAD

**Issue by dehghani-mehdi** [sebastienros/fluid#568]
For example:

```
{% foo %}
Hello
{% endfoo%}
```

```
parser.RegisterEmptyBlock("foo", (statements, writer, encoder, context) =>
{
    // how to access the value `Hello` here?
});
```

**Comment by hishamco** [comment]
Try

```csharp
return statements.RenderStatementsAsync(writer, encoder, context);
```

**Comment by dehghani-mehdi** [comment]
I want to access `Hello` inside `RegisterEmptyBlock`, I tried `var result = statements.RenderStatementsAsync(writer, encoder, context);` but that doesn't give me the `Hello`

**Comment by hishamco** [comment]
> Is the result equal to hello there? 

It depends, if your block does nothing the code below should work

> if not, you don't know what I am talking about, so please stop posting irrelevant comments

I know what I'm talking about, so be kind when you write your comments, what I mean in my [comment ](https://github.com/sebastienros/fluid/issues/568#issuecomment-1529797792) is the code will return the result after rendering 

```csharp
parser.RegisterEmptyBlock("hello", static (writer, encoder, context) =>
{
    return s.RenderStatementsAsync(writer, encoder, context);
});

var template = parser.Parse("{% foo %} hello {%- endfoo %}");
var result = template.Render();
```

The result should be `Hello`

**Comment by hishamco** [comment]
Please elaborate on what you are trying to do to avoid misunderstanding your question

**Comment by sebastienros** [comment]
Here is an example on how to use it. the block can contain "statements" that need to be processed. In your example it's a single Text Statement, but it could be another block, loops, ... You just need to process them all in order. Or evaluate them in a buffer and do something interesting with them.

https://github.com/sebastienros/fluid/blob/8564be1aa195c31fd9b160cd0cba170d1c4f2713/Fluid.Tests/Extensibility/ExtensibilityTests.cs#L62-L77

**Comment by dehghani-mehdi** [comment]
I don't why you didn't mention it, but the answer was `writer.ToString()`;

```
parser.RegisterEmptyBlock("foo", (statements, writer, encoder, context) =>
{
    var result = writer.ToString(); // result here the value `Hello`
    // manipulate result
    writer.Write(result);
    return Statement.Normal();
});
```

Thank you for the help.

**Comment by sebastienros** [comment]
No, this won't work as-is. You need to create a new Text Writer or you will get the results from everything else that was written from previous tags too.

> create a custom TextWriter

**Comment by dehghani-mehdi** [comment]
You are right, I used the following code:

```
_parser.RegisterEmptyBlock("foo", static (statements, writer, encoder, context) =>
{
	using (var sw = new StringWriter())
	{
		statements.RenderStatementsAsync(sw, encoder, context);
                var result = sw.ToString();
                // manipulate result
                writer.Write(result);
	}

	return Statement.Break();
});
```
