### ISSUE TITLE
Deep nested property values return empty string?

### ISSUE THREAD

**Issue by ptzedakis** [sebastienros/fluid#571]
Hi,
I pass an object with nested properties to my fluid template but it only renders the data in the scalar properties of type int, string, etc.

So, I have a data structure of a Product.ProductAttribute.KeyValuePair<string, ProductAttributeItemData> and I use the following code in my API endpoint to render my template:

            ...
            var parser = new FluidParser();
            string templateText = System.IO.File.ReadAllText(templateFilePath);
            var template = parser.Parse(templateText);

            TemplateOptions.Default.MemberAccessStrategy.Register<Product>();
            TemplateOptions.Default.MemberAccessStrategy.Register<ProductAttribute>();
            TemplateOptions.Default.MemberAccessStrategy.Register<ProductAttributeItemData>();

            foreach (var product in products)
            {
                Console.WriteLine(product.URL);
                Console.WriteLine(product.Name.AttributeInfo.Value.AttributeValueAsText);

                var context = new TemplateContext(product);
                context.SetValue("product", product);

                var renderedProductInfoFileContents = await template.RenderAsync(context);
            }
            ...

The template contains the following two lines:

- {{ product.URL }}
- {{ product.PackH.AttributeInfo.Value.AttributeFriendlyName }}: {{ product.PackH.AttributeInfo.Value.AttributeValueAsText }} 

The product.URL gets displayed, however the second line with the nested object properties does not display the stored value.

What am I missing ?
Thank you,
P.

**Comment by sebastienros** [comment]
You need to "Register" any property or class that you want to access. If you pass a model it is registered automatically, but not it's sub-properties.

**Comment by sebastienros** [comment]
Or use another MemberAccessStrategy that doesn't check for registered properties and allows anything to be accessed.

**Comment by sebastienros** [comment]
https://github.com/sebastienros/fluid#allow-listing-object-members
