### ISSUE TITLE
TemplateOptions.Now usage

### ISSUE THREAD

**Issue by mukaofssn** [sebastienros/fluid#572]
Hello,
Does TemplateOptions.Now dictate how "now" should work? Tried the following in the code:
```       
        var options = new TemplateOptions
        {
            Now = () => DateTimeOffset.UtcNow,
            TimeZone = TimeZoneInfo.FindSystemTimeZoneById("Europe/London")
        };
```

and tried using it like `{{ now | add_days: 3 }}` where `add_days` is a custom filter which is used to increment the date passed in.
However, when the control went to the filter logic, it is seen that "now" wasn't converted to a date/time format.

**Comment by sebastienros** [comment]
It's `"now"` not `now`. And this won't work with all filters, is up to you to handle that the input of your for is this strong to call `Now` from the options. You can check the source code of the`date` for as an example.

**Comment by mukaofssn** [comment]
Thanks @sebastienros, thanks, we do specify as "now" (was a typo in the above example). I will check out the filter you have specified.

**Comment by sebastienros** [comment]
Also https://stackoverflow.com/questions/39730058/adding-days-to-a-date-excluding-weekends-in-shopify#39730626

**Comment by mukaofssn** [comment]
@sebastienros is it mandatory to call a filter in order to realise the value of 'now'? Would RenderAsync work if we pass in {{ 'now' }}  as the template?
