### ISSUE TITLE
Question: Multiple arguments/parameters for tag

### ISSUE THREAD

**Issue by knightmeister** [sebastienros/fluid#574]
I'm evaluating moving our home grown templating solution to Fluid; I've checked off all our requirements, the only remaining thing for me to figure out to port is supporting multiple parameters/arguments for a tag.

Our existing homegrown CMS does, and we use it for example to import sections of a document, the format would be something like

```
{% article 'articleid' sections:'1,2,3' heading:'This is my title' %}
```

I got the first part (articleid) by creating an identifier tag. I don't need to bind to the template context for my use case, just pass through primitive values. But I need to be able to pass in additional values, ideally ones that are named just so the intent is clear.  

Is this possible with Fluid?

Thanks in advance.

**Comment by sebastienros** [comment]
Look at this paragraph which explain how to provide custom syntaxes for tags https://github.com/sebastienros/fluid#custom-parsers

Fluid provide only a few out of the box methods for most common case, and this one for very custom arguments. And with it this can be anything you want.

Here are some examples (in OrchardCore and Squidex) https://grep.app/search?q=RegisterParserTag

**Comment by sebastienros** [comment]
The one with ArgumentsList parser is probably what you need.

**Comment by knightmeister** [comment]
@sebastienros thanks heaps, exactly what I was after
