### ISSUE TITLE
Question: Introspection of parsed template

### ISSUE THREAD

**Issue by knightmeister** [sebastienros/fluid#578]
Is it possible to introspect tags within a parsed template?

I know that `FluidTemplate` contains a list of `Statement`s but I don't see a way of viewing the tag name and arguments.

What I'm trying to do is look at the layout being used when rendering to do some things before giving it to Fluid to render.

i.e. 
```
{% layout "mylayout.liquid" %}
```

I would like to be able to find the tag that is specific for `layout` and then get the value `mylayout.liquid` from that tag.

Thanks :)

**Comment by sebastienros** [comment]
Exactly what I am doing in a different branch, but tied to a specific feature so won't be merged soon.

When you have the list of Statements, try to find the implementation :

This tag is coming from [here](https://github.com/sebastienros/fluid/blob/8564be1aa195c31fd9b160cd0cba170d1c4f2713/Fluid.ViewEngine/FluidViewParser.cs#L73)

I believe you are now familiar of what this code does. The issue that I am seeing is that it ultimately calls into https://github.com/sebastienros/fluid/blob/8564be1aa195c31fd9b160cd0cba170d1c4f2713/Fluid/FluidParser.cs#L548 and I see that the tag name is not kept in the statement node, so you would not be able to find "layout" among all the statements of type `ParserTagStatement`. I could suggest that you customize the `FluidViewParser` instance by calling `RegisterExpressionTag("layout", ...` again but returning a Statement type that would have the name of the tag in it.

Or, you could submit a PR that add the tag information to the current class (maybe event `Statement`) and you wouldn't have to do something custom in your own code. I think this would be a good addition.

**Comment by knightmeister** [comment]
Appreciate the reply. I'm happy to have a crack at doing a PR for `Statement.cs` to add the name. Will let you know how I go.

**Comment by knightmeister** [comment]
PR submitted for review

**Comment by MithrilMan** [comment]
> Exactly what I am doing in a different branch, but tied to a specific feature so won't be merged soon.

@sebastienros 
Is it maybe something related to the issue I opened here? https://github.com/sebastienros/fluid/issues/580

I was trying to understand the best approach to solve my problem and I thought that maybe I should use a custom parser tag but if you are working on a similar feature or something that could help solve my problem I could wait or fork your branch. But I can't find an updated branch so maybe it's private?

**Comment by knightmeister** [comment]
@MithrilMan I have a PR open for this here https://github.com/sebastienros/fluid/pull/579
@sebastienros have you had a chance to look at my approach, if so any feedback is welcome.

**Comment by sebastienros** [comment]
I have finally added visitors, [here is the PR](https://github.com/sebastienros/fluid/pull/650). Please check the README for usage examples and let me know if that will work for you.

**Comment by sebastienros** [comment]
I am closing as the feature has shipped
