### ISSUE TITLE
Register JObject no work

### ISSUE THREAD

**Issue by atliuhui** [sebastienros/fluid#58]
```csharp
var expression = "{{ Context.User }}";
//var expression = "{{ Context.User.Name }}";
var data = JObject.Parse("{\"User\": \"Bill\"}");
//var data = JObject.Parse("{\"User\": {\"Name\": \"Bill\"}}");

TemplateContext.GlobalMemberAccessStrategy.Register<JObject>((source, name) => source[name]);

FluidTemplate template = null;
if (FluidTemplate.TryParse(expression, out template))
{
    var context = new TemplateContext();
    context.SetValue("Context", data);

    var text = template.Render(context);

    Console.WriteLine(text);
}
```
```xml
<package id="Fluid.Core" version="1.0.0-beta-9422" targetFramework="net461" />
```

**Comment by sebastienros** [comment]
You need to tune the member access strategy to allow for the properties to be navigated. It's secure by default.

Something like this:

```
            // When accessing a property of a JObject instance
            TemplateContext.GlobalMemberAccessStrategy.Register<JObject>((obj, name) => obj[name]);

            // Prevent JTokens from being converted to an ArrayValue as they implement IEnumerable
            FluidValue.TypeMappings.Add(typeof(JObject), o => new ObjectValue(o));
            FluidValue.TypeMappings.Add(typeof(JValue), o => FluidValue.Create(((JValue)o).Value));
```

**Comment by sebastienros** [comment]
Sorry, I didn't see you had already tried it ...

**Comment by atliuhui** [comment]
```csharp
var expression = "{{ Context.User }}";
//var expression = "{{ Context.User.Name }}";
var data = JObject.Parse("{\"User\": \"Bill\"}");
//var data = JObject.Parse("{\"User\": {\"Name\": \"Bill\"}}");

TemplateContext.GlobalMemberAccessStrategy.Register<JObject>((source, name) => source[name]);

FluidValue.TypeMappings.Add(typeof(JObject), o => new ObjectValue(o));
FluidValue.TypeMappings.Add(typeof(JValue), o => FluidValue.Create(((JValue)o).Value));

FluidTemplate template = null;
if (FluidTemplate.TryParse(expression, out template))
{
    var context = new TemplateContext();
    context.SetValue("Context", data);

    var text = template.Render(context);

    Console.WriteLine(text);
}
```
this is ok！

**Comment by sebastienros** [comment]
I added a new section in the readme https://github.com/sebastienros/fluid/blob/dev/README.md#using-jsonnet-object-in-models

**Comment by sjd2021** [comment]
> I added a new section in the readme https://github.com/sebastienros/fluid/blob/dev/README.md#using-jsonnet-object-in-models

I no longer see a reference to jobject in the readme. I need a way to use this library dynamically. It's only used by internal applications, and I need them to be able to send over any model they'd like. Using JObject..FromObject(x) is the only thing I can think of that would make this work the way that I need it to given the tight restrictions in the library.

**Comment by sebastienros** [comment]
It's not in the README anymore because it now handles such object by default. It doesn't need to be registered manually. Same with Dictionaries. Please try it and file an issue if you think it's not working as expected.

Example unit test: https://github.com/sebastienros/fluid/blob/b370f3ed8df07a8966fac357eef8b0f819ec42e7/Fluid.Tests/MemberAccessStrategyTests.cs#L117-L132

**Comment by sjd2021** [comment]
Thank you @sebastienros  
It works great!
