### ISSUE TITLE
Fluid.Tags compatibility method after upgrading to a new version

### ISSUE THREAD

**Issue by wangsidong177** [sebastienros/fluid#583]
Hi Team,

I used Fluid.Tags earlier and currently upgraded to. Net6. 
I need to upgrade Fluid as well. I am currently using the latest version 2.4.0. 
But after the update, I found that Fluid.Tags is no longer available for use. 
Is there any way to be compatible with the Fluid.Tags method I used before?

Here is my previous code:

`public class TokenTag : SimpleTag
    {
        public override async ValueTask<Completion> WriteToAsync(TextWriter writer, TextEncoder encoder, TemplateContext context)
        {
            ...
            return Completion.Normal;
        }
    }`

**Comment by sebastienros** [comment]
The documentation in the README explains how to create custom tags, have you checked it?
