### ISSUE TITLE
Question: Update underlying Liquid version

### ISSUE THREAD

**Issue by caspertl** [sebastienros/fluid#584]
Hi!

Thanks for a great framework 👍 

Is it possible to update the underlying Liquid version?

Filters like "sum" (https://shopify.github.io/liquid/filters/sum/) does not exist in the current Fluid 2.4.0. In the meantime i've implemented my own sum filter - but it would be nice to have the newest filters and features of Liquid (5.4.0 currently).

**Comment by hishamco** [comment]
Feel free to submit a PR

**Comment by sebastienros** [comment]
Filter `sum` added by https://github.com/sebastienros/fluid/pull/618
