### ISSUE TITLE
Layout support doesn't seem to work in 2.4.0

### ISSUE THREAD

**Issue by sjd2021** [sebastienros/fluid#585]
We're receiving this error every time we try to parse any template that uses a layout file:

`Unknown tag 'layout' at (1:40))`

Snippet:

![image](https://github.com/sebastienros/fluid/assets/84007094/c38dd0c5-cd2d-4649-a7e0-57ecf0535ade)

(I've also tried it with double quotes, dropping the .liquid extension, etc.)

Interestingly enough, the `render` tag works just fine in the regular liquid files (non-layouts) even though the fluid-specific documentation does not directly mention it. It only mentions `renderbody`, `rendersection`, etc.(?). For now, we are getting by with adding sections to every template. But layouts would be ideal.

**Comment by sebastienros** [comment]
The layout tag is only available in the ViewEngine project, are you using it? The default Liquid tags don't have it, this notion of layout and section is extra and opt-in. Try to use `FluidViewParser` instead of `FluidParser`.

**Comment by sebastienros** [comment]
Check which file provider is used in the options, like what is the root folder, and if the paths are correct relatively to each other.

**Comment by sebastienros** [comment]
Had to look at the tests, but here is how it's done. Note that you are using custom folders so I rooted all the file providers.

```c#
// See https://aka.ms/new-console-template for more information

using Fluid;
using Fluid.ViewEngine;
using Microsoft.Extensions.FileProviders;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Serialization;

var serializer = JsonSerializer.CreateDefault(new JsonSerializerSettings
{
    ContractResolver = new CamelCasePropertyNamesContractResolver(),
    ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
    NullValueHandling = NullValueHandling.Include,
    TypeNameHandling = TypeNameHandling.None
});

var options = CreateFluidViewEngineOptions();

var renderer = new FluidViewRenderer(options);

var model = new MyModel(55, "Howdy");

var ctx = new TemplateContext(JObject.FromObject(model, serializer), options.TemplateOptions);

await using var sw = new StringWriter();
await renderer.RenderViewAsync(sw, "raw.liquid", ctx);

Console.WriteLine(sw.ToString());

static FluidViewEngineOptions CreateFluidViewEngineOptions()
{
    var options = new FluidViewEngineOptions();
    options.ViewsFileProvider = new PhysicalFileProvider(AppContext.BaseDirectory);
    options.PartialsFileProvider = new PhysicalFileProvider(AppContext.BaseDirectory);
    options.TemplateOptions.ValueConverters.Add(value => value is JValue { Type: JTokenType.Boolean } v ? (bool?)v.Value : null);
    options.TemplateOptions.MemberAccessStrategy.IgnoreCasing = true;
    options.TemplateOptions.FileProvider = new PhysicalFileProvider(AppContext.BaseDirectory);
    return options;
}

record MyModel(int PropertyA, string PropertyB);
```

Also you are using a Json document, which would be unnecessary here, you can pass a `MyModel` instance directly. And maybe use `System.Text.Json` instead of `NewtonSoft`, that would make one less dependency.

**Comment by sebastienros** [comment]
You can use in-memory file providers. The tests use one for instance. And then you can use CompositeFileProvider if you need to have snippets come from different sources at the same time.

**Comment by sebastienros** [comment]
That's exactly how it's working, all good.
There is a special filter otherwise like `@Html.Raw` which is `{{ value | raw }}` so the output is not encoded if you want to keep the default html encoder for security reasons. There is also a tag: `{% raw %} ... {% endraw %}`. This is explained in the README.

**Comment by AhmadAlMunajjed** [comment]
Hi @sjd2021, can you share sample of what have you do getting templates/layouts from external sources like database or file storage 

Did you need to cache it for performance?

Thanks!
