### ISSUE TITLE
Hope size supports null

### ISSUE THREAD

**Issue by huangyedie** [sebastienros/fluid#587]
![image](https://github.com/sebastienros/fluid/assets/51399090/b935d4cb-dbc2-4e18-8214-082c4561b316)

{% assign username = null -%}

Hope to return
username.size return 0

**Comment by hishamco** [comment]
I try it in https://tryliquid.dev/ but It doesn't return 0

**Comment by sebastienros** [comment]
From shopify's implementation:

![image](https://github.com/user-attachments/assets/5ae0a5d7-ced0-4b20-992d-b33cc834fc22)

**Comment by huangyedie** [comment]
> From shopify's implementation:
> 
> ![image](https://private-user-images.githubusercontent.com/1165805/362975051-5ae0a5d7-ced0-4b20-992d-b33cc834fc22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5ODM2MTksIm5iZiI6MTcyNDk4MzMxOSwicGF0aCI6Ii8xMTY1ODA1LzM2Mjk3NTA1MS01YWUwYTVkNy1jZWQwLTRiMjAtOTkyZC1iMzNjYzgzNGZjMjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzBUMDIwMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTc5YzYyZjg1ODMxZjcxYjE1MjQ1ODEzZTFmNTdjMmNhMWQ3YzhjNGM4ZDk0MDJiZTYzNDkyMTNlYTNjZDY0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FKLAW1X1ahf8M9YEUxHfDexHckoX4tKeEOAi95S_3tU)

The problem from last year has been resolved. Suggest creating a group chat to facilitate quick response to questions
