### ISSUE TITLE
Missing fluid compatibilty table and roadmap

### ISSUE THREAD

**Issue by ericis** [sebastienros/fluid#588]
Can this project list compatibility with the Fluid definition? Is there a "Label" on issues that track open issues?

Example: The [Rust "liquid" crate](https://crates.io/crates/liquid) explicitly calls out conformance with the Liquid definition.

> Goals:
> Conformant. Incompatibilities with [strict shopify/liquid](https://github.com/Shopify/liquid) are [bugs to be fixed](https://github.com/cobalt-org/liquid-rust/labels/shopify-compatibility).

**Comment by sebastienros** [comment]
I can create a label, that would be useful for people investigating the compatibility.
FYI the goal is to be as conformant to the ruby implementation as closely as possible, even with the weirdest things (empty values, boolean comparisons, ...). So if you know of any discrepancy you are welcome filing bugs.

I personally use the Shopify dev website to check the behavior of the official APIs. They have editable code editors to try it.

Note that I will also file bugs in https://liquidjs.com/ when I find issues in Fluid.
