### ISSUE TITLE
Fluid prints nothing inside for ..in loop

### ISSUE THREAD

**Issue by lafasta** [sebastienros/fluid#592]
Hello,

I can render and print normally outside a loop, but inside a loop, I get the html structure repeated by the loop and by a number of times equals the number of items in the collection, but fluid replaced {{itemLine.Name}} with nothing.

I've spent hours already searching and trying to find out the reason but I had no luck .... 

Please check the attached photos for better understanding. 
Thanks in advance 

![fluid](https://github.com/sebastienros/fluid/assets/88973424/0a3d810a-78bc-4c9c-bcae-2d1933dd5527)

**Comment by sebastienros** [comment]
You need to register the types of the models you want to bind.

See doc here: https://github.com/sebastienros/fluid#allow-listing-a-specific-type

**Comment by lafasta** [comment]
Thanks, that resolved the issue. ☺♥
