### ISSUE TITLE
Support for Roslyn Source Generators

### ISSUE THREAD

**Issue by Xemrox** [sebastienros/fluid#610]
Projects like [Scriban](https://github.com/scriban/scriban) support the somewhat awkward environment of roslyn code generators through direct source linking/embedding.

See [Source Embedding](https://github.com/scriban/scriban?tab=readme-ov-file#source-embedding).

Is there any way to get fluid.core working with source generators?
Maybe enable the _same_ mechanism as scriban uses for fluid?

**Comment by sebastienros** [comment]
> Working with source generators

As in being able to use Fluid from a source generator?

This doc seems to explain how to do that, have you tried it?

https://github.com/dotnet/roslyn/blob/main/docs/features/source-generators.cookbook.md#use-functionality-from-nuget-packages

**Comment by mo3in** [comment]
not working ...

**Comment by lahma** [comment]
[Here's an example of of a source generator project](https://github.com/lahma/jint/blob/source-gen/Jint.SourceGenerators/Jint.SourceGenerators.csproj) utilizing Fluid as template engine.
