### ISSUE TITLE
How to write to call the test function

### ISSUE THREAD

**Issue by huangyedie** [sebastienros/fluid#619]
![image](https://github.com/sebastienros/fluid/assets/51399090/c7fc9dce-c8f7-47be-bf06-688a88016a5d)
![image](https://github.com/sebastienros/fluid/assets/51399090/e16bbe29-2fc5-4aa6-9dc4-b4432a966a35)

I want to call the test function instead of concatenating

How to write to call the test function?

**Comment by huangyedie** [comment]
![image](https://github.com/sebastienros/fluid/assets/51399090/cc863617-4733-4da5-9077-2f49efbd9bda)

Ceshi函数。

The result I want is Q E 666.

**Comment by huangyedie** [comment]
@sebastienros

**Comment by huangyedie** [comment]
The parameter called to test is Q E

**Comment by huangyedie** [comment]
![image](https://github.com/sebastienros/fluid/assets/51399090/69a18559-a777-4e7c-9ca0-13040dd53b96)
I have come up with the method of using append to meet this requirement. If there is a better solution, please provide guidance

**Comment by sebastienros** [comment]
```
{% assign v = QQQ | append: ' ' | append: EEE %}
{{ q | test }}
```
