### ISSUE TITLE
upgrade to standard2.0

### ISSUE THREAD

**Issue by eddyjl077** [sebastienros/fluid#62]
Please upgrade to 2.0

<TargetFramework>netstandard2.0</TargetFramework>

**Comment by hishamco** [comment]
Do we still need to target netstandard2.0 for any reason?

Please refer to this PR #27

**Comment by eddyjl077** [comment]
No, if there are no improvement in the performance or bug fixes, you right,
we shouldnt do it for no reason.

Thank you.
