### ISSUE TITLE
Loop template can't rendering

### ISSUE THREAD

**Issue by DKhangHa** [sebastienros/fluid#624]
I wrote this code based on your read-me file but it couldn't render data of the property of each object in list.
Please help me if I have any syntax problems.
![image](https://github.com/sebastienros/fluid/assets/149549291/f63e57a3-d997-4b4e-a81b-a0220bd75f8d)

**Comment by sebastienros** [comment]
You need to register the type Test. It's explained in the doc.

**Comment by DKhangHa** [comment]
Thank you! That helps me a lot.

**Comment by sebastienros** [comment]
🎉
