### ISSUE TITLE
allow to use view location expanders

### ISSUE THREAD

**Issue by eddyjl077** [sebastienros/fluid#63]

**Comment by hishamco** [comment]
For which reason?

**Comment by eddyjl077** [comment]
I  would like to be able configure the path of my views per tenant.

Is it already feasable?

**Comment by hishamco** [comment]
I already did something similar in [Bloggy](https://github.com/hishamco/bloggy) to configure the path of my views per theme

@sebastienros your thoughts to implement such thing in OrchardCore

**Comment by eddyjl077** [comment]
yes, it would be nice if this feature becomes part of this view engine.
