### ISSUE TITLE
After upgrading to 2.8.0 My durable function would no longer start.

### ISSUE THREAD

**Issue by well0549** [sebastienros/fluid#642]
After Switching  to 2.8.0 i got an error and my durable function would no longer start. I got an error:

Microsoft.Azure.WebJobs.Extensions.Rpc: Method 'GetChangeToken' in type 'Microsoft.Azure.WebJobs.Extensions.Rpc.ExtensionEndpointDataSource' from assembly 'Microsoft.Azure.WebJobs.Extensions.Rpc, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation. Value cannot be null. (Parameter 'provider')

Switching back to 2.7.0 solved the problem.

It's a durable function using .net core 60. (32 Bit)

I read somewhere it's because of the the SDK but could not find the info anymore

**Comment by sebastienros** [comment]
It's possible that an updated assembly reference is pulling a different version of `Microsoft.Azure.WebJobs.Extensions.Rpc`. Can you check which one you get before you upgrade Fluid, and then add an explicit reference to this version in your project to force it? However this would also mean that you are potentially using unsecure versions and should upgrade.

**Comment by well0549** [comment]
The exact error was : Microsoft.Azure.WebJobs.Script: Error configuring services in an external startup class. Microsoft.Azure.WebJobs.Extensions.Rpc: Method 'GetChangeToken' in type 'Microsoft.Azure.WebJobs.Extensions.Rpc.ExtensionEndpointDataSource' from assembly 'Microsoft.Azure.WebJobs.Extensions.Rpc, Version=3.0.37.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.

**Comment by well0549** [comment]
added package  Microsoft.Azure.WebJobs.Extensions.Rpc but thjat did not help. Function was still stuck in the warmup. 
Not really important probably fixed when i switch to .net8 isolated
