### ISSUE TITLE
Directory.Packages.props does not respect PrivateAssets

### ISSUE THREAD

**Issue by kaqq** [sebastienros/fluid#646]
https://github.com/sebastienros/fluid/compare/v2.7.0...v2.8.0#diff-5baf5f9e448ad54ab25a091adee0da05d4d228481c9200518fcb1b53a65d4156R10
version 2.8.0 results in all packages marked as PrivateAssets being included anyway. 

proposed fix: https://github.com/sebastienros/fluid/pull/645

**Comment by sebastienros** [comment]
> Directory.Packages.props does not respect PrivateAssets

Where do you get that from? I had the impression it was supported (from documentation and other example in dotnet repositories), and it's working on another project I maintain.

Now will check on Fluid though, maybe it's not working here for some other reason.

**Comment by lahma** [comment]
I think `PrivateAssets` needs to be defined in csproj if it's not a `GlobalPackageReference`, `Directory.Build.props` only guides versions as different projects could want/need different behavior for `PrivateAssets`.

**Comment by sebastienros** [comment]
I can't even get anything to be copied in the output folder, what am I doing wrong ;)

**Comment by lahma** [comment]
You should check the produced `.nuspec` inside the `.nupkg`, what are the actual dependencies. NuGet Package Explorer is great for that.

**Comment by kaqq** [comment]
I discovered this because I got PolySharp codegen output after updating to 2.8.0
![image](https://github.com/sebastienros/fluid/assets/58994315/d8d6b374-73d0-45c8-9cd8-008d473862a8)
vs 
![image](https://github.com/sebastienros/fluid/assets/58994315/b68e7be4-e6b1-468d-bb05-1e09d29127d0)

**Comment by sebastienros** [comment]
I was testing with a mix of dotnet tools and source code analyzer libraries, and then a build that was not copying all dependencies in the bin. Now I can see this, thanks. Then I tried with Fluid and it just worked as you explained it, thanks!
