### ISSUE TITLE
Listing in readme -  Used By section ?

### ISSUE THREAD

**Issue by simenums** [sebastienros/fluid#659]
- [Weavo Liquid Loom](https://www.weavo.dev) A Liquid Template generator/editor + corresponding Azure Logic Apps Connector / Microsoft Power Automate Connector

Fluid, what a great library! 

best regards
Simen Bøhmer, Weavo.Net

**Comment by sebastienros** [comment]
Do you want to create a PR for that?

**Comment by simenums** [comment]
Yes, of course. https://github.com/sebastienros/fluid/pull/660
