### ISSUE TITLE
System.MissingMethodException: Method not found: 'Parlot.Fluent.Parser`1 Parlot.Fluent.Parsers.AndSkip

### ISSUE THREAD

**Issue by gumbarros** [sebastienros/fluid#677]
When running Fluid with a project that also have Parlot has a transitive dependency the following exception happens.

**Comment by gumbarros** [comment]
![image](https://github.com/sebastienros/fluid/assets/52143624/8bce33d1-da68-4e2e-bad6-ed8d622d464d)
Probably just a new NuGet publish is needed, because the latest version uses Parlot v25 and Parlot is at v28.

**Comment by gumbarros** [comment]
@sebastienros sorry for the ping, but can you publish a new NuGet version? I'm in the middle of a project and really need to use Fluid.

**Comment by sebastienros** [comment]
Published 2.11.0 with Parlot 1.0.0
