### ISSUE TITLE
Create a DocFX or similar doc website

### ISSUE THREAD

**Issue by gumbarros** [sebastienros/fluid#682]
My co-workers that never writed Liquid templates asked about a doc of Fluid with examples on how to write `if`, `for` etc and were a bit disapointed when they saw just a README.md. An DocFX website hosted at GitHub pages [like the NCalc one](https://ncalc.github.io/ncalc/articles/index.html) would be great.

**Comment by sebastienros** [comment]
I personally rely on the Shopuify's official documentation which is very complete. All the filters are behaving the same, and it's assumed a bug if not. The README also points to some very good documentation written by Deane Barker.
