### ISSUE TITLE
Does Fluid support special characters?

### ISSUE THREAD

**Issue by KnightMollo** [sebastienros/fluid#688]
Hi folks.
I have some °C in the sub template liquid file, and I include it from the base template liquid file. But the string output only shows �C. Similar thing for ‘’ and –. I want to check if it's related with encoder in Fluid engine but failed to find anything related. Is there a way to set it to have the expected output? 
Thanks.

**Comment by sebastienros** [comment]
Is that an issue only with include/render tag?

**Comment by KnightMollo** [comment]
No I don't think so. It's the content in another liquid file included in the base template. For example,
base.liquid
some content. {% include subtemplate %}
subtemplate.liquid
Today's temperature is 20 °C.

Then the output looks like
some content. Today's temperature is 20 �C.

**Comment by KnightMollo** [comment]
Update: I think I find the root cause. It has nothing to do with Fluid engine. The original liquid file was somehow not saved as Unicode. Sorry for the confusion.
