### ISSUE TITLE
Parsing error when encountering numeric property used for indexer

### ISSUE THREAD

**Issue by dustinburson** [sebastienros/fluid#700]
Hello!

I am one of the maintainers of the repository https://github.com/microsoft/FHIR-Converter which uses Liquid templates to convert data from one healthcare standard (Hl7v2, CCDA) to another (FHIR).  The engine is currently based on DotLiquid and I am doing an investigation on potential performance improvements of switching the engine over to Fluid.

One issue I have hit is the data model the Hl7 message is loaded into uses string and numeric indexers.  One example is below where **MSH** is the string indexer and **10** is the numeric indexer.

`{{ firstSegments.MSH.10.Value }}`

For the string indexers I have been able to build an adapter using the `IFluidIndexable` interface but since the numeric indexer is failing at the template parser, I haven't been able to find a solution.

I have a few work arounds, but they all require modifying the template content in some way which I am trying to avoid.

My questions are:
- Is accessing a numeric indexer on a class like in the example above supported but I am doing something incorrect?
- If not is there a recommend way to override the parser for this specific case?
- If the above is not possible, is this something you would consider supporting in the project and take a contribution for?

Thank you!

**Comment by sebastienros** [comment]
Quick thought before I look deeper, have you tried the indexer syntax like `MSH[10]` or `MSH["10"]` ?
