### ISSUE TITLE
Can you use fluid in .cshtml files?

### ISSUE THREAD

**Issue by Xliff** [sebastienros/fluid#71]
I would like to use Fluid templates in simple .cshtml files (as an alternative to Razor, ideally). Is this possible?

**Comment by hishamco** [comment]
I'm not sure why you need to mix both?!!

**Comment by Xliff** [comment]
Actually, I was hoping to use the Liquid sintax in the .cshtml instead of Razor, but I do see your point.

**Comment by sebastienros** [comment]
You can use the view engine for MVC as described in the readme, and use both .liquid and .cshtml in the same app. But you shouldn't try to have Liquid inside a cshtml file.
