### ISSUE TITLE
Why use TryParse on a template?

### ISSUE THREAD

**Issue by deanebarker** [sebastienros/fluid#730]
I see this in tests:

```
_parser.TryParse(source, out var template, out var error);
```

What's the benefit of doing this, rather than just using `Parse` and handling the exception via `try...catch`?

**Comment by sebastienros** [comment]
Not having to depend on exceptions to detect something is wrong. And this could do some sanity checks and know that it's a wrong template even before entering an exception itself.

Same logic for the `int.Parse()` and `int.TryParse()`. Exceptions are expensive, if there are ways to not throw them then it's better.

**Comment by deanebarker** [comment]
But wouldn't I have to throw an exception here anyway? A template being non-parsable is an existential event. It's not like I can error-correct around it.
