### ISSUE TITLE
Upgrading to Microsoft.Extensions.FileProviders.Abstractions v.2.1.1.0 breaks fluid

### ISSUE THREAD

**Issue by sereeth** [sebastienros/fluid#76]
We upgraded our standard libraries all up to 2.1.1.0, after doing so fluid wouldn't work and was throwing the following:

----> System.TypeInitializationException : The type initializer for 'Fluid.TemplateContext' threw an exception.
 ----> System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Extensions.FileProviders.Abstractions, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by hishamco** [comment]
You are right, because the Fluid uses version `1.1.1` as shown [here](https://github.com/sebastienros/fluid/blob/dev/Fluid/Fluid.csproj#L10), @sebastienros can we upgrade to 2.1 and target netstandard2.0?

**Comment by sebastienros** [comment]
Did you just copy paste the Fluid dll or actually recompiled the application? The dependencies file should automatically take the latest one and not require 1.1.1. This works fine in OrchardCore for instance, which is also using 2.1.1.
