### ISSUE TITLE
Examples or nuget are broken

### ISSUE THREAD

**Issue by byme8** [sebastienros/fluid#8]
I installed latest nuget, copy-paste the example and it fails to compile. "Register" method is absent. Also as I understand to template.Render() should be passed context, but it just my guess.

**Comment by sebastienros** [comment]
Can you give me the exact sample you are trying?

**Comment by sebastienros** [comment]
All the `Register` methods are on this class: https://github.com/sebastienros/fluid/blob/d7a92d4c9fbefb7fd6e26708069d4149bb999e06/Fluid/IMemberAccessStrategy.cs mostly as extension methods. So have the `using Fluid;` statement in your code should be sufficient to make it work.

**Comment by byme8** [comment]
![image](https://user-images.githubusercontent.com/5927686/27396106-c6f97ed0-56ba-11e7-82b8-ca2182534f75.png)

**Comment by byme8** [comment]
Next code works as expected:
```
var model = new { Firstname = "Bill", Lastname = "Gates" };
var source = "Hello {{ p.Firstname }} {{ p.Lastname }}";
if (FluidTemplate.TryParse(source, out var template))
{
     var context = new TemplateContext();
     context.MemberAccessStrategy.Register(model.GetType());
     context.SetValue("p", model);
      var result = template.Render(context);
}
```

**Comment by sebastienros** [comment]
Ok, the `Render` is definitely missing the context parameter probably, `template.Render()` should be `template.Render(context)`

And for the `Register`, it's missing the `MemberAccessStrategy`, fixing it right now.
