### ISSUE TITLE
TemplateContext.GlobalMemberAccessStrategy.Register<JObject>((source, name) => source[name]); throws  Error

### ISSUE THREAD

**Issue by quasipolynomial** [sebastienros/fluid#82]
```
using Fluid;
using Fluid.Values;
using Newtonsoft.Json.Linq;
...
TemplateContext.GlobalMemberAccessStrategy.Register<JObject>((source, name) => source[name]);
```

throws

`CS1660 C# Cannot convert lambda expression to type 'string' because it is not a delegate type`

**Comment by hishamco** [comment]
Seems you are using a wrong signature, I didn't see an extension method similar to what you are using above?!! Could you please refer to what the extension that you are using?

**Comment by quasipolynomial** [comment]
Source doesn't have the required signature and link is https://www.nuget.org/packages/Fluid.Core/1.0.0-beta-9446

**Comment by hishamco** [comment]
I think it should be
```csharp
TemplateContext.GlobalMemberAccessStrategy.Register<JObject, object>((source, name) => source[name]);
```
/cc @sebastienros

**Comment by tgrandgent** [comment]
This public API was changed in f478f9901ad632e88611fb0d10ebea69341318c0.  README.md should be updated to reflect this.
