### ISSUE TITLE
Custom tags via AddMvc?

### ISSUE THREAD

**Issue by tylersticka** [sebastienros/fluid#86]
Apologies in advance for what is probably a dumb question, I'm working with a client on a .NET Core MVC project for the first time and trying to provide a bit of guidance.

We have a project right now that's set up very similarly to the [Fluid.MvcSample](https://github.com/sebastienros/fluid/tree/dev/Fluid.MvcSample).

We have one custom filter and one custom tag we'd like to add. The filter was super easy, but we're having trouble with the tag.

There's a step that involves [defining a new template type](https://github.com/sebastienros/fluid#defining-a-new-template-type). But we aren't currently calling `TryParse` anywhere... we're calling `services.AddMvc().AddFluid()` from `Startup.cs`.

Is there a simple example available of registering a custom tag in an MVC project?

Thanks in advance for your help! 🙂

**Comment by sebastienros** [comment]
You can change the default template type which is `FluidTemplate`.

`FluidTemplate.Factory.RegisterTag<QuoteTag>("quote");`

**Comment by tylersticka** [comment]
@sebastienros Thank you for the suggestion!

Would the above go in `Startup.cs`, or somewhere else?

I tried this:

```csharp
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
        TemplateContext.GlobalMemberAccessStrategy.Register<Person>();
        TemplateContext.GlobalFilters.AddFilter("slug", SlugifyFilter.Slugify);
        FluidTemplate.Factory.RegisterTag<SvgTag>("svg");
    }
}
```

But I still see a syntax error in the view:

```
Exception: Syntax error, expected: if, endif, elsif, else, unless, endunless, case, endcase, when, for, endfor, continue, break, comment, endcomment, raw, endraw, cycle, assign, capture, endcapture, increment, decrement, include, layout, renderbody, section, endsection, rendersection at line:0, col:3
```

**Comment by sebastienros** [comment]
Try in the static constructor of the Startup class, to be sure it's run before anything.

**Comment by sebastienros** [comment]
If that still doesn't work I assume I will need to change the way we register the view engine to provide a custom template type, which will be one of yours like in the documentation.

**Comment by tylersticka** [comment]
Just tried this:

```csharp
public class Startup
{
    static Startup()
    {
        FluidTemplate.Factory.RegisterTag<SvgTag>("svg");
    }

    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
        TemplateContext.GlobalMemberAccessStrategy.Register<Person>();
        TemplateContext.GlobalFilters.AddFilter("slug", SlugifyFilter.Slugify);
        // FluidTemplate.Factory.RegisterTag<SvgTag>("svg");
    }
}
```

Same result (no compilation errors, but same error in the view).

**Comment by sebastienros** [comment]
Got it working, you actually need to change `FluidViewTemplate`:

```csharp
        static Startup()
        {
            FluidViewTemplate.Factory.RegisterTag<MyTag>("mytag");
        }
```

**Comment by sebastienros** [comment]
I am adding it to the documentation

**Comment by tylersticka** [comment]
@sebastienros I feel like I still might be missing something. When I change `FluidTemplate` to `FluidViewTemplate`, I see compilation errors like this:

```
Startup.cs(7,7): error CS0246: The type or namespace name 'FluidViewTemplate' could not be found (are you missing a using directive or an assembly reference?)
```

Here is a larger look at my `Startup.cs` file, so you can see what directives I'm using as well:

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClientName.Models;
using Fluid;
using FluidViewTemplate;
using FluidMvcViewEngine;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using ClientName.Liquid.Filters;
using ClientName.Liquid.Tags;

namespace ClientName
{
    public class Startup
    {
        static Startup()
        {
          FluidViewTemplate.Factory.RegisterTag<SvgTag>("svg");
        }

        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
            TemplateContext.GlobalMemberAccessStrategy.Register<Person>();
            TemplateContext.GlobalFilters.AddFilter("slug", SlugifyFilter.Slugify);
            // FluidTemplate.Factory.RegisterTag<SvgTag>("svg");
        }
    }
}
```

**Comment by sebastienros** [comment]
Maybe you are missing a using statement. Look at the sample that does that in the repo.

**Comment by sebastienros** [comment]
`using Fluid.MvcViewEngine;` and not `using FluidViewTemplate`

**Comment by sebastienros** [comment]
Apparently you typed `using` statement by hand, hoping you'd be lucky ... you were not. Try to use Intellisense for that ;)

**Comment by tylersticka** [comment]
> Apparently you typed `using` statement by hand, hoping you'd be lucky ... you were not. Try to use Intellisense for that ;)

Ha, in this case I wasn't the one who created the `Startup.cs`! But you're right,  `using Fluid.MvcViewEngine` appears to have been missed, and restoring it fixes the problem.

Thanks for your help!
