### ISSUE TITLE
Fluid.MvcSample not listing person data

### ISSUE THREAD

**Issue by ifew** [sebastienros/fluid#88]
I develop my project with Fluid and passing model to view
it does not display my listing data

And then i pulled and try to run Fluid.MvcSample
it' same, does not display

<img width="753" alt="screen shot 2561-11-19 at 19 13 46" src="https://user-images.githubusercontent.com/1040714/48706583-43ce1f00-ec2f-11e8-837c-4cb58e11c07e.png">

**Comment by hishamco** [comment]
Strange!! @sebastienros is there anything happen after your commit https://github.com/sebastienros/fluid/commit/d7e5f21dbed1e081f1a72ae303401c66c0662604 which I don't think it will break?!!

**Comment by sebastienros** [comment]
Are you adding your class to the white list? https://github.com/sebastienros/fluid#white-listing-object-members

**Comment by sebastienros** [comment]
Sorry, I can see it doesn't work with the default sample either. I am looking at it then.
