### ISSUE TITLE
Setting encoder in MVC view engine

### ISSUE THREAD

**Issue by tylersticka** [sebastienros/fluid#89]
In [the Encoding section of the README](https://github.com/sebastienros/fluid#encoding), there's a description of how to override the default HTML encoding behavior.

How might we override this if we are using the MVC view engine?

Thank you in advance for your help!

**Comment by sebastienros** [comment]
Doesn't it work as it is documented?

There is a `{% raw %} ... {% endraw %}` too

**Comment by sebastienros** [comment]
Ok, I see, but that is so dangerous to not encode by default ...
What do your views look like to ensure you encode strings if you disable it by default?

**Comment by tylersticka** [comment]
We're just starting this project, so I don't have a complete view example to share with you unfortunately.

The alternative would be to add `| raw` filters to dozens of `{% capture %}` blocks in the LiquidJS project we're consuming templates from, which I'd hoped to avoid.

**Comment by sebastienros** [comment]
Fixed in the dev branch. However I think there is definitely something wrong. Please send me some more details about what you are trying to do, even privately (skype, email, twitter).

In the meantime I will try to imaging what scenarios could be done with `capture` in this context ...

**Comment by sebastienros** [comment]
BTW you can also create a `captureraw` tag that would be a copy paste of the `CaptureStatement` class from Fluid, but which would set the `NilEncoder` instead of flowing the default TextEncoder.
