### ISSUE TITLE
Placeholders in custom filters

### ISSUE THREAD

**Issue by TerryDieckmann** [sebastienros/fluid#95]
Hello,

I think it would be a great feature to allow the user to have placeholders as values inside (custom) filters.

Currently I have the `Min` and `Max` as custom filter. But when I try the following template, it does not work when I parse it with the `MyTemplate` parser:
 
![image](https://user-images.githubusercontent.com/18029728/49433035-55780080-f7b1-11e8-8e87-1407eda9995e.png)
Here is the `MyTemplate` parser class:

![image](https://user-images.githubusercontent.com/18029728/49432767-b81ccc80-f7b0-11e8-8494-38770bac3483.png)

Is it possible to implement this feature?

**Comment by sebastienros** [comment]
I don't understand what you call placeholders. Is the issue that the filters you describe don't work?

**Comment by sebastienros** [comment]
Reading it a second time, I don't see why it could not work. I will test it.

**Comment by sebastienros** [comment]
This example just works fine for me. Please provide a better repro if you still have an issue.
