### ISSUE TITLE
Division and multiplication filters seem to always result in 0

### ISSUE THREAD

**Issue by tylersticka** [sebastienros/fluid#99]
Example template code:

```liquid
{% assign _rating = 4 %}
{% assign _max = 5 %}
{% assign _percentage = _rating | divided_by: _max | times: 100 %}
{{_rating}} {{_max}} {{_percentage}}
```

Expected output:

```
4 5 80
```

Actual output:

```
4 5 0
```

**Comment by sebastienros** [comment]
I get the same result on http://dotliquidmarkup.org/try-online, and it looks like it's because it does `4 / 5` first, which is rounded to `0` then multiplied by `100`.

Looking at the code, there is an `int` case in the division in Fluid ... probably the issue here.
